### ISSUE TITLE
Data download - mangled columns

### ISSUE THREAD

**Issue by shevyk** [OpenBudget/BudgetKey#10]
1. Please add data download in .xls format as well as csv. Currently the file opens as giberish in Excel and requires using Excel's import wizard which most people are not familiar with and is cumbersome.

2. The data export is formatted in a way which is difficult for most users to analyse. See: https://docs.google.com/spreadsheets/d/19UW5j1UI9Oa4yfPXPrscZvws1GAqbYGOiJRXaOPPWWY/edit#gid=1652475121

![image](https://user-images.githubusercontent.com/12704845/35625701-f742faf8-069b-11e8-8ce5-1ded05c1acd7.png)

It would be better to separate entity type from name and id etc.

**Comment by akariv** [comment]
Related #12
