### ISSUE TITLE
SocialMap Sitewide: footer logos + link to forum

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#115]
see design example : https://projects.invisionapp.com/d/main#/console/7587193/290393628/preview

also, please add the following text+link to the fotter:
"רוצים לעזור? מצאתם תקלה? יש לכם שאלה?"

https://forum.hasadna.org.il/c/eknights/obudget

to be opened in a new tab

**Comment by akariv** [comment]
I need assets for all logos + 
review of all texts (I think they were copied from a previous website and not necessarily correct) +
links for all logos and texts

**Comment by noamoss** [comment]
@akariv will ask Dima on Slack for the assets.

Relevant items to keep in the footer:

| item | link |
|---|---|
צרו קשר | info@hasadna.org.il |
דווחו תקלה | https://forum.hasadna.org.il/c/eknights/obudget |
קוד האתר | (you decide which repo)
קבוצת הדיון שלנו | https://forum.hasadna.org.il/c/eknights/obudget |
API | (you know better)

**Comment by akariv** [comment]
we need links for the logos too.

**Comment by noamoss** [comment]
@akariv reopening the issue as the current status is not good enough. You said you would like to ask for @mushon  advise. Please update.

**Comment by akariv** [comment]
Footer is now according to latest design by @mushon .
Supporters should be moved to about page as discussed.
