### ISSUE TITLE
SocialMap association page: Ommit "Valid until..." label in badges block

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#120]
since we can't say when each of the badges will stop being valid, we shall omit the dynamic label part from all 3 badges (top left corner).

**Comment by akariv** [comment]
changed to 'בתוקף' as discussed

**Comment by noamoss** [comment]
@akariv please omit, as rediscussed.

**Comment by noamoss** [comment]
checked and approved on live.
