### ISSUE TITLE
מספרים וסמלים מימין לשמאל

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#127]
הסימן של ש"ח אמור לבוא משמאל למספר
הסימון של אחוז יבוא מימין למספר

![image](https://user-images.githubusercontent.com/8996235/39992550-d7c1b6de-577b-11e8-8978-81c3c06b3c9d.png)

**Comment by akariv** [comment]
Also related to #209

**Comment by YoniA** [comment]
working on it
