### ISSUE TITLE
לפסק סכומים של תקנים ועב"צ

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#128]
להוסיף פסיקים לא רק בסכומי כסף, אלא גם בסכומים של חודשי עבודה בלתי צמיתה
ותקני כח אדם

![image](https://user-images.githubusercontent.com/8996235/39992718-60c3cefe-577c-11e8-81ca-4896b9e74855.png)

**Comment by akariv** [comment]
Related to #209

**Comment by akariv** [comment]
Example:
http://next.obudget.org/i/budget/C2/2019?li=0
