### ISSUE TITLE
billions and millions

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#130]
1.  האותיות הלטיניות לא מובנות למשתמש העברי. עדיף לכתוב במפורש מיליארד ומיליון 
2. למשתמש הפשוט לא ברור מה זה 0.2 מיליארד. עדיף לכתוב 200 מיליון
3. תקציב בש"ח - סימן ש"ח בטקסט שעל הציר צריך להופיע משמאל לטקסט
4. כשהמספר במיליונים, לא צריך עוד ספרות מימין לנקודה

![image](https://user-images.githubusercontent.com/8996235/39997396-8144a69e-578b-11e8-9c7b-0474f187b3b0.png)

**Comment by akariv** [comment]
Related and similar answer as in #52
