### ISSUE TITLE
תוצאות חיפוש לא רלוונטיות

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#138]
כשמחפשים מייקרוסופט ומסננים לפי ארגון  - מה הקשר של 4 התוצאות מהסוף לחיפוש?

https://next.obudget.org/s/?q=%D7%9E%D7%99%D7%A7%D7%A8%D7%95%D7%A1%D7%95%D7%A4%D7%98&range=last_decade&dd=entities

**Comment by akariv** [comment]
נראה לי ברור, לא?

![Screen Shot 2018-08-05 at 9.57.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537482f6ebef97b1f959d236/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f66b7191a371f1172c4f5e565cb053181d1ba6acda6fb4bc2e75825a02e5d76f5726c03513a9ea8317bf01bb7689478de3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c48cb5cf349e34a5da5123571ab.png)
