### ISSUE TITLE
להציג מספר רשומות שיש בהוצאות של התקנה

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#140]
בדרופ-דאון בו בוחרים תצוגת רכש או תמיכות - להציג עמה תוצאות יש בכל קטגוריה.
לפעמים לא יודעים אם בתקנה יש רכש או תמיכות או פטורים ואז צריך לנסות את כל האפשרויות עד שמוצאים

![image](https://user-images.githubusercontent.com/8996235/40085730-270917d6-58a4-11e8-91de-8cd812875e76.png)

**Comment by maryLoi** [comment]
אופציה נוספת לדרופדאון - כל ההתקשרויות+תמיכות

**Comment by akariv** [comment]
Delegated to #207
