### ISSUE TITLE
SocialMap Activitiy Field, update the budget portion label and formula

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#142]
current:

כ-X יותר/פחות מהסכום הממוצע לכל התחומים.

new:

כ-X% מהמחזור הכספי השנתי הכולל המוערך לתחום בשלוש השנים האחרונות.

![image](https://user-images.githubusercontent.com/3581741/40109931-50e380c4-5907-11e8-8fc7-5dbd41bbabdf.png)

**Comment by noamoss** [comment]
@akariv 

![image](https://user-images.githubusercontent.com/3581741/40282322-524f9a02-5c76-11e8-9ce5-9f6ad73a9937.png)

1. add a colon.
1. add comma (possible also a line break as well)

**Comment by noamoss** [comment]
@akariv updating with a different phrase, following Shevy's idea:

"סך כספי הממשלה שהועברו לארגונים בתחום בשלוש השנים האחרונות הוא 743,825,552₪. כ- 50% מההכנסות בתחום מקורם בכספים ממשלתיים"

**Comment by shevyk** [comment]
עוד תיקון:
סך כספי הממשלה שהועברו **באופן ישיר** לארגונים
ולהסביר שבמקרים מסוימים כספי ממשלה עוברים לארגונים באמצעות גופים אחרים, למשל, כספים לבתי חולים עוברים לעתים קרובות באמצעות קופות החולים, וכספים לבתי ספר תיכוניים עוברים באמצעות רשויות מקומיות.

אחרת, האחוז מתוך המחזור פשוט לא הגיוני, למשל, [בבתי חולים ומוסדות רפואיים](https://next.obudget.org/i/reports/ngo-activity-report/%D7%91%D7%AA%D7%99%20%D7%97%D7%95%D7%9C%D7%99%D7%9D%20%D7%95%D7%9E%D7%95%D7%A1%D7%93%D7%95%D7%AA%20%D7%A8%D7%A4%D7%95%D7%90%D7%99%D7%99%D7%9D?theme=socialmap)

**Comment by akariv** [comment]
זו פשוט השוואה בעייתית - גם כי אנו לא באמת מסוגלים לעקוב אחרי כל כספי
הממשלה (לא כל ההעברות מופיעות) וגם כי המחזור הכספי חסר (לא כל העמותות
מדווחות).

**Comment by noamoss** [comment]
@akariv ^^^ wasn't fixed on `live`.

**Comment by akariv** [comment]
Looks fixed to me...


https://next.obudget.org/i/reports/ngo-activity-report/%D7%9E%D7%A8%D7%9B%D7%96%D7%99%D7%9D%20%D7%A7%D7%94%D7%99%D7%9C%D7%AA%D7%99%D7%99%D7%9D%20%D7%95%D7%9E%D7%AA%D7%A0%D7%B4%D7%A1%D7%99%D7%9D?li=0&theme=socialmap

**Comment by akariv** [comment]
<img width="496" alt="screen shot 2018-09-21 at 0 35 06" src="https://user-images.githubusercontent.com/265333/45848206-4519c300-bd36-11e8-95ec-d354157f3fc7.png">

**Comment by noamoss** [comment]
you're right. missed that.
