### ISSUE TITLE
Social Map Homepage: fix Rows override each other 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#151]
![image](https://user-images.githubusercontent.com/3581741/40298540-2c6f5efa-5cec-11e8-8478-e3a53b7ac4eb.png)

http://whatismybrowser.com/w/485BXNA

**Comment by akariv** [comment]
This happened on Shavy's computer which had strange zoom settings. 
I suggest we drop the priority for this.

**Comment by akariv** [comment]
Okay, I hacked something to handle these situations (although I don't have a laptop where this is reproduced, so mostly a blind attempt)

**Comment by noamoss** [comment]
@akariv ready on live?
