### ISSUE TITLE
Social Map: עמותות עם מידע לא מעודכן

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#154]
דוגמאות לעמותות שחסר בהן מידע (כגון סייוג, אישור ניהול תקין וכו) שטוענות כי מזינות את המידע מזה שנים בדיווח לרשם העמותות 

מנהיגות אזרחית
תפוח
זה זה
פעמונים
עמותה להעצמה כלכלית לנשים

**Comment by akariv** [comment]
האם יש הבדל בין המידע שנמצא בגיידסטאר לזה שיש אצלנו?

**Comment by akariv** [comment]
@maryLoi  ?

**Comment by maryLoi** [comment]
בדקתי עכשיו שניים מדגמית ונראה תקין
(מנהיגות אזרחית ופעמונים)
