### ISSUE TITLE
SocialMap improve/fix downloaded CSV/XSL

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#159]
the current file isn't usable

**Comment by akariv** [comment]
Please explain what 'isn't usable' means? It looks good to me.

<img width="788" alt="screen shot 2018-06-12 at 17 21 39" src="https://user-images.githubusercontent.com/265333/41296214-2028dc18-6e65-11e8-8b4e-740234856a2b.png">

**Comment by noamoss** [comment]
clicking on the 'download file' link from the search results page sends you a file with `<em>` or `[Object Object]` code embedded in cells, see for example:

```entities
name,page_title,received_amount,address lines,details,description,goal,government
"<em>הסדנא</em> רד-ליין (ע""ר)","<em>הסדנא</em> רד-ליין (ע""ר) (עמותה)",62507,,[object Object],,,
"<em>הסדנא</em> 360 פתרונות שיווק בע""מ","<em>הסדנא</em> 360 פתרונות שיווק בע""מ (חברה פרטית)",6592.95,,[object Object],,,
"מוסך <em>הסדנא</em> 2000 בע""מ","מוסך <em>הסדנא</em> 2000 בע""מ (חברה פרטית)",,,[object Object],,,
"אותות <em>הסדנא</em> בע""מ","אותות <em>הסדנא</em> בע""מ (חברה פרטית)",,,[object Object],,,
"<em>הסדנא</em> שלטים ותערוכות בע""מ","<em>הסדנא</em> שלטים ותערוכות בע""מ (חברה פרטית)",,,[object Object],,,
"מוניות <em>הסדנא</em> ירושלים בע""מ","מוניות <em>הסדנא</em> ירושלים בע""מ (חברה פרטית)",,,[object Object],,,
"<em>הסדנא</em> של דלתא בע""מ","<em>הסדנא</em> של דלתא בע""מ (חברה פרטית)",,,[object Object],,,
"<em>הסדנא</em> אדריכלים בע""מ","<em>הסדנא</em> אדריכלים בע""מ (חברה פרטית)",,,[object Object],,,
"גדי צחור <em>הסדנא</em> בע""מ","גדי צחור <em>הסדנא</em> בע""מ (חברה פרטית)",,,[object Object],,,
"<em>הסדנא</em> לידע ציבורי (ע""ר)","<em>הסדנא</em> לידע ציבורי (ע""ר) (עמותה)",,,[object Object],,,
,,,,

**Comment by akariv** [comment]
This feature is not part of the spec and will be removed in a future
version.

**Comment by noamoss** [comment]
@akariv actually, it is a needed feature (that why I asked you about it and was surprised when you told me it is implemented): this is the only way to enable users to download raw data of association by demand (out of the area/topic context).   Let's discuss before disabling it, as it is a crucial element in the site IMO.

**Comment by akariv** [comment]
It doesn't appear in any of the specs or designs for social map.
For BudgetKey, it was implemented once but in the wrong way, and needs to
be re-implmented at some point (but not in the project's near-term roadmap).

Let's define the actual use case that we're trying to address and then see
how it's best to address it.

**Comment by noamoss** [comment]
:+1:  let's discuss next Monday.

**Comment by akariv** [comment]
there's another issue for this
