### ISSUE TITLE
create search filters definitions

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#161]
### כל פעולות הרכש / מכרזים / מכרזים מרכזיים / מכרזים משרדיים / בקשות פטור ממכרז:
box 1:
1. כל המכרזים שיסגרו בחודש הקרוב
2. כל המכרזים הפתוחים מכל הסוגים
3. כל בקשות הפטור ממכרז שטרם אושרו

## התקשרויות
box 1:
1. כל ההתקשרויות מהשבוע האחרון
2. כל ההתקשרויות החדשות (פורסם תשלום לראשונה בשבוע האחרון).

## ארגונים 
box 1:
1. כל הארגוים שקיבלו תמיכה ממשלתית
2. כל הארגונים שהיו בהתקשרות עם הממשלה

box 2: [סוג ארגון]

### עמותה, חל"צ, הקדש
box 1: תחום פעילות

box 2: אזור פעילות (multiselection)

box 3:
1. כל הארגונים הפעילים שקיבלו תמיכה ממשלתית
2. כל הארגונים הפעילים שהיו בתהקשרות עם הממשלה
3. כל הארגונים בעלי ניהול אישור תקין
4. כל הארגונים בעלי אישור 46
5. כל הארגונים בעלי תו מידות

### חברה פרטית, חברת חוץ, וכל הארגונים האחרים...
box1:  סטטוס: פעיל/לא פעיל/הכל
box 2:
1. כל החברות שקיבלו תמיכה ממשלתית
2. כל החברות שהיו בתהקשרות עם הממשלה

**Comment by noamoss** [comment]
## פעולות רכש
### כל פעולות הרכש / מכרזים / מכרזים מרכזיים / מכרזים משרדיים / בקשות פטור ממכרז:

1. ספק
2. גורם מזמין
3. סכום (טווח)
4. סוג הרכש: מכרז מרכזי, מכרז משרדי, פטור ממכרז
5. סטטוס רכש: הושלם תהליך הרכש, בתהליך, לא אושר, פעיל, לא ידוע, עתידי, פתוח
6. התקשרויות מתועדות: יש/אין
7. סיבת הפטור
8. תאריך פרסום
9. תאריך עדכון

## התקשרויות

1. ספק
2. גורם מזמין
3. סכום (טווח)
4.תהליך הרכש: מכרז מרכזי, מכרז משרדי, פטור ממכרז
5. סטטוס תהליך הרכש: הושלם תהליך הרכש, בתהליך, לא אושר, פעיל, לא ידוע, עתידי, פתוח
6. תאריך פרסום
7. תאריך עדכון
8.סכום שאושר (טווח)
9. סכום שהועבר (טווח)

## ארגונים 
1. סוג הארגון: חברה פרטית, קופת גמל, חל"צ, הקדש, אגודה שיתופית, עמותה, 
(I assume it will be a dynamic field, so did not include all possible values here)
2. כספי מדינה ב-3 השנים האחרונות (טווח)
3. כתובת רישום (עיר)

### עמותה, חל"צ, הקדש
1. סטטוס: פעיל/לא פעיל
2. תחום פעילות
3. אזורי פעילות (ריבוי בחירה)
4. מחזור כספי שנתי מדווח (טווח)
5. קיבל/ה תמיכות: כן/לא
6. תמיכה ממשרד:
7. התקשרויות עם הממשלה: כן/לא
8. התקשרויות עם (גורם ממשלתי):
9. כספי מדינה ב-3 השנים האחרונות (טווח)
10. מספר עובדים (טווח)
11. מספר מתנדבים (טווח)
12. אישור ניהול תקין: כן/לא
13. אישור 46: כן/לא
14. תו מידות: כן/לא

### חברה פרטית, חברת חוץ, וכל הארגונים האחרים...
1. סטטוס: פעילה / לא פעילה
2. שנת הקמה
3. כספי מדינה ב-3 השנים האחרונות (טווח)
4. כתובת רישום (עיר)
5. קיבל/ה תמיכות: כן/לא
6. תמיכה ממשרד:
7. התקשרויות עם הממשלה: כן/לא
8. התקשרויות עם (גורם ממשלתי):
9. כספי מדינה ב-3 השנים האחרונות (טווח)


## סעיף תקציבי
1. סעיף  תוקף: כן/לא
2. שנים (טווח)
3. גובה הסכום שאושר (טווח)
4. גובה הסכום ששולם (טווח)
5.  בוצעו תמיכות במסגרת הסעיף: כן/לא
6. בוצעו התקשרויות במסגרת הסעיף: כן/לא
7. בוצעו העברות תקציביות
8. תאריך העברות תקציביות (טווח)

**Comment by noamoss** [comment]
limit to 3 filters.

**Comment by noamoss** [comment]
@akariv when possible, better keep the current time filter in addition to the above.

**Comment by akariv** [comment]
מכרזים / פטורים - חיפוש ממוקד, לפי ההקשר
התקשרויות - חדשות מהרבעון האחרון, פעילות
הכל: בלי סינונים
