### ISSUE TITLE
add "remove all subscribes" button 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#170]
![image](https://user-images.githubusercontent.com/3581741/41856020-bd499906-789c-11e8-8d92-65df47cfc964.png)

we need a design for "delete all" button in the personal area.

**Comment by mushon** [comment]
added here:
https://projects.invisionapp.com/d/main#/console/7587193/286008737/preview

**Comment by noamoss** [comment]
@akariv ready for you.
