### ISSUE TITLE
open procure: homepage components (top part)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#175]
https://projects.invisionapp.com/d/main#/console/7587193/303778873/preview:

1. Logo

2. search field (notice the search field should cover the top half of screen, like in the social map homepage, and scroll down when the user clicks on the tabs below.

3. dynamic text:

<div dir="rtl">
ב[שנה שעברה] רכשה המדינה סחורות ושירותים בכ-[סכום כספי]. פעולות הרכש  כללו
[מספר מכרזים מרכזיים] מכרזים מרכזיים של  מנהל הרכש וב-[מכרזים משרדיים] מכרזים משרדיים של [מספר משרדים שפרסמו מכרזים משרדיים]. בנוסף, אושרו [מספר בקשות פטור ממכרז שאושרו] פעולות רכש בפטור ממכרז בשנה זו.
</div>

the following terms should include a pop-up
<div dir="rtl">
מכרזים מרכזיים: מכרז הנערך מטעם החשב הכללי באוצר עבור משרדי הממשלה השונים
מכרזים משרדיים: מכרזים מטעמם של משרד או משרדים בודדים
פטור ממכרז: ישנם כ-30 מקרים בהם לפי החוק גופים ממשלתיים פטורים מעריכת מכרז.
</div>

![image](https://user-images.githubusercontent.com/3581741/42134531-3d9c4b28-7d46-11e8-9876-7416570d1e59.png)

(lower part to be handled in follow-up issues)

**Comment by akariv** [comment]
2nd part of the sentence in (3) is missing a verb.

**Comment by noamoss** [comment]
@akariv I think I understood you, fixed.

**Comment by akariv** [comment]
Still missing:

למשל: ״5 מכרזים מרכזיים של מנהל הרכש וב-3 מכרזים משרדיים של 4״ זה לא משפט...

**Comment by noamoss** [comment]
fixed

**Comment by noamoss** [comment]
@akariv reopening issue, as our design/ux department, asked to set a common box height per row.

**Comment by noamoss** [comment]
sorry, closing in favor of https://github.com/OpenBudget/budgetkey-themes/issues/19#issuecomment-407147511
