### ISSUE TITLE
open procure: homepage components (lower part, supplier)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#176]
follow-up of #175, for the default chosen tab: supplier

![image](https://user-images.githubusercontent.com/3581741/42134611-06acf0c0-7d48-11e8-83e3-5d717941b53e.png)

### 1. אף פעם לא עבדנו עם גורמים בממשלה

| square | question header | answer | button label | button link |
|---|---|----|---|---|
2A| איך זה עובד בדיוק? | הממשלה ויחידותיה רוכשת וצורכת שירותים רבים. תהליך הרכש יכול להתבצע בצורת מכרז מרכזי (לכל יחידות הממשלה), מכרז משרדי או בצורה של פטור ממכרז במקרים שמוגדרים בחוק. לאחר אישור תהליך הרכש מתבצעות התקשרויות והעברות התשלום בין הגורם הרוכש לספק.| קראו עוד על תהליכי רכש | /methods_details |
2B| איך האתר הזה יכול לעזור לי | אתר "רכש פתוח" אוסף ומאחד מידע ממקורות ממשלתיים שונים. תוכלו לצפות במידע כל מכרזים ורכישות עתידיות ולנתח העברות כספים שתועדו בעבר. | ספרו לי עוד על מקורות המידע  | /more_info
2C| מאיפה מתחילם? | חפשו נושא, שירות או מוצר אותו הייתם רוצים להציע לממשלה כדי לראות לצפות בהיסטוריית הרכש וההתקשרויות. ניתן גם להזין במסך החיפוש שמות של עסקים דומים כדי לצפות בהתקשרויות עבר והווה שלהם עם גופי ממשל ולאחר מכן להירשם לקבלת עדכונים שוטפים.| לחיפוש | to the top of the homepage

### 2. אנחנו כבר מספקים סחורה / שירותים לממשלה

| square | question header | answer | button label | button link |
|---|---|----|---|---|
3A | איך אוכל ללמוד עוד על התקשרות או פעולת רכש | בכל אחד מהמסכים תממצאו טבלת שאילתות חכמה. תוכלו ללמוד בעזרתה על אופן העברת הכספים, סכומים, תאריך וגופים נוספם | לדוגמה | /explore_info
| 3B |איך אפשר להשאר מעודכנים?| מערכת "רכש פתוח" מצליבה מידע מממספר מקורות. תוכלו לראות מה השתנה בשבוע או בחודש האחרון, ולקבל עדכונים שבועיים בנושאים שמעניינים אתכם. | למסך החיפושים השמורים | personal page | 
| 3C | מצאתי תהליך רכש מעניין, מה אפשר לעשות? | בכל אחד מסוגי תהליכי הרכש ישנם שלבים שונים. נציג לך רעיונות לכיווני פעולה אפשריים במסכים השונים, אבל תמיד אפשר גם לקרוא עוד. | ספרו לי עוד | moethods_details

**Comment by akariv** [comment]
Where the button links should go to?
Are these new pages that need to be designed?
(i.e. 
/methods_details
/explore_info
/more_info
)

**Comment by noamoss** [comment]
@akariv 

>I don't remember talking about other pages, but we can do modals with some extra content if it's really necessary.

we did, but modals seem to be good as well. I will define them separately, for now, let's have placeholders until I have the edited content.

**Comment by mushon** [comment]
זו התחלה מצויינת אבל אני מרגיש שגם הנושאים לא כלכך מחודדים וגם הטקסטים קצת ארוכים מדי.
מה שאני מצרף פה עדיין ברמה של וויירפריימז, אבל הוא יתן קצת מושג:
![hp suppliers](https://user-images.githubusercontent.com/27123/42181066-2af77504-7e42-11e8-85aa-bb39d4c3f404.png)

אני חושב שהשאלות והנושאים שהיו לנו בשבוע שעבר היו מדוייקים יותר. שווה סיבוב נוסף בעיני…

**Comment by noamoss** [comment]
@mushon
יש שתי שאלות שחשוב לנו להכניס, אבל לא נוכל לעשות את זה עד שנוסיף את מנגנון הדמיון-בין-ישויות, כך שגם לספק וגם למשתמש אנחנו מתכננים להחליף.

 שוחחתי על זה עם אדם טלפונית מוקדם יותר: כרגע נכניס את התכנים כמו שכתבתי אותם כדי לקבל מושג ויזואלי ונשפר טקסטים ועיצובים מאוחר יותר. אין לנו זמן לחכות עם זה עד שאחזור מחופשה ותיקון של זה לא ידרוש הרבה עבודה.
