### ISSUE TITLE
Add political donations to people pipelines

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#178]
Political donations are collected in the donations/transactions pipeline.

We want to add donation events (who donated how much to whom) to the person event list in the people pipeline.

We don't have a 'proof' url per donation, but we can link to the Mevaker website for all items: 

http://www.mevaker.gov.il/(X(1)S(uuokupc212t5005shmjbxtbd))/he/mimun/donation/Pages/default.aspx?AspxAutoDetectCookieSupport=1

@odedsh

**Comment by slallum** [comment]
starting to work on it

**Comment by slallum** [comment]
This can be closed, right?

**Comment by akariv** [comment]
Yep. Thanks!
