### ISSUE TITLE
לא מופיעה ההקצאה בתקנה

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#187]
מחפשים "סבסוד מעונות יום". התוצאה השלישית והרביעית זהות במספר ושם תקנה. למה?

![image](https://user-images.githubusercontent.com/8996235/43133982-2057a426-8f49-11e8-9509-2f9a6183a6b6.png)

אם נכנסים סעיף הראשון, מ-2017, בדף התוצאות אין סכום למרות שבחיפוש יש

![image](https://user-images.githubusercontent.com/8996235/43134043-6419240a-8f49-11e8-9665-5263ebc93b5e.png)

**Comment by akariv** [comment]
One shows original, other revised.
Needs to be fixed.

Also related to #209

**Comment by akariv** [comment]
We need to align the amount we're showing.
Generally all amounts need to be 'revised' ones, but we need to mention the approved budget in case it was different.
