### ISSUE TITLE
התקנה בשורת חיפוש מוצגת עם שני אפסים מובילים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#189]
ברשימת הוצאות בתוך תקנה לוחצים על מספר תקנה, מגיעים לדף חיפוש: התקנה בשורת חיפוש מוצגת עם שני אפסים מובילים

![image](https://user-images.githubusercontent.com/8996235/43134644-5b8acd78-8f4b-11e8-99be-77986757c0ca.png)

**Comment by akariv** [comment]
Can't see the big problem here, but in any case: need to update the search target in the questions.

**Comment by maryLoi** [comment]
זה מבלבל משתמשים כי הם לא מבינים שתקנה 0060... היא אותה התקנה כמו 60.... י

**Comment by nadavs123** [comment]
Pushed a fix for this issue
