### ISSUE TITLE
מציג הוצאות ששולמו במקום שאושרו

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#190]
![image](https://user-images.githubusercontent.com/8996235/43134812-f4b6e68a-8f4b-11e8-9a97-14dcfc6eabcd.png)

**Comment by akariv** [comment]
השאילתה מציגה סכומים ששולמו, לפי תמיכות שאושרו או ששולמו בשנה כלשהי

**Comment by akariv** [comment]
השאילתא שונתה למשהו פחות מבלבל
