### ISSUE TITLE
open procure: fix (office/central/exemption) tender page arrows  spending link

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#198]
These small arrows are currently leading users to the (non-existing) company page, while they should lead to the התקשרות page.

https://next.obudget.org/i/tenders/office/516787/4-2010?li=11&theme=govbuy

![image](https://user-images.githubusercontent.com/3581741/43408062-10d95d48-9429-11e8-968a-ce179b7c616b.png)

**Comment by akariv** [comment]
There could be more than one contract. Which of the contracts should it lead to?

**Comment by noamoss** [comment]
not sure I understand the question... each arrow should lead to the relevant contract (with the relevant supplier)

**Comment by noamoss** [comment]
oh... got you. this is a scenario we have not considered.

I can see two possible solutions:

1. adding an arrow for each (separate) contract (maybe adding a column header "התקשרויות" as well)

2. using the arrow to send the user to the most recent (last updated) contract. 

I prefer the functionality of the first option, as this is the main gateway into the contract's page (according to our flow) and because the 2nd option is a bit misleading. 


@akariv @mushon What do you think?

**Comment by akariv** [comment]
Consider there can be 1000s of contracts per supplier.

Graffiti office supplies has 8,860 contracts in a single tender.

Should be resolved using the queries at some point, or using search, or
link to 'most relevant contract' (e.g. largest which is still active or
largest if none is active any more), but that's something that needs to be
resolved in the design.

**Comment by noamoss** [comment]
>using the queries

can we use a link for contracts between the publisher and the relevant suppliers only? if so, it's good enough for now.

**Comment by akariv** [comment]
1. not atm
2. it will only fetch 100 rows, which might not be enough in many cases

**Comment by noamoss** [comment]
@mushon let's discuss this next Monday

**Comment by noamoss** [comment]
@akariv is the following idea applicable (technically): we will have two icons per row: 

1. (arrow) wil take you to the latest contract.
2 (file) will take you to the query table and will set a query for all the contracts between the publisher and the supplier.

**Comment by noamoss** [comment]
@akariv 

>1. why am I now seeing only 3,000 in this contract

this will self-explained by the icon/header. 

>2. This is the same suggestion from above, which is not possible atm
not the same. before I asked about a search result page and here I am asking for a query in the lower table (which is easier to implement, isn't it?)

**Comment by noamoss** [comment]
ok ok ok

one --> many --> many

we will add a counter for scenarios in which we have more than 1 contracts inside the tender + link (probably to the most recent contract).

**Comment by noamoss** [comment]
following a talk with Mushon:

1. supplier name (right column) will be linked to the company page (once it is ready).
2. add a number of contracts in the table (see design link below)
3. for now we will drop the arrow icon (+link). Once we will have the technical ability to link to a specific predefined query, we will add a new icon with an internal link.

https://projects.invisionapp.com/d/main#/console/7587193/276178413/preview

**Comment by akariv** [comment]
http://next.obudget.org/i/tenders/central/553418/technology-2-2014?li=15

**Comment by noamoss** [comment]
@akariv looks good, but I am reopening to deliver a question to our UX chief:

@mushon currently I need to hover over the company name to know it is clickable. Would you suggest to keep as is, or to keep it underlined?

![image](https://user-images.githubusercontent.com/3581741/43785670-825a8c8e-9a6f-11e8-9d9b-e2511c294128.png)

**Comment by mushon** [comment]
Definitely underline :)

Thanks!

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by akariv** [comment]
I actually tried with the underline at first and it looks really
terrible... but you're the boss :)
