### ISSUE TITLE
Add missing combinations for exemptions

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#200]
('התקשרות ששוויה אינה עולה על 50,000 ש"ח', 'הוחזר לשולח', True, True)
('ציוד רפואי יחודי - (חוק ישן)', 'פניות ישנות לבירור מול המשרד', True, True)
('תקנה 5(ג) - (חוק ישן)', 'הוחזר לשולח', True, False)
('התקשרות ששוויה אינה עולה על 50,000 ש"ח', 'הוחזר לשולח', True, True)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'נרשם', False, False)
('התקשרות של לשכת הפרסום הממשלתית', 'דיווח תקין ומאושר', True, True)
('התקשרות עם מומחה-רכישת השכלה או הכשרה מקצועית-פניה תחרותית לקבלת הצעות', 'אושר ע"י ועדת הפטור המרכזית', True, False)
('שירותים שעניינם תרבות, אמנות, בידור או הווי', 'הוחזר לשולח', True, True)
('לא הוגשה כל הצעה במכרז/ועדת המכרזים לא המליצה על הצעה כלשהי', 'דיווח תקין ומאושר', True, False):
('התקשרות של נציגות או סניף של המשרד במדינת חוץ - (חוק ישן)', 'דיווח תקין ומאושר', True, True)

**Comment by noamoss** [comment]
@akariv updated in https://docs.google.com/spreadsheets/d/1lM2Afiw2JMJzHMIvWt3XylWLy2PLmVGbqaR9laBXFNo/edit#gid=1604640775

please close issue to confirm it is ok now.

**Comment by akariv** [comment]
Still missing:
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'אושר ע"י ועדת הפטור המרכזית', False, False)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'נרשם', False, False)

**Comment by akariv** [comment]
More missing entries for exemptions: 
('הענקת זכויות במקרקעין לצרכי ציבור', 'נרשם', True, True)
('רכישת תרופות, נסיובים או תרכיבים, שהינם יחודיים', 'בטיפול', True, False)
('התקשרות המשטרה עם בעל רעיון יחודי', 'טרום החלטת ועדה', True, False)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'אושר ע"י ועדת הפטור המרכזית', False, False)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'נרשם', False, False)

For tenders:
('central', 'הסתיים', False, False)
('central', 'בוטל', False, False)
('central', 'פורסם וממתין לתוצאות', True, False)

**Comment by noamoss** [comment]
@akariv fixed both files.

**Comment by akariv** [comment]
I added the two tender items, please check and fix if needed (marked with blue highlight)

**Comment by noamoss** [comment]
updated 362/703... will update

**Comment by akariv** [comment]
Still missing:
('שירותים שעניינם תרבות, אמנות, בידור או הווי', 'הוחזר לשולח', True, False)
('רכישת תרופות, נסיובים או תרכיבים, שהינם יחודיים', 'בטיפול', True, False)
('מכרז סגור - הוראת שעה', 'נרשם', True, True)
('central', 'עודכן', False, False)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'אושר ע"י ועדת הפטור המרכזית', False, False)
('התקשרות של יחידה למחקר מדעי  - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'נרשם', False, False)

**Comment by noamoss** [comment]
@akariv done.

**Comment by noamoss** [comment]
@akariv added:

* ('הענקת זכויות במקרקעין לצרכי ציבור', 'נרשם', True, False)
* ('התקשרות בנסיבות מיוחדות ונדירות', 'נרשם', True, False)
* ('התקשרות עם הסוכנות היהודית או ההסתדרות הציונית', 'בטיפול', False, False)
* ('התקשרות עם חברה ממשלתית', 'בטיפול', False, False)

for the followings, I think it is already there, I prefer not to duplicate it, please check:

>('התקשרות של יחידה למחקר מדעי - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'אושר ע"י ועדת הפטור המרכזית', False, False)

see line 424 [in the file](https://docs.google.com/spreadsheets/d/1lM2Afiw2JMJzHMIvWt3XylWLy2PLmVGbqaR9laBXFNo/edit#gid=1604640775). 

>('התקשרות של יחידה למחקר מדעי - ביצוע שיתוף פעולה בתחום מו"פ והוראה', 'נרשם', False, False)

see line 425.

a possible reason for the error: we have a sensitive character (`"`)

**Comment by akariv** [comment]
last ones:
central: ('central', 'בוטל', True, False)
exemption: ('הענקת זכויות חזקה במקרקעין לקק"ל', 'נרשם', True, True)

**Comment by noamoss** [comment]
@akariv 

done.

>last ones:

you don't know that.

**Comment by akariv** [comment]
('central', 'חדש', False, False)
('בחינת קיומם של ספקים ע"י החשכ"ל', 'אושר ע"י ועדת הפטור המרכזית', False, False)
('בחינת קיומם של ספקים ע"י החשכ"ל', 'טרום החלטת ועדה', False, False)
('בחינת קיומם של ספקים ע"י החשכ"ל', 'נרשם', False, False)
('הענקת זכויות במקרקעין שנתקיימו לפחות שני מכרזים פומביים', 'נרשם', False, False)
('התקשרות עם הסוכנות היהודית או ההסתדרות הציונית', 'טרום החלטת ועדה', True, True)
('התקשרות עם קרנות הנשלטות בידי הסוכנות, ההסתדרות הציונית או קרן היסוד', 'טרום החלטת ועדה', False, False)
('התקשרות של נציגות או סניף של המשרד במדינת חוץ - (חוק ישן)', 'דיווח תקין ומאושר', True, False)

**Comment by noamoss** [comment]
@akariv items 2-8 are missing a field (tender type).

**Comment by akariv** [comment]
You really forgot everything about this :D

First one is a tender.
2-8 are exemptions.

Like here: https://github.com/OpenBudget/BudgetKey/issues/200#issuecomment-416182819

**Comment by akariv** [comment]
Exemption spreadsheet: https://docs.google.com/spreadsheets/d/1lM2Afiw2JMJzHMIvWt3XylWLy2PLmVGbqaR9laBXFNo/edit#gid=1604640775

Tender spreadsheet:
https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit#gid=0

**Comment by noamoss** [comment]
@akariv thanks, indeed, forgot it all... :)

fixed, feel free to close the issue.
