### ISSUE TITLE
imrpove tooltips: make greedy

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#201]
some terms (like מנהל הרכש / מנהל הרכש הממשלתי) have longer and shorter versions, and both versions are included in the table. We should always prefer the longer version, and prevent the tooltip of the shorter version from appearing as well.

![image](https://user-images.githubusercontent.com/3581741/43461447-31000258-94dc-11e8-9ec8-633e3387ba56.png)

**Comment by akariv** [comment]
Order tooltips in table so that bigger is before smaller.
