### ISSUE TITLE
social map: create about content

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#204]
http://next.obudget.org/about/?theme=govbuy

Edit the files here to update:
https://github.com/OpenBudget/budgetkey-app-about/tree/master/abouts

**Comment by noamoss** [comment]
pushed https://github.com/OpenBudget/budgetkey-app-about/pull/2/ without being able to check/verify results locally. Please reassign to me when I can QA on live.

**Comment by akariv** [comment]
Will be done when we work on social map

**Comment by noamoss** [comment]
@akariv so how come it is not prioritized...? (was it on purpose or by mistake)

**Comment by akariv** [comment]
@noamoss added the links to the footer.
