### ISSUE TITLE
open procure: fix central tenders page info values and labels

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#205]
http://next.obudget.org/i/tenders/office/600875/11-2017?li=0&theme=govbuy
https://www.mr.gov.il/CentralTenders/technology/Pages/11-2017.aspx

![image](https://user-images.githubusercontent.com/3581741/43541831-09ad874a-95d4-11e8-9c15-a6c94212c178.png)

**Comment by akariv** [comment]
Problem - this tender appears both as a central tender and as an office tender:
https://www.mr.gov.il/officestenders/Pages/officetender.aspx?pID=600875
Notice they have different names (but similar).

When scraping office tenders I can't tell if there is a central tender that points to it.

Possible solution:
- If publisher is 'משרד האוצר מנהל הרכש' set the type to central regardless of where I found it.
- If title starts with 'מכרז מרכזי' then remove these words (?)
- After סטטוס put the contents of 'extended_status'

Please approve the above ^

**Comment by noamoss** [comment]
@akariv 

>When scraping office tenders I can't tell if there is a central tender that points to it.

...why not? I mean, why can't we check if the publication number already exists, and always prefer central over office?

Anyhow, assuming there is a good for why not, I would go fo the followings:

>If publisher is 'משרד האוצר מנהל הרכש' set the type to central regardless of where I found it.

can do

>If title starts with 'מכרז מרכזי' then remove these words (?)

would no do that. Sounds to too risky, I think, and we might not cover all relevant scenarios. Unless you can tell we have hundreds of fake office tenders titles starting with these two words.

>After סטטוס put the contents of 'extended_status'

yep.

**Comment by akariv** [comment]
> would no do that. Sounds to too risky, I think, and we might not cover
all relevant scenarios. Unless you can tell we have hundreds of fake office
tenders titles starting with these two words.

that's the first thing you highlighted - so this means that we're keeping
the title as-is?

**Comment by noamoss** [comment]
@akariv reopening the issue to ask you to explain what exactly did you change in the logic.

**Comment by akariv** [comment]
As we said above:
- If publisher is 'משרד האוצר מנהל הרכש' set the type to central regardless of where I found it.
- After סטטוס put the contents of 'extended_status'
