### ISSUE TITLE
Show year range for budget items

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#208]
Budget items have a year range (and we have one page that shows the most latest data for each item + its history).

We want to add some text saying 'this item was active between the years X and Y' or 'this item was only active on the year Z'

**Comment by yotam707** [comment]
I'm on it

**Comment by akariv** [comment]
sample page: https://next.obudget.org/i/budget/0020460214/2018?li=0

**Comment by akariv** [comment]
Relevant repo - github.com/OpenBudget/budgetkey-app-generic-item

**Comment by SanSunB** [comment]
I'm working on this :)
