### ISSUE TITLE
budgetkey: create about page content

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#210]
perhaps @noamoss can take this too?

Some work was done in:
#188
#85
#162
#191

**Comment by noamoss** [comment]
@akariv sure, no problem

**Comment by noamoss** [comment]
(will need your guidance/review, though, when ready).

**Comment by noamoss** [comment]
@akariv pushed v1.0 (https://github.com/OpenBudget/BudgetKey/issues/220), without being able to watch it on my screen. Please let me know when merged, so I will QA there.

**Comment by noamoss** [comment]
@akariv pushed v2.0 (https://github.com/OpenBudget/budgetkey-app-about/pull/3). Please notice two mini issues which are on your side now:

1. as we agreed on the the "Social Map" about page, icons should be spread/aligned to both sides:
![image](https://user-images.githubusercontent.com/3581741/44677735-5a554780-aa3f-11e8-9953-9f0abfac7073.png)

2. If you have hasadna's logo file with text, please replace in the assets folder.

3. budget-key about page currently don't have "staff" section, as I don't know who should be listed. If you have a list name of contributors, please add it. Anyhow, notice we are linking to this part from the footer site-wide.
