### ISSUE TITLE
מספר מזהה

### ISSUE THREAD

**Issue by hoteralon** [OpenBudget/BudgetKey#211]
שלום! שמתי לב שבנתונים המופיעים לגבי גופים נתמכים מתקציב המדינה כבר לא מופיע מספר התאגיד. אני מוריד טבלת אקסל ואין לי את הנתון הזה .... מדוע ? תודה

**Comment by akariv** [comment]
תודה על הדיווח - נתקן בקרוב.

**Comment by akariv** [comment]
תוקן באתר
