### ISSUE TITLE
open procure: fix tooltip expanded text

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#213]
http://next.obudget.org/i/tenders/central/600875/technology-11-2017?li=1&theme=govbuy

`להירשם להתראות` is marked for hovering, but no text appears (even though it exists on the [relevant table](https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit#gid=0))

![image](https://user-images.githubusercontent.com/3581741/43709159-ca769d1a-9974-11e8-9424-9494878269f0.png)

**Comment by akariv** [comment]
The problem is that the text in the tooltip is dark?

**Comment by noamoss** [comment]
yep.
