### ISSUE TITLE
Open procure: old central tender pages does not include status labels and search results position

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#214]
http://next.obudget.org/i/tenders/central/516787/4-2010?li=2&theme=govbuy
https://www.mr.gov.il/officestenders/Pages/officetender.aspx?pID=516787:

![image](https://user-images.githubusercontent.com/3581741/43709966-f1d42240-9976-11e8-97b0-45999a6ad0e1.png)

This is correct for old central tenders (in the `הסתיים` stage), and probably has a negative side effect - of pushing them up in the search results page:

![image](https://user-images.githubusercontent.com/3581741/43710065-3922c124-9977-11e8-9171-48f8b20741c5.png)

another example: http://next.obudget.org/i/tenders/central/607643/Goods-13-2017?li=9&theme=govbuy

**Comment by akariv** [comment]
Do you have the correct settings in the lookup table @noamoss?

**Comment by akariv** [comment]
i.e. issue #200

**Comment by akariv** [comment]
Depends on #216

**Comment by noamoss** [comment]
checked and approved.
