### ISSUE TITLE
open procure: fix central tender actionable tip design

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#215]
http://next.obudget.org/i/tenders/office/619128/1583?li=3&theme=govbuy:

![image](https://user-images.githubusercontent.com/3581741/43710386-289b0e14-9978-11e8-97f5-f55fadb0b5b6.png)

(actinable tip box should be wider)

**Comment by akariv** [comment]
Link?

**Comment by noamoss** [comment]
checked and approved on live.
