### ISSUE TITLE
open procure: search results boost by `simple descision`

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#216]

**Comment by noamoss** [comment]
@akariv 

## tenders:
| simple decision | boost |
| --- | -- |
| סגור | 2
| הסתיים | 2
| עתידי | 6
| בוטל | 1
| פתוח | 8

## exemptions:
| simple decision | boost |
| --- | -- |
|אושר פטור ממכרז|  8
|בתהליך| 8
|לא אושר| 4

**Comment by noamoss** [comment]
@akariv looks much better. I could still find needed improvements in terms of weighting (like when searching for "הספקה") - but we will find a time to handle this and fine-tune the formula later.

**Comment by noamoss** [comment]
@akariv ok, I guess we should explore it a bit more.

Look at these results (https://next.obudget.org/s/?q=%D7%A6%D7%99%D7%95%D7%93&dd=central-tenders&range=last_decade&theme=govbuy&focused=no&lang=he):

![image](https://user-images.githubusercontent.com/3581741/43786126-95e6107e-9a70-11e8-951b-e01e95f6773c.png)

We need to understand how come the "future" appears beneath the "closed" one.

**Comment by noamoss** [comment]
could you provide formula's results for the first 3 items? (unless you have a more efficient way to explore it)

**Comment by akariv** [comment]
First one get 800,000 and second one gets 2,400,000.
Combined with the text matching score first one ends up with ~970K and 2nd
one with ~840K.
Reason for that is a bad parameter for combining scores from different
fields, and since 1st result contains the word 'ציוד' in more fields it
gets a better matching score.
I've changed it to use the best score from the best field (and not the sum
of all fields) to level the playing field.

Check out the results now (after the change) and lmk.

**Comment by noamoss** [comment]
@akariv it is better -  but we are still missing (underweighting) one important component, I think: the topics labels of the tenders.

See for example results 21 + 22 in the example above:

http://next.obudget.org/i/tenders/central/0/technology-25-2018?li=20&theme=govbuy

http://next.obudget.org/i/tenders/central/0/network-10-2018?li=21&theme=govbuy

both are future tenders, that include the searched query ("ציוד") and should appear (IMO) before the other closed results.

**Comment by akariv** [comment]
Well, it makes sense that results that actually have the queried term in their title will get a higher score than results that only contain the term in a secondary field (which is often spammy)

**Comment by noamoss** [comment]
@akariv 
> it makes sense that results that actually have the queried term in their title will get a higher score than results that only contain the term in a secondary

right, but this is not the case here. It does not make sense that open tenders with the quired terms in their label will show beneath closed tenders with the quired term in the title.

Let me put it in another way: I believe label texts should be weighted as title words when sorting results. I bet that most of the times they describe the meaning and the purpose of the purchase better than the description, just like in the given examples on my last comment.
