### ISSUE TITLE
הבדל בין סך לכלל התקשרויות

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#22]
ההבדל בין שתי האופציות לא ברור מיד. אפשר להוסיף טולטיפ שמסביר?

כלל ההתקשרויות עם הארגון ב כל השנים
סך ההתקשרויות עם הארגון מ כל השנים

**Comment by akariv** [comment]
איזה ניסוח היה יותר ברור לדעתך?

**Comment by maryLoi** [comment]
אולי

כלל ההתקשרויות -> דיווח רבעוני של הוצאות רכש/ התקשרויות
סך ההתקשרויות -> ריכוז התקשרויות 

בנוסף, ב'סך התקשרויות' אין תיאור מטרת ההתקשרות

**Comment by akariv** [comment]
סך ההתקשרויות הוא הסך הכל לפי גורם מזמין - אז לא תהיה שם מטרה.
כלל ההתקשרויות הן לא לפי רבעונים אלא פשוט ההתקשרויות...

**Comment by akariv** [comment]
תיקנתי את הניסוח
