### ISSUE TITLE
open procure: update project logo

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#220]

**Comment by noamoss** [comment]
@mushon please add the link to the updated version and any relevant instructions.

**Comment by mushon** [comment]
The icons (like all other assets)

 are available on InVision Inspect:
Positive:
https://projects.invisionapp.com/assets/7587193/153704852/BA1F4FA4144CAE7EDF8164750397A14F304F4480C703F3CC308F22290191A6DF/download

Negative:
https://projects.invisionapp.com/assets/7587193/153342563/BC5AA383DC6336F40229AFA2BBB81B6148E81985B0E2DB33972B3EC35EAEE94A/download

(Also attached here for reference)
[openprocure_logos.zip](https://github.com/OpenBudget/BudgetKey/files/2300148/openprocure_logos.zip)

**Comment by noamoss** [comment]
checked and approved on live.
