### ISSUE TITLE
לסגור תיבת דיאלוג של טבלת התקשרויות

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#222]
כשפותחים את ה דיאלוג בוקס, צריך שהוא יסגר אחרי שעושים קליק בכל מקום בדף, ולא רק בחץ של הדיאלוג

![image](https://user-images.githubusercontent.com/8996235/44085811-482e0c80-9fc3-11e8-8eab-d66eeb06c7c3.png)

**Comment by akariv** [comment]
Related to #207
