### ISSUE TITLE
Add tooltip for amount in tender

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#227]
Explaining that it comes from the sum of contracts and not some information about the tender itself.

e.g. http://next.obudget.org/i/tenders/central/537978/4-2002?li=0

**Comment by noamoss** [comment]
@akariv text to add as tooltip:

הסה"כ מייצג את סך כל ההחייבויות לתשלום שפורסמו עד כה על ידי הגורם הממשלתי במסגרת ההתקשרות המסויימת הזו, עם הספק הרלוונטי. סכום זה עשוי להשתנות ולגדול עם הזמן, בהתאם לתנאי המכרז או הפטור ממכרז שבמסגרתם מתבצעת ההתקשרות.

**Comment by noamoss** [comment]
well, it not what I had in mind, but I can live with it.
