### ISSUE TITLE
Social Map: add missing links to the footer

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#229]
following #204, users currently cannot reach it, since the footer is not full: we are missing links to
 * אודות
* הצוות
* API
* מדיניות פרטיות

all are links to sections in the about page.

**Comment by akariv** [comment]
done

**Comment by noamoss** [comment]
@akariv sorry, but the internal links are not working as they should  - might need to change URL anchors or the markdown of the about pages.

**Comment by akariv** [comment]
fixed now

**Comment by noamoss** [comment]
checked and approved on live.
