### ISSUE TITLE
in dropdown first option is duplicate

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#23]
אם נמצאים ב"כלל התמיכות מתקציב זה ש אושרו"
כשלוחצים על החץ ופותחים את הדרופדאון, האפשרות הראשונה משוכפלת

![image](https://user-images.githubusercontent.com/8996235/37426474-3eb52eac-27cf-11e8-99f3-a38066bdffb0.png)

**Comment by akariv** [comment]
למטה זה הדרופדאון, למעלה זה מה שבחרת.

@mushon מה דעתך?

**Comment by maryLoi** [comment]
אם יש אופציה שכבר בחרתי, הייתי מצפה שהיא לא תופיע שוב ברשימה
