### ISSUE TITLE
דיסקליימר עבור "צרו קשר

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#232]
עבור גולשים שטועים לחשוב שדף חברה במפתח הוא אתר רשמי של חברה, ופונים לסדנא לבקש חשבוניות או לאמץ גורי חתולים. צריך שהקישור ל"צרו קשר" יוביל לדף עם דיסקליימר המסביר שזה לא אתר חברה

**Comment by akariv** [comment]
Needs text and design

**Comment by noamoss** [comment]
רגע, לפני שאתם שולחים!
האתר הזה אמנם מציג מידע על חברות וארגונים מכל הארץ, אבל זהו **אינו** האתר שלהם.
אם אתם מעוניינים ליצור קשר עם חברה או ארגון פנו אליהם באמצעות פרטי הקשר המופיעים באתר, ב[מודיעין הטלפונים](https://www.b144.co.il/) או באתר האינטרנט הרשמי שלהם.

**Comment by noamoss** [comment]
@akariv בדקתי באתר החי, עדיין נפתח אוטומטית מייל ל-info@hasadna.org.il.

**Comment by akariv** [comment]
closing as added this text in actionables.

**Comment by noamoss** [comment]
checked on live and approved.
