### ISSUE TITLE
wrong tooltip

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#233]
בטבלת התמיכות בדף של סעיף תקציבי
https://next.obudget.org/i/budget/00204602/2019
![image](https://user-images.githubusercontent.com/8996235/44957980-f1a81800-aee1-11e8-9384-88e08ccdcc98.png)

**Comment by akariv** [comment]
@maryLoi  is the problem the typo with the 'ד'?

**Comment by maryLoi** [comment]
חיפוש התקנה 00.00.00.00 במפתח התקציב

**Comment by yotam707** [comment]
I'm working on it now

**Comment by nadavs123** [comment]
We went for:
"חיפוש מידע נוסף על 00.00.00.00"
