### ISSUE TITLE
חסד משימתי

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#235]
בחיפוש "חסד משימתי" התקנה מופיעה פעמיים

![image](https://user-images.githubusercontent.com/8996235/44978925-7f344800-af74-11e8-83fe-01c5698ab0b0.png)

**Comment by maryLoi** [comment]
probably a duplicate

**Comment by akariv** [comment]
This is caused by a bad item connection decision (two items should have been connected)

**Comment by akariv** [comment]
מבדיקה עולה כי התקציב של התקנה התאפס בשנת 2017, מה שגורם ליצירת ניתוק בין התקנה של 2016 לזו של 2019.
זה מקרה יחסית נדיר ולא נתקן.
