### ISSUE TITLE
טולטיפ לא קריא

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#247]
עדיף במקום הקו המקווקו אייקון של סימן שאלה או משהו

![image](https://user-images.githubusercontent.com/8996235/45096881-3aeaa880-b12a-11e8-868e-5b0d71104c30.png)

פה זה מבלבל כי נראה לחיץ

![image](https://user-images.githubusercontent.com/8996235/45096915-4a69f180-b12a-11e8-912d-5e8203d2f0dd.png)

**Comment by noamoss** [comment]
@maryLoi 

>עדיף במקום הקו המקווקו אייקון של סימן שאלה או משהו

מעביר למחלקת ה-ux והעיצוב של הפרוייקט.

@mushon ^^^?

**Comment by mushon** [comment]
טופל - בום!!!
https://zpl.io/bzN50DA
(עברנו ל-3 שורות)
![image](https://user-images.githubusercontent.com/27123/55275659-4423a880-52fa-11e9-9fc7-5d1726e279db.png)
