### ISSUE TITLE
fix broken email alerts design

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#251]
![image](https://user-images.githubusercontent.com/3581741/45846220-e81b0e80-bd2f-11e8-8900-91bcd0a9a646.png)

**Comment by akariv** [comment]
already fixed, look at the latest email.

**Comment by noamoss** [comment]
@akariv this is taken from last mail I got:

![image](https://user-images.githubusercontent.com/3581741/45848188-37643d80-bd36-11e8-8b94-3fd6b3c47145.png)


about half of the width is white/blank/ unused.

**Comment by akariv** [comment]
This was on purpose to fit the mobile layout.

**Comment by noamoss** [comment]
let's leave this issue open for future improvement. The idea should be finding a way to serve weekly emails to mobile without hurting their shape/visuality for desktop users.

Out of our current scope.

**Comment by noamoss** [comment]
@akariv BTW, this is how the new structure looks on my mobile, still does not include the full display. 

![image](https://user-images.githubusercontent.com/3581741/45877433-7500af00-bda6-11e8-92ca-eb52685810d7.png)

**Comment by akariv** [comment]
hmm. ok.
