### ISSUE TITLE
social map mobile QA: fix homepage expandable tabs (activity fields +  governmental transfers)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#256]
![image](https://user-images.githubusercontent.com/3581741/45874937-e2a8dd00-bd9e-11e8-81af-7120197a1d1b.png)

This issue is relevant to the top 2 expandable tabs in the homepage:

1. items should be clickable, just like in the desktop version.

2.button background color should be identical to the item font color.

**Comment by akariv** [comment]
1a. It's not clickable just as in the desktop versions - as we don't have pages for government offices...

1b. ack

**Comment by noamoss** [comment]
checked and approved on `live`
