### ISSUE TITLE
socialmap: fix homepage governmental transfers items list 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#257]
https://whatismybrowser.com/w/6WBQ736:

![image](https://user-images.githubusercontent.com/3581741/45875231-bb9edb00-bd9f-11e8-992a-54063e5a6c72.png)

**Comment by akariv** [comment]
I just tried the same configuration and it looks fine.
Can you check if you're zoomed in on the browser?

**Comment by noamoss** [comment]
@akariv checked and reproduced:

![image](https://user-images.githubusercontent.com/3581741/45877493-b1340f80-bda6-11e8-9cd9-a02696f7125a.png)

**Comment by akariv** [comment]
It looks like you're zoomed in. Did you check that?

**Comment by noamoss** [comment]
@akariv yes, I checked that, verified by zooming in and out, and again by clicking ctrl+0.
You could say it might be some default behaviour of my OS - so maybe this is a rare bug - let's leave it open and see if we can reproduce it on other devices. I am assigning myself for the meanwhile.

**Comment by akariv** [comment]
The reason I ask is there's a zoom icon in your address bar - it doesn't
show on zoom 100%.
Can you share a screenshot of how it looks on your machine without any zoom?

**Comment by noamoss** [comment]
@akariv I guess you were right, now I can not reproduce. Sorry.

Closing issue.

**Comment by noamoss** [comment]
@akariv sorry, we need to reopen as I found this bug on another device, no zoom at all:

https://whatismybrowser.com/w/482Y8PZ:


![image](https://user-images.githubusercontent.com/3581741/46072069-16627900-c18a-11e8-98d5-eb6591a35b24.png)

**Comment by akariv** [comment]
latest code wasn't updated on server, now it is.
