### ISSUE TITLE
social map homepage fix "search organizations in other fields" link

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#258]
![image](https://user-images.githubusercontent.com/3581741/45875333-09b3de80-bda0-11e8-9cdd-0279f99930b6.png)

clicking the button leads to a meaningless search results page. Instead, it should lead to the empty "activity fields" search result page (https://next.obudget.org/s/?q=&dd=field-of-activity-reports&range=last_decade&theme=socialmap&lang=he):

![image](https://user-images.githubusercontent.com/3581741/45875509-8e066180-bda0-11e8-98d0-1d4bae4dbde4.png)

**Comment by noamoss** [comment]
@akariv 


I know it has been waiting, and I remember we spoke about. The current function just does not make sense as once I click the button that's what I see:

![image](https://user-images.githubusercontent.com/3581741/45877574-fd7f4f80-bda6-11e8-8f8f-860150b14322.png)

It is more confusing than showing an empty search field + list of all activity fields to choose between.

**Comment by akariv** [comment]
ah, ok - the link is indeed wrong.

It shoudl point to this -
https://next.obudget.org/s/?q=%D7%90%D7%A8%D7%92%D7%95%D7%A0%D7%99%D7%9D%20%D7%94%D7%A4%D7%A2%D7%99%D7%9C%D7%99%D7%9D%20%D7%91%D7%AA%D7%97%D7%95%D7%9D&dd=field-of-activity-reports&range=last_decade&theme=socialmap&lang=he

does this make more sense?

**Comment by noamoss** [comment]
@akariv yep, much better.

**Comment by noamoss** [comment]
@akariv fixed only for the desktop display, not for mobile.

**Comment by akariv** [comment]
oops, you're right

**Comment by noamoss** [comment]
checked on live and approved.
