### ISSUE TITLE
social map mobile QA: homepage header should be responsive (relative to the device width)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#259]
consider this example (Xiaomi M2, http://mobt.me/ioOj):

![image](https://user-images.githubusercontent.com/3581741/45875748-47fdcd80-bda1-11e8-83b6-3cebbeb346d0.png)

**Comment by akariv** [comment]
a. we're not supporting devices this old. Same as for browsers in general -
we only support the last couple of versions.
b. these device emulators are shit. best to get screenshot from real device
using
https://www.browserstack.com/list-of-browsers-and-platforms?product=screenshots
for
example

**Comment by noamoss** [comment]
>we're not supporting devices this old. Same as for browsers in general -
we only support the last couple of versions.

np, if you think it is about the browser/device version, you can close this issue. I suspect it has to do with the screen width (the following screenshot is taken on a desktop browser):

![image](https://user-images.githubusercontent.com/3581741/45877709-72528980-bda7-11e8-9436-143383df51b3.png)


>b. these device emulators are shit. best to get screenshot from real device

You would be surprised how many embarrassments I had a week ago on another project due to BrowserStack. It is nice (but slow) but for sure not reliable. That's why I using my device in parallel to the emulator checks - but I don't hold one of the popular devices.

**Comment by akariv** [comment]
Perhaps a better service then :)

I agree re the photo credits, I'll fix these.

**Comment by noamoss** [comment]
>Perhaps a better service then :)

tell me if you know one. Meanwhile I am trying to combine them all. 

>I agree re the photo credits, I'll fix these.

thnx.
