### ISSUE TITLE
תוצאות חיפוש: לא מוצגים סכומים אגרגטיביים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#26]
אם מחפשים "עיר ללא אלימות" בחלק מהתוצאות לא מוצגים סכומים, למרות שהסכומים קיימים בדף הפרוט

![image](https://user-images.githubusercontent.com/8996235/37467923-3833e8e8-286a-11e8-95ca-42e4fd156268.png)

**Comment by akariv** [comment]
עכשיו מוצג הסכום אחרי שינויים ולא התקציב המקורי (שיכול להיות בהרבה פעמים 0)
