### ISSUE TITLE
social map mobile QA: complete "more info" (data query place holder) + link to send by email

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#260]
current:

![image](https://user-images.githubusercontent.com/3581741/45876096-539dc400-bda2-11e8-93bb-b9182c5519c8.png)

expected: 

![image](https://user-images.githubusercontent.com/3581741/45876081-408af400-bda2-11e8-8f50-6f390e5e9375.png)

**Comment by akariv** [comment]
Waiting for this https://projects.invisionapp.com/d/main#/console/7587193/299758596/comments/104035334

**Comment by akariv** [comment]
+ spec for that email's subject and contents

**Comment by noamoss** [comment]
@akariv 

subject: קישור למידע מאתר "המפה החברתית"

content: 
שלום.

העמוד [שם העמוד] נשלח אליכם ממכשיר נייד.
[לחצו כאן] לצפייה בעמוד.

**Comment by akariv** [comment]
@noamoss
אטפל בזה כשהאסט יעלה לאינוויזן

**Comment by noamoss** [comment]
checked on live and approved.
