### ISSUE TITLE
social map mobile QA: force space between organizations list items (governmental transfers tab)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#262]
found on Galaxy 6s emulator (http://mobt.me/ioTd), Iphone emulator, and reproduced on a real device as well:

![image](https://user-images.githubusercontent.com/3581741/45876689-01f63900-bda4-11e8-8919-34bfd786a4f9.png)

notice there are 3 different problems displayed:

1. one item is covering the next item
2. some items begins with space which should be trimmed
3. the item name should be in the eight of the index number. On some items, the textual name is higher.

This screen shows exemplify two more problems: 
![image](https://user-images.githubusercontent.com/3581741/45877095-6cf43f80-bda5-11e8-861e-d62654d2db29.png)

when the index includes 3 digits (>99) and the organization name is long : 

4. there is no space between the index no. and the organization name, like in the design
5. the space between the organization name and the amount is not the standard space. ==> we should have a standard

**Comment by noamoss** [comment]
@akariv you ignored my 3rd point, but it looks ok now on live.

**Comment by akariv** [comment]
Didn't ignore - just implemented according to design: https://projects.invisionapp.com/d/main#/console/7587193/299758601/inspect

<img width="472" alt="screen shot 2018-09-24 at 9 27 00" src="https://user-images.githubusercontent.com/265333/45939547-060c9b80-bfdc-11e8-9e1b-b55997df870b.png">

**Comment by noamoss** [comment]
@akariv your'e right it is on the design, but my comment followed that - but anyhow, it's totally fine as is.
