### ISSUE TITLE
להציג הודעה "בטעינה" במקום "אין תוצאות" בזמן שנתוני הוצאות עולים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#266]
![image](https://user-images.githubusercontent.com/8996235/45922514-fdb14500-bea3-11e8-8f3c-318451afc7ce.png)

**Comment by aviklai** [comment]
Pull request ready:
https://github.com/OpenBudget/budgetkey-app-generic-item/pull/103
