### ISSUE TITLE
when hovering over link, cursor doesn't change 

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#267]
העכבר נמצא על "מיהו הארגון

<img width="525" alt="chrome_2018-09-22_20-32-26" src="https://user-images.githubusercontent.com/8996235/45922611-25ee7300-bea7-11e8-9ea8-d069d742cbcf.png">

**Comment by aviklai** [comment]
Pull request ready:
https://github.com/OpenBudget/budgetkey-app-generic-item/pull/103
