### ISSUE TITLE
תוצאות חיפוש לא אגרגטיביות

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#27]
1. שתי שורות שונות לאותה תקנה
2. התוכנית "קניות" היא רמה אחת מעל עיר ללא אלימות, אין צורך להציג אותה

![image](https://user-images.githubusercontent.com/8996235/37468357-80e09ed2-286b-11e8-8db4-2fac5e922605.png)

**Comment by akariv** [comment]
תוקן

**Comment by maryLoi** [comment]
עדין קורה

![image](https://user-images.githubusercontent.com/8996235/38043544-1d5acba8-32c0-11e8-91e3-4aca83715f12.png)
