### ISSUE TITLE
fix search query turns into Gibrish when subsribing to search query+ login

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#270]
When I mark a search query for subscription without being logged in after I log in the search query is transformed into "harpash":

![image](https://user-images.githubusercontent.com/3581741/47008950-f77d5400-d143-11e8-82f6-a953387cdd16.png)

(https://whatismybrowser.com/w/CD5MFC4)

**Comment by akariv** [comment]
you probably mean hrepsh, I think

**Comment by akariv** [comment]
@noamoss does this issue reproduce for you? I tried FF and Chrome but both seem to be working.
It's been a long time since you opened it and it seems that it was solved in the time since.

**Comment by noamoss** [comment]
can't reproduce
