### ISSUE TITLE
אחוזים לא תואמים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#273]
האחוז המוצג הוא לא מאותו שלם וזה מבלבל. צריך לציין במפורש מתוך מה.

![image](https://user-images.githubusercontent.com/8996235/47741030-f723a380-dc81-11e8-8e21-d42bad0b4fa6.png)

**Comment by maryLoi** [comment]
גם הסכומים לא תואמים. למשל: בריאות בתרשים מופיע 41 מיליארד. אם נכנסים לתוך הקטגוריה רואים 63 מיליארד

**Comment by yotam707** [comment]
אני יכול לתקן את זה. את יכולה בבקשה לכתוב לי כיצד את רוצה שהטקסט יראה בטולטיפ?
