### ISSUE TITLE
File download name should be more appropriate

### ISSUE THREAD

**Issue by chaimkut** [OpenBudget/BudgetKey#274]
When downloading an Excel file from the website, the name is always `budgetkey.xlsx`. Obviously if you download multiple files then the browser automatically changes it to `budgetkey (1).xlsx`, `budgetkey (2).xlsx`... This makes it difficult to sort through, find downloaded files. Perhaps file names should have some standardized fields based on context, i.e. reference number, page title, years covered, ... For instance, to download https://next.obudget.org/i/budget/00204201/2019 could result in a filename such as `20.42.01_משרד_החינוך_קדם_יסודי_פירוט_תמיכות_2008-2019.xlsx`
or something of that sort...

**Comment by akariv** [comment]
Thanks, I agree.

**Comment by MaaikeB** [comment]
I would like to assign this issue to me, can I do so, or can someone else?

**Comment by MaaikeB** [comment]
@akariv I think this task was implemented, no? Can you close it?
