### ISSUE TITLE
design main search page results display

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#277]
- add filters by content type
- add total + per type query results

**Comment by mushon** [comment]
[Design here](https://projects.invisionapp.com/d/main#/console/7587193/253951995/comments)
![image](https://user-images.githubusercontent.com/27123/48025628-a8c44800-e14c-11e8-8d7f-8b27e20d8834.png)

Next step: the "All" tab should show an aggregate for every category.

**Comment by mushon** [comment]
https://invis.io/EFP736QXDSG

**Comment by noamoss** [comment]
@mushon ok, thanks, we will move with this design. Could you please add a mobile version?


@akariv any questions/specifications are needed here on your side?

**Comment by akariv** [comment]
Looks good. waiting to see how the aggregated view would work with this.

**Comment by akariv** [comment]
As in

> Next step: the "All" tab should show an aggregate for every category.

**Comment by noamoss** [comment]
@mushon following @akariv 's comment, I think we might consider enlarging the "הכל" and turn it into a static label - and set the first category filter autoselected. In other words: giving up the "All" view. I see no point duplicating the data from the filter into a new view.

**Comment by akariv** [comment]
המטרה של התצוגה הסיכומית היא לתת סקירה על סוגי המידע שיש, הסבר על מה זה כל דבר כדי להדריך את המשתמש.
הפילטרים הוא סוג של תצוגה סיכומית, אבל לא טובה במיוחד למי שלא מבין כלום.
אפשר להציג אותם כשמציגים תוצאות חיפוש ספציפיות (בשביל לעבור לסוג אחר) אבל במוד הסיכומי אני חושב שצריך משהו אחר במקום.

**Comment by noamoss** [comment]
בנתי.
לא זוכר שדיברנו על כל זה אבל זה רעיון טוב בעיני.

@mushon אם תרצה, אפשר לתת לך לסיים את תצוגת המובייל של הפילטרים ולעבוד עם דימה על התצוגה האגרגטיבית, או להיפך. מה דעתך?
