### ISSUE TITLE
ElasticSearch - Sort on Other than Relevance

### ISSUE THREAD

**Issue by MaaikeB** [OpenBudget/BudgetKey#288]
Right now the API only does sorting according to the scoring (which is according to relevance of the text search).

We want to be able to do sorting by more parameters:
- Other fields like last_modified and popularity (not yet existing)
Hereby we should also use a certain scoring threshold, since we want results that are relevant. 

Testing:
Use Kibana to test the Query

**Comment by MaaikeB** [comment]
TODOs
- [ ] Should there be validation of the sort object?

tested
```
{
    "query" : {
        "bool" : {
            "must" :[
                { "match": { "__is_new": "false"}}
            ]
        }
    },
    "sort": { "__last_modified_at": { "order": "desc" }},
}
```

**Comment by akariv** [comment]
Fixed via https://github.com/OpenBudget/apies/pull/1
