### ISSUE TITLE
search results "all" tab fixed items height

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#294]
1) all subsection cards should have the same height

2) subsections height should be fixed, otherwise, we hint one is more important than another

![image](https://user-images.githubusercontent.com/3581741/50557746-bdf2c880-0cf0-11e9-8749-56c0da189856.png)

**Comment by akariv** [comment]
This is a issue for the card design - atm the design dictates different heights, so some cards will be shorter than the others.

**Comment by akariv** [comment]
+ some card types are taller than the others.

**Comment by noamoss** [comment]
@akariv I want to reconsider it. @mushon ^^^^

**Comment by mushon** [comment]
The card types are no longer of different heights.
At this time claiming something like that would be nothing short of blasphemy!
@akariv Please review and TAKE IT BACK!!!
https://zpl.io/V0q4gwK
