### ISSUE TITLE
search results "all" tab one card scenario

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#295]
fix display when there is only one relevant result in a subsection: 

1. card should get the standard-common width.
2. horizontal scrolling should be off

![image](https://user-images.githubusercontent.com/3581741/50557785-2f327b80-0cf1-11e9-9e82-6e67ee696d6e.png)

**Comment by akariv** [comment]
This card type is not designed, so it doesn't have a mobile view (or any view as a matter of fact).
Once it's designed it will show here correctly.

**Comment by noamoss** [comment]
oh..

**Comment by noamoss** [comment]
will prioritize in today's tasks.

**Comment by mushon** [comment]
The type was designed and is ready in Zeplin:
https://zpl.io/bLPk9AQ
![image](https://user-images.githubusercontent.com/27123/55244762-dd977f80-5252-11e9-8d0a-5602c4bba413.png)
