### ISSUE TITLE
search results page, fix organization overlay text

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#296]
https://next.obudget.org/s/?q=%D7%A4%D7%99%D7%A8%D7%95%D7%AA&dd=entities&range=all&lang=he&entity_kind=all&public_funds=all

![image](https://user-images.githubusercontent.com/3581741/50558336-ee893100-0cf5-11e9-99c6-df3469dbc4d4.png)

**Comment by akariv** [comment]
Firefox, Safari & Chrome:
![screen shot 2018-12-31 at 12 36 16](https://user-images.githubusercontent.com/265333/50558648-bfc08a00-0cf8-11e9-8a5d-b1e2d39f69c2.png)
![screen shot 2018-12-31 at 12 36 08](https://user-images.githubusercontent.com/265333/50558649-bfc08a00-0cf8-11e9-8311-69a4c7cfe7c7.png)
![screen shot 2018-12-31 at 12 35 41](https://user-images.githubusercontent.com/265333/50558650-c0592080-0cf8-11e9-9a75-f43e8022a54d.png)

**Comment by akariv** [comment]
Please provide more info

**Comment by noamoss** [comment]
@akariv https://whatismybrowser.com/w/E9BB5W9

**Comment by akariv** [comment]
This doesn't reproduce - please see if it's some installed extension / loading error?

![screen shot 2018-12-31 at 12 44 22](https://user-images.githubusercontent.com/265333/50558841-fba81f00-0cf9-11e9-9a69-16f2f990a325.png)

**Comment by noamoss** [comment]
@akariv you were right, closing issue.
