### ISSUE TITLE
search results "all" tab imrpove subsection intro card design

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#297]
![image](https://user-images.githubusercontent.com/3581741/50558480-73c11580-0cf7-11e9-935a-14a854b1aa30.png)

intro card should get similar style to the other siblings

**Comment by akariv** [comment]
That's according to the design.

**Comment by akariv** [comment]
![screen shot 2018-12-31 at 12 42 27](https://user-images.githubusercontent.com/265333/50558770-8c322f80-0cf9-11e9-95db-951650415cc4.png)

**Comment by noamoss** [comment]
>That's according to the design.

If so it is a bad design decision IMO.

I see the screenshot you attached, buy can't see on `live`.

**Comment by akariv** [comment]
Still not sure why you've assigned it to me...

**Comment by noamoss** [comment]
@akariv asking you to change the height setting of the card.

**Comment by akariv** [comment]
Ah, so it's just the height... you should have said so.

**Comment by noamoss** [comment]
search results intro cards are empty on Govbuy theme:



![image](https://user-images.githubusercontent.com/3581741/50680555-cd378600-1010-11e9-93d8-04a0b6d1bfb3.png)

https://next.obudget.org/s/?q=%D7%A2%D7%99%D7%A6%D7%95%D7%91&dd=all&range=all&theme=govbuy&lang=he

**Comment by akariv** [comment]
Yes, we need texts for all of these.
Same for socialmap.

**Comment by noamoss** [comment]
@akariv 

>Yes, we need texts for all of these.

will post here soon.

>Same for socialmap.

social map search results page does not include cards (yet?)

**Comment by noamoss** [comment]
@akariv 

I just noticed some of these are already available at the current open-budget search results cards, so let's try to unify into a single version. I leave you to decide whether the intro cards text should reflect the tooltips texts (I think it is a good idea, but not sure how complicated is it).

Anyhow, here are my suggestions, if they are too long, please let me know what is the limitation?

התקשרויות:

התקשרויות הן העברות כספים מתועדות בין יחידה ממשלתית לגוף אחר. המידע עליהן נאסף מדו"חות רבעוניים של יחידות הממשלה שעומדות בחובה לפרסמם.

ספקים:

ספקים ממשלתיים או גופים או אנשים המעניקים שירות או מוצר ליחידה ממשלתית תמורת תשלום. 

מכרזים:
מכרז ממשלתי הוא הליך לבחירת ספק או ספקים לצורך רכישה או אספקת שירותים ליחידות הממשלה. סוג המכרז משתנה בהתאם לסוג השירות או המוצר, היקף העסקה, משך ההתקשרות ופרמטרים נוספים.

מכרזים משרדיים:
מכרז משרדי הוא מכרז שמפורסם מטעמו של משרד ממשלתי יחיד או משרדים בודדים.

מכרזים מרכזיים:
מכרז הנערך על ידי החשב הכללי במשרד האוצר עבור משרדי הממשלה השונים.

פטור ממכרז:
פטור ממכרז הוא הליך לבדיקת בקשה של יחידה ממשלתית להתקשרות עם ספק מבלי לקיים מכרז. ישנם כ-30 מקרים בהם גופים ממשלתיים פטורים מעריכת מכרז לפי החוק.


עמותה:
עמותה היא סוג של תאגיד המורכב מקבוצה של בני-אדם או תאגידים אחרים אשר חברו יחד למען מטרה מסוימת (לרוב מטרה ציבורית), ונרשמו בפנקס העמותות על ידי רשם העמותות שבמשרד המשפטים שמפקח על פעילותן.(מקור: ויקיפדיה)
