### ISSUE TITLE
smart table is not responding on contract page

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#300]
![image](https://user-images.githubusercontent.com/3581741/50565705-2ca84400-0d3a-11e9-93d5-f8dfddd1957c.png)

https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%91%D7%A8%D7%99%D7%90%D7%95%D7%AA/4501561972/0024070311?li=3

**Comment by akariv** [comment]
See the relevant query, make sure that the query works also in cases where all we have is a supplier name without an entity_id (as is the case with the link above)
