### ISSUE TITLE
enable ctrl + click 

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#304]
ctrl + click to open link in new window

**Comment by maryLoi** [comment]
לא עובד: בדף תוצאות חיפוש, בלחיצה על שם תקנה
https://next.obudget.org/s/?q=%D7%9E%D7%A2%D7%A0%D7%A7%20%D7%90%D7%99%D7%96%D7%95%D7%9F&dd=budget&range=all&lang=he&kind=all&fiscal-year=all

![image](https://user-images.githubusercontent.com/8996235/51565001-70a1eb00-1e99-11e9-9dd2-2a78f1e4215b.png)

**Comment by SanSunB** [comment]
I'm working on this :)
