### ISSUE TITLE
fix undisplayed saved search details

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#306]
![image](https://user-images.githubusercontent.com/3581741/52077217-20addd00-2599-11e9-8cce-ab19016defbd.png)

Username: Dimkaaa@gmail.com

**Comment by noamoss** [comment]
@akariv since Dima was the one to report this bug, can you explain what did you do with this issue, so I can verify it works?

**Comment by akariv** [comment]
The period part in the subscription was irrelevant (as we don't take the period into account anyway when sending the emails).
I simply removed it from the display instead of fixing the associated bug (which only occurs with very early subscriptions).
