### ISSUE TITLE
קולות קוראים, אתר משרד העבודה והרווחה: משיכת מידע

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#308]
## A. scan for new items in the calls of proposals index page:
index page url: https://www.molsa.gov.il/Publications/Pages/PubAppealNewSearch.aspx

![image](https://user-images.githubusercontent.com/3581741/52937081-d1242b00-3366-11e9-8214-a7c5a9cc6cbe.png)

we can use the publish date sorting to detect new items.

from this page we should take the item title and the link from the "פרטים נוספים" column (see below).

notice: the search section includes a 'category' select field. It could be useful to decide when/which item is a real 'opportunity', but since I could not find a consistent method of categorization and therefore I guess we bettter ignore it for now. 

### B. add the following details to the new record: [example link](https://www.molsa.gov.il/Publications/Pages/PubAppealDetails.aspx?ListID=65E31E8E-AF67-4F88-8978-7ABF0970DA11&WebId=F6CEEC85-5B09-4F74-B8AF-75B91C21AE70&ItemID=38)
(* marks details that are available also in the index page table, in case it is easier to retrieve from tere)

![image](https://user-images.githubusercontent.com/3581741/52936935-6a067680-3366-11e9-98fa-e25850fcf454.png)

1. title *
2. publish date *
3. publisher (two parts) *
4. ordering client (aka גורם מזמין)
5. description 
6. publication audience *
7. threshold conditions 
8. deadline *
9. contact for details
10. required documents
11. partners
12. file download (name + url)

**Comment by noamoss** [comment]
@akariv is there a way I can check/verify this?

**Comment by akariv** [comment]
use a redash query on the calls_for_bids table

**Comment by noamoss** [comment]
:+1: 
looks good
