### ISSUE TITLE
קולות קוראים, אתר ג'וביז: משיכת מידע

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#309]
## A. indicate new published calls for proposals

1. https://jobiz.gov.il/public_messages?message_type%5B%5D=2135

2. https://jobiz.gov.il/public_messages?message_type%5B%5D=2137

![image](https://user-images.githubusercontent.com/3581741/52938821-50b3f900-336b-11e9-8067-aa4fab929cf6.png)

We can use the publish date to indicate new relevant items and the url for the item page. 
Also, notice the alert mechanism on the top in case we need another indication for change. 

## B. Add item's details to the new record:

![image](https://user-images.githubusercontent.com/3581741/52938920-91137700-336b-11e9-998d-14508e937604.png)

1. title
2. publisher
3. publish date
4. details

**Comment by akariv** [comment]
Specifically this example is irrelevant - are there any good examples for this?

**Comment by noamoss** [comment]
@akariv no, unfortunately currently there are only 2 online examples, both are irrelevant. 
I tried to create an alerts agent, to be notified when a new item is published, but they don't enable it for "קולות קוראים".

I think adding a simple validation (like ensuring 'משרד הרווחה' appears in the header) is good enough for now.

**Comment by akariv** [comment]
קולות קוראים מג׳וביז ומבחני תמיכה מג׳וביז

בטבלאות
- calls_for_bids 
- support_criteria

**Comment by noamoss** [comment]
@akariv 

1. Could not find [current jobiz publications](https://jobiz.gov.il/public_messages?message_type%5B%5D=2137) on `calls_for_bids`, please [see my query](https://app.redash.io/hasadna/queries/182151).
2. for 'support_criterias', you inserted the `publish date` under`start date` title. Isn't it risky for future usage?


![image](https://user-images.githubusercontent.com/3581741/54625336-be8d3680-4a77-11e9-8cc3-95d5e870b740.png)

![image](https://user-images.githubusercontent.com/3581741/54625280-a61d1c00-4a77-11e9-9a3b-0aece69cf0ce.png)

**Comment by akariv** [comment]
start_date is used for the publication date for tenders as well.

**Comment by noamoss** [comment]
@akariv :+1: and what about 

>Could not find current jobiz publications on calls_for_bids, please see my query.

**Comment by akariv** [comment]
fixed
