### ISSUE TITLE
קישור לסעיף תקציבי שבור

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#31]
הקישור למשרד החינוך מגיע לעמוד 
Not Found

http://next.obudget.org/i/budget/0020240595/2002?li=7
http://next.obudget.org/i/budget/0020/2002

![image](https://user-images.githubusercontent.com/8996235/37539796-69e9fe60-295d-11e8-9203-a25b236b3dd3.png)

**Comment by akariv** [comment]
תוקן.
