### ISSUE TITLE
office tenders + support criterias: מניעת כפילות ואיחוד מידע ממקורות שונים בעת יצירת פרט חדש

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#310]
this issue is to add logic when indicating a new call for proposals in one of the sources (i.e. #309 vs. #308 ) to ensure we are not recreating a record on our DB for an existing item. 

The best indication for a recurring item is equal values in the `publisher` and `title` fields. In this case, we should just add (without deleting) data on the existing item's record.

**Comment by noamoss** [comment]
@akariv need your opinion here. I am not sure if we should spend time on that, as long as we don't have real conflict examples. On the other hand, I assume we will have no way knowing of it in real time. What do you think?

**Comment by noamoss** [comment]
@akariv I found a potential conflict source (for tenders): https://www.health.gov.il/Services/Tenders/Pages/default.aspx#blank.

Please share your thoughts

**Comment by akariv** [comment]
Is there any tender there that doesn't exist on the main tenders website?

**Comment by noamoss** [comment]
@akariv Found two.

The first example (first item) is due to a manual mistake in the healt ministry site, so we can say it is irrelevant.
I think the second exmpale (see below) shows we should scan this source:

![image](https://user-images.githubusercontent.com/3581741/55033268-6d52e900-501b-11e9-8f9e-2c9e520bc332.png)

**Comment by akariv** [comment]
https://next.obudget.org/s/?q=%D7%9C%D7%90%D7%A1%D7%A4%D7%A7%D7%AA%20%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%20%D7%A0%D7%99%D7%A7%D7%99%D7%95%D7%9F%20%D7%A2%D7%91%D7%95%D7%A8%20%D7%9C%D7%A9%D7%9B%D7%95%D7%AA%20%D7%94%D7%91%D7%A8%D7%99%D7%90%D7%95%D7%AA&dd=procurement&range=all&lang=he&tender_type=all

**Comment by noamoss** [comment]
@akariv different publish date, different status.

**Comment by akariv** [comment]
Found it - a slightly different wording

https://www.mr.gov.il/officestenders/Pages/officetender.aspx?pID=629720

https://next.obudget.org/i/tenders/office/629720/4/2019?li=0

**Comment by noamoss** [comment]
@akariv so you think we should give up on this issue?

**Comment by akariv** [comment]
The real question is whether all data sources we have are either completely
unique or a replication of a more authoritative source (e.g. mr.gov.il).
So far this is the case, but if we find a source that has extra information
that is not included in that source - or a mixture of records - then this
issue will be relevant.

**Comment by noamoss** [comment]
right, but (correct me if I am wrong) we have no real quick/manual way to know that. This should be part of the task here. The fact we don't find any new/exclusive item, nor extra information, while scanning quickly the source now does not mean this is not happening for some of the past/future items. I think all these scraping tasks should be about mapping the source and defining for each data point whether it should be extracted or not.

**Comment by akariv** [comment]
Okay, this may be a good content task - pre scraping assessment.

**Comment by akariv** [comment]
@noamoss can we update the scraping tasks with what we agreed above and close this issue?

**Comment by akariv** [comment]
@noamoss can we update the scraping tasks with what we agreed above and close this issue?

**Comment by noamoss** [comment]
@akariv for now I defined scarping tasks for Health ministry only, and you can find the defined logic [here, #347](https://github.com/OpenBudget/BudgetKey/issues/347)
