### ISSUE TITLE
קול קורא, אתר ג'וביז, משיכת מידע 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#311]
## A. indicate new published calls for proposals
we can use the search result link: https://jobiz.gov.il/public_messages?search=&searchNotices=2137

![image](https://user-images.githubusercontent.com/3581741/52937573-2876cb00-3368-11e9-8e30-af938106905e.png)

We can use the publish date to indicate new relevant items and the url for the item page. 
Also, notice the alert mechanism on the top in case we need another indication for change. 

## B. Add item's detials to the new record:

![image](https://user-images.githubusercontent.com/3581741/52937872-eb5f0880-3368-11e9-8366-a920165e8c51.png)

1. title
2. publisher
3. publish date
4. details

**Comment by akariv** [comment]
This is Kol Kore, not Tmicha (let's use the 1st term for the call for applications and the 2nd for the actual money transfer to a specific recipient)

**Comment by noamoss** [comment]
@akariv you are right, my mistake (fixed title)

**Comment by akariv** [comment]
So this and #309 are duplicated?

**Comment by noamoss** [comment]
@ak

in a way  it is a duplication, so I just upated #309 to include both types of "הודעות" on jobiz:

1. https://jobiz.gov.il/public_messages?message_type%5B%5D=2135

2. https://jobiz.gov.il/public_messages?message_type%5B%5D=2137

And will close this issue
