### ISSUE TITLE
מבחני תמיכה, אתר משרד העבודה והרווחה, משיכת מידע

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#314]
## A. Scan the index page for new items:
url: https://www.molsa.gov.il/subsidizing/pages/supportshomepage.aspx

![image](https://user-images.githubusercontent.com/3581741/52943172-341cbe80-3375-11e9-96fe-f28978a2fe0b.png)

## B. In case of a new (and not a פג תוקף) item, validate it was not already saved via משרד המשפטים:
check we don't have another item by משרד הרווחה with the same title.

## C. save the following details:
1. status 
2. title
3. contact 
4. deadline 
5. attachments
6. comments (to be named more_info)
7. (not needed, I think)

**Comment by akariv** [comment]
Can you show examples of such duplicates (for B)

**Comment by noamoss** [comment]
@akariv I hope it is a valid example, eventhoguh the reported amounts are different between the two sources: 

1. Obudget: https://next.obudget.org/i/supports/0023103801/2016/%D7%99%D7%A9%D7%99%D7%91%D7%AA%20%D7%A9%D7%A2%D7%9C%D7%91%D7%99%D7%9D/%D7%903?li=8

2. ([from 2016 first half report](https://www.molsa.gov.il/Subsidizing/PublicInstitues/MolsaReceivedSupport/%d7%9e%d7%95%d7%a1%d7%93%d7%95%d7%aa%20%d7%a6%d7%99%d7%91%d7%95%d7%a8%20%d7%a9%d7%90%d7%95%d7%a9%d7%a8%d7%95%20%d7%9c%d7%aa%d7%9e%d7%99%d7%9b%d7%94%20%d7%9e%d7%97%d7%a6%d7%99%d7%aa%20%d7%a8%d7%90%d7%a9%d7%95%d7%a0%d7%94%202016.xlsx), it was not included in the 2016 annual file):
![image](https://user-images.githubusercontent.com/3581741/53495951-b01bb280-3aa9-11e9-9277-cb61ddda7b6f.png)

**Comment by akariv** [comment]
How is this file related to the subject of this issue?

If I understand correctly, this is about merging _support criteria
documents_ between welfare and justice ministries.
What you pasted here is an actual support, not a criteria document.

**Comment by noamoss** [comment]
@akariv you are right. Deleted the previous example comment, adding a new one:

1.[ justice ministry website](https://www.justice.gov.il/Units/Tmihot/Pages/TestServies.aspx):

![image](https://user-images.githubusercontent.com/3581741/53502261-61284a00-3ab6-11e9-9031-c6f10e77e478.png)

2. [welfare ministry website](https://www.molsa.gov.il/subsidizing/pages/supportshomepage.aspx):
![image](https://user-images.githubusercontent.com/3581741/53502403-a5b3e580-3ab6-11e9-9be5-9206b6bf5e13.png)

**Comment by akariv** [comment]
I see some similarity in the title, but what would be the logic for
combining these two?

**Comment by noamoss** [comment]
@akariv you asked for an example for potential duplication - here we have an item that could potentially appear twice in both sources (I know that here one if from 2016 and the other is from 2018) - let's say they both were published in the same year in both sites, first in the justice ministry site and then in the welfare ministry website: from the welfare ministry website we could add the contact person, more documents and deadline (== status)

**Comment by akariv** [comment]
My question was about how we determine that two items from the two
different sources refer in fact to a single publication.

In your example there is no exact match in any of the fields, hence my
question about the matching logic.

**Comment by noamoss** [comment]
@akariv 

> ... how we determine that two items from the two different sources refer in fact to a single publication.

my suggestion is to keep it simple (used a similar method to recognize entities in wikipeida):
1. Titles'[Levenshtein ratio](https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html) >= 0.8
2. Same publisher

**Comment by akariv** [comment]
:+1:

**Comment by noamoss** [comment]
@akariv added the design template draft in #320

**Comment by noamoss** [comment]
@akariv you wrote me on Slack this issue is done, but I could not find the example from the example screenshots above (searched for `למטרת שיפוצים והצטיידות`) neither on redash. Please advice how can I verify it was applied correctly:


![image](https://user-images.githubusercontent.com/3581741/54832260-80388700-4cc4-11e9-876d-ae59eb89f6df.png)

**Comment by akariv** [comment]
These results are not searchable yet...

This is the query:
https://app.redash.io/hasadna/queries/183295/source
