### ISSUE TITLE
חיפוש מסונן "הזדמנויות"

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#315]
Create a filtered search configuration titles 'הזדמנויות' which are either 'open' (status) or with future deadline:

מכרז משרדי, מכרז מרכז, קולות קוראים (#309 #310 ), טיוטת קולות קוראים (#312), מבחני תמיכה (#314+תוכן קיים ממשרד המשפטים)

**Comment by akariv** [comment]
למה תמיכות ופטןרים?
תמיכות הם כלל לא הזדמנות
פטורים הם הזדמנות חלשה מאוד

**Comment by noamoss** [comment]
@akariv מקבל לגבי הפטורים (עדכנתי הגדרה).
למה תמיכות הן לא הזדמנויות לדעתך?

**Comment by akariv** [comment]
אלו העברות בפועל לארגונים. באיזה אופן הם הזדמנות?

(או שאתה מתכוון לפרסום מבחני תמיכה להתייחסויות הציבור?)

**Comment by noamoss** [comment]
@akariv this glitch happened for a couple of times:

![image](https://user-images.githubusercontent.com/3581741/55353034-0164fa80-54cb-11e9-8bc8-c7e81031154e.png)

**Comment by noamoss** [comment]
@akariv the filter was not applied as expected:

>which are either 'open' (status) or with future deadline:

![image](https://user-images.githubusercontent.com/3581741/55353608-6cfb9780-54cc-11e9-9e17-e9082d5ae261.png)

**Comment by akariv** [comment]
Filtered for future claim_date, as adding 'open' returns bad results atm.

**Comment by noamoss** [comment]
checked and approved on live.

@akariv I think we should apply a fallout scenario, for items that will not include 'due date' in the source - otherwise, our users might miss it.

**Comment by akariv** [comment]
- Added 'open' calls for bids and tenders as well
- Changed sort order to be by creation date (when showing all results, when searching order is by relevance)
