### ISSUE TITLE
Replace intricate company details scraper with data from data.gov

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#316]
Recently a new file was published to data.gov.il with all the company registrar's data:

https://data.gov.il/dataset/ica_companies/resource/f004176c-b85f-4542-8901-7b3176f9a054

We would like to replace our current, very complicated, company details scraper with data from this file.

The replacement should be in such a way that the current data format (headers, formats) is preserved.

If any data that is currently scraped does not exist in this new file, please indicate so in the issue.

**Comment by MaaikeB** [comment]
dataflows:
https://github.com/datahq/dataflows/blob/master/TUTORIAL.md

csv file at data.gov:

scraper file
https://github.com/OpenBudget/budgetkey-data-pipelines/blob/master/datapackage_pipelines_budgetkey/pipelines/entities/companies/registrar/scraper.py#L39

here is an example of how to transform the data
https://github.com/OpenBudget/budgetkey-data-pipelines/blob/4a88f4daa4ccb900bed3e3193d5c0aa50a103eae/datapackage_pipelines_budgetkey/pipelines/procurement/calls_for_bids/jobiz.py#L57

(read about data wrangling from the readme: https://github.com/OpenBudget/budgetkey-data-pipelines/blob/master/README.md)
