### ISSUE TITLE
נתוני תמיכות 

### ISSUE THREAD

**Issue by hoteralon** [OpenBudget/BudgetKey#317]
היי .. יש תקלה במשיכת נתוני תמיכות ? אני רואה שגם אתר התמיכות הממשלתי לא מתפקד

**Comment by akariv** [comment]
אתר התמיכות הממשלתי לא מאוד יציב ולעיתים הוא למטה.
אצלנו הנתונים עדכניים יחסית (אנחנו מעדכנים אותם פעם בחודש).

אדם
