### ISSUE TITLE
add subscription indication while typing in search query

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#318]
When user types in a search query - show hint 'הרשמה לעדכונים' until the star is pressed

![image](https://user-images.githubusercontent.com/3581741/53363482-4387a300-3945-11e9-857b-4d1087f06450.png)

**Comment by akariv** [comment]
Fixed, waiting for deployment

**Comment by noamoss** [comment]
please let me know when I can check

**Comment by noamoss** [comment]
@akariv you closed the issue, no change on my side:

![image](https://user-images.githubusercontent.com/3581741/55907466-83e26e00-5bdf-11e9-95b0-4d5dc582e8f5.png)

**Comment by akariv** [comment]
Subscription and login in general was turned off for social map.
I'll turn it on once the emails for opportunities are actually working (is
there an issue for that?)
In the meantime you can check on budgetkey.

**Comment by noamoss** [comment]
@azk 

>I'll turn it on once the emails for opportunities are actually working 

what do you mean? don't they work now (for welfare sources?) We need to show it as part of the הוכחת יכולת, so unless I miss something please turn it on.

>is there an issue for that?

not sure I understand - we said the opportunities will be added to the current email structure (the one you made for govbuy). Aren't we there yet? Anyhow, opened a new issue for that (#352)

---

QA results for the current issue (based on next.obudget):

1. The new indication should also appear in the homepage search field input, not only in the search results page.

2. when I click on the 'הירשמו לעדכונים'+star as anonymous, I expect the subscription to be completed after I log in. Currently, I see the text, I click, I am logging in, and then I need to notice nothing changed and re-click the star. The first click should cover me (assuming I was able to log in).

**Comment by azk** [comment]
@noamoss I guess you intended on mentioning @akariv

**Comment by noamoss** [comment]
@azk whoops. right, sorry.

@akariv ^^^

**Comment by noamoss** [comment]
checked on live, looks great.

**Comment by noamoss** [comment]
@akariv found one more place where the indication is missing, saved searches page (on social-map context):

![image](https://user-images.githubusercontent.com/3581741/56167613-4e73c100-5fe1-11e9-92ff-79aab28363c7.png)

**Comment by akariv** [comment]
Added now by default to all page headers.

**Comment by noamoss** [comment]
checked on live and approved.
