### ISSUE TITLE
מבחני תמיכה משרד הרווחה, page design

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#320]
![image](https://user-images.githubusercontent.com/3581741/53723037-7ebb3200-3e6f-11e9-90a9-b462fa92c98e.png)

-----

(based on the following example, from the [welfare minstry website](https://www.molsa.gov.il/subsidizing/pages/supportshomepage.aspx):)

![image](https://user-images.githubusercontent.com/3581741/53723075-95618900-3e6f-11e9-8ca1-c5e21e6d4702.png)

**Comment by akariv** [comment]
:+1:

**Comment by akariv** [comment]
@noamoss Should I use the design for the calls for bids instead of this?

**Comment by noamoss** [comment]
@akariv yes, I think we better do so.

**Comment by akariv** [comment]
״פג תוקף״  should go on the top right label.
"סופי" is part of the document type (and should go in the tag)
plz approve.

**Comment by noamoss** [comment]
@akariv 

>״פג תוקף״ should go on the top right label.
correct

>"סופי" is part of the document type (and should go in the tag)

I admit I did not think of it as a document type, but more like a status. But, for a matter of fact, you are right - there are only two 'types': 'draft' and 'final'. Since we are using the 'draft' in a separate content type, I think better just ignore the 'סופי' in the design -- as long as we are going to include 'טיוטה' in the item tag, as you offered.

**Comment by akariv** [comment]
https://next.obudget.org/i/support_criteria/support_criteria/261592596/None

**Comment by noamoss** [comment]
checked and approved.
