### ISSUE TITLE
Calls for Bids from ministry of Health

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#323]
https://www.health.gov.il/Subjects/Finance/Mtmicha/Pages/default.aspx

Scrape all links in the page. First phase, only collect those that point to a PDF file.

For each one, generate a record containing the following fields:
- publication_id
- page_title
- documents

also:
- tender_type = 'call_for_bids'
- tender_id = None

see this file for an example:
https://github.com/OpenBudget/budgetkey-data-pipelines/blob/master/datapackage_pipelines_budgetkey/pipelines/procurement/calls_for_bids/molsa.py

**Comment by akariv** [comment]
cc @kewankh

**Comment by ilyalyudevig** [comment]
@akariv hey Adam, I just wrote a pipeline for this issue 
if it still relevant, would be great to hear from you

**Comment by akariv** [comment]
Sure, still relevant - where can I see the code?
Is it on your branch?

**Comment by ilyalyudevig** [comment]
@akariv just put it on the branch
I should finish the publication id generation, need some time for that
sorry if i messed something up, I'm absolutely new in this :)

**Comment by akariv** [comment]
No worries - can you please put a link as I can't seem to find it?

**Comment by ilyalyudevig** [comment]
@akariv [https://drive.google.com/drive/folders/1QfXpP7sIA4PQJU3LfOvfmeNP97KjO3j9?usp=sharing](scraper and pipeline-spec)
