### ISSUE TITLE
Apply General Search Results ('all') Template on Social Map 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#324]
![image](https://user-images.githubusercontent.com/3581741/54881739-b3f9e500-4e5b-11e9-9b31-694de25c79fc.png)

The Social Map 'all' tab should include only relevant content types, of course, + "opportunities" (which are defined in a separate issue #315). Let's try placing the "opportunities" first.

**Comment by noamoss** [comment]
@akariv as a reminder, https://github.com/OpenBudget/BudgetKey/issues/315 is here for definitions

**Comment by noamoss** [comment]
@akariv looks good, but results categories order should be identical to the filter items order:

1. organizations 
2. fields of activity
3. geographical areas
4. opportunities

**Comment by noamoss** [comment]
(updated last comment with a new finding)

**Comment by noamoss** [comment]
checked on live and approved.

**Comment by noamoss** [comment]
@akariv found another bug, the tenders are not counted correctly:

![image](https://user-images.githubusercontent.com/3581741/55413380-e600fa80-5571-11e9-8b71-8ed756e704f2.png)

**Comment by akariv** [comment]
I can't reproduce this - can you please share a link?

**Comment by noamoss** [comment]
@akariv weird, now I can't either. Closing the issue, will open a follow-up if I see it again.
