### ISSUE TITLE
search results item redesign (content types recoloring)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#326]
We changed the color templates for items in the search results items types:

[Zeplin Link](https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c88c1915a12d91940238b03)

![image](https://user-images.githubusercontent.com/3581741/54881988-52874580-4e5e-11e9-968b-9c289257ab04.png)

Notice:
- The read deadline label to be handled on #325 
- This issue includes also items which are out of the scope of the social map theme, but we want to handle all of them at once.

**Comment by akariv** [comment]
Please add design for the call for bids and support criteria items as well.

**Comment by mushon** [comment]
https://zpl.io/V0q4gwK
![image](https://user-images.githubusercontent.com/27123/54945232-014e8300-4f3e-11e9-9a8a-c9471e28baf0.png)

**Comment by noamoss** [comment]
@akariv 

QA results: 
## General

* [ ] פג תוקף results should appear after open results. Currently I see many irrelevant results before the relevant/open ones. Sorting by publish date and/or by days count to the deadline might be useful.

 (this comment might be relevant and applied as part #324).

* [ ] when we don't know the publish date, don't show the label, or show (instead) the עודכן לאחרונה (label+value):

![image](https://user-images.githubusercontent.com/3581741/55345617-0620b300-54b9-11e9-9d3a-aa9946296c84.png)


* [ ] when querying 'תמיכה' the highlight color makes it impossible to read the label text. Please turn darker or even better, don't include the labels in the highlighting mechanism (feel free to open a follow-up if you prefer)


![image](https://user-images.githubusercontent.com/3581741/55344876-3a936f80-54b7-11e9-922c-795c64d6b6b1.png)


## מבחן תמיכה
Missing the relevant budget year (see demo above, and the following design):

![image](https://user-images.githubusercontent.com/3581741/55345065-af66a980-54b7-11e9-914d-5e272c4306fb.png)

## מבחן תמיכה: טיוטה
* [ ]  Missing the relevant budget year (see demo above, and the following design):

![image](https://user-images.githubusercontent.com/3581741/55345893-b68eb700-54b9-11e9-9c88-d28abfae4acb.png)

**Comment by noamoss** [comment]
checked and approved on live.
