### ISSUE TITLE
support_criteria + call_for_bids: time labels fix

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#328]
https://next.obudget.org/i/calls_for_bids/call_for_bids/381581212/None:

![image](https://user-images.githubusercontent.com/3581741/54882189-2967b480-4e60-11e9-8d4c-4bbed8db5277.png)

We can tell there was a change in the item (it was updated since it was published) but we have no chronological timeline (like in the tender item). Is this just a reflection of the raw data, or do we log a change on our side?

**Comment by akariv** [comment]
We don't have an update date for these items, so we use the time of latest change in our database.

**Comment by noamoss** [comment]
@akariv I this case I think we should:

a. change the 'פורסם לראשונה' label into 'תאריך פרסום'
b. omit the 'עדכון אחרון' label+value

for this content type.

**Comment by noamoss** [comment]
@akariv updated issue's title to apply for the support_criterias template as well.

**Comment by noamoss** [comment]
@akariv I just noticed we are missing an important detail in the current page design (which is included in the search results): the relevant budget year of the item.

Let's ask @mushon to advice of the current location and shape, before implementing this issue.

@mushon We don't have updates date here, just publication date any relevant budget year.
Here are the relevant locations I could think of to add the relevant budget year, but you might have better ideas:
![image](https://user-images.githubusercontent.com/3581741/55029076-dafa1780-5011-11e9-9c1c-858204124e63.png)


 Please add the Zeplin link once ready for @akariv.

**Comment by mushon** [comment]
Done. BOOM!!!
https://zpl.io/a3ekN3l

**Comment by akariv** [comment]
Updated the date location and text. 

As for the budget year - we usually don't have this info, and generally it's not interesting as it's an 'implementation detail' of the government. If I'm applying to a support in November, I don't really care if the funds for it were allocated from this or the next budget year, as the payment time is not necessarily related to the budget year (we've seen supports being paid years after they were approved).
The only thing interesting is whether it's open or closed (and what's the deadline).
