### ISSUE TITLE
חיפוש עמותת אקים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#33]
![image](https://user-images.githubusercontent.com/8996235/37599980-bc9c2696-2b8e-11e8-802b-e1717ca4e95b.png)

**Comment by akariv** [comment]
החיפוש מסונן לתמיכות, אז לא תמצאי את ״אקים״ שם אלא בארגונים.
![Screen Shot 2018-03-20 at 13.39.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537482f6ebef97b1f959d236/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f36b7191a379ec0c2858415b49be5d4a1f06a3a3dc78e2a436628f540de4d96b5d7c943b19aebdd01eb701ba21dd4d8dbee99850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca59f34fe74d5ca6103f62f43b.png)

**Comment by maryLoi** [comment]
הכוונה הייתה שמילים כמו "הקמת" ו"מקימות" לא אמורות להתקבל בתוצאות חיפוש של אקים

**Comment by akariv** [comment]
מדוע לא?
התוצאות הן עבוד מילים דומות (״אקים״ ו״הקמה״ הן מאותו השורש).
אם אין התאמה מדויקת (וזה המצב), יוצגו תוצאות עם התאמה פחות טובה.

אדם
