### ISSUE TITLE
call_for_bids + support criterias: fix visual glitches

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#330]
https://next.obudget.org/i/calls_for_bids/call_for_bids/219790611/None

![image](https://user-images.githubusercontent.com/3581741/54882410-692f9b80-4e62-11e9-879e-88b71fc6cc4e.png)

1. no status label is shown (when I think it should be marked as open, isn't it?)

2. I think that in case of a returning structure of dot+number+dot (`\.\s+\d\.`) with no link break we should force it.

3. If there are no action items, no reason to show the blank border. Just to clarify the expected behaviour in the no-action scenario:

![image](https://user-images.githubusercontent.com/3581741/54932416-73659e80-4f23-11e9-9a20-09938a627162.png)

**Comment by noamoss** [comment]
@akariv this issue is relevant for support criteria content type as well. Updated the issue's title.

**Comment by akariv** [comment]
Fixed

**Comment by noamoss** [comment]
@akariv only point 3 was implemented:



> If there are no action items, no reason to show the blank border. Just to clarify the expected behaviour in the no-action scenario:


the two other parts [are still there](https://next.obudget.org/i/calls_for_bids/call_for_bids/219790611/None):


> 1. no status label is shown (when I think it should be marked as open, isn't it?)

> 2. ... in case of a returning structure of dot+number+dot (\.\s+\d\.) with no link break we should force it.

**Comment by akariv** [comment]
the URLs have changed, please use Kibana to fetch the updated ones:

https://next.obudget.org/i/support_criteria/support_criteria/261592596/None
https://next.obudget.org/i/calls_for_bids/call_for_bids/209179902/None

**Comment by noamoss** [comment]
:+1: 
checked and approved.
