### ISSUE TITLE
call for bids + support criteria: url/email in description should be clickable (and open in a new tab)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#331]
https://next.obudget.org/i/calls_for_bids/call_for_bids/241327296/None:

![image](https://user-images.githubusercontent.com/3581741/54882439-bca1e980-4e62-11e9-82f5-0d301b27f37a.png)

same goes for email addresses (like [in this example](https://next.obudget.org/i/calls_for_bids/call_for_bids/219790611/None))

**Comment by noamoss** [comment]
@akariv issue is relevant for support criteria item page as well, updated title.

**Comment by akariv** [comment]
Can you share a link where this is broken?

**Comment by noamoss** [comment]
@akariv https://next.obudget.org/i/support_criteria/support_criteria/244341371/None

**Comment by akariv** [comment]
Sorry, commented on the wrong issue - this is still not fixed.

**Comment by akariv** [comment]
https://next.obudget.org/i/calls_for_bids/call_for_bids/209179902/None

**Comment by noamoss** [comment]
@akariv I think it is working great for call_for_bids, but not for support_criterias, yet.

**Comment by akariv** [comment]
Fixed

**Comment by akariv** [comment]
https://next.obudget.org/i/support_criteria/support_criteria/203985587/None

**Comment by noamoss** [comment]
checked and approved on live.

**Comment by noamoss** [comment]
@akariv the new link leads to a json, not to the item itself.
