### ISSUE TITLE
tenders/exemptions/call_for_bids design: fix labels location

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#333]
https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c61d64c67d72e99ebac33cb:

![image](https://user-images.githubusercontent.com/3581741/54882629-9ed58400-4e64-11e9-987c-39524a5f00a2.png)

1. (optional) updated/new
2. item status
3. type of item : (optional for tendes, exepmtion, contract --- not for call for bid).

**Comment by akariv** [comment]
https://next.obudget.org/i/tenders/office/621615/01/2018?li=0
https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%91%D7%99%D7%A0%D7%95%D7%99%20%D7%95%D7%94%D7%A9%D7%99%D7%9B%D7%95%D7%9F/4501313434/0070020301?li=0
https://next.obudget.org/i/calls_for_bids/call_for_bids/365473212/None
https://next.obudget.org/i/support_criteria/support_criteria/267044068/None

**Comment by noamoss** [comment]
looks good.
