### ISSUE TITLE
call for bids: add source url

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#334]
similar to the tender/contract style (notice to open in a new tab):

![image](https://user-images.githubusercontent.com/3581741/54930711-685d3f00-4f20-11e9-8137-08a63cadd9e3.png)

location:

![image](https://user-images.githubusercontent.com/3581741/54930599-3a77fa80-4f20-11e9-9f46-65a66720dded.png)

**Comment by akariv** [comment]
Fixed

**Comment by noamoss** [comment]
@akariv found a problem when checking [this item page source link](https://next.obudget.org/i/support_criteria/support_criteria/203985587/None) - it is being referred to a json.

**Comment by noamoss** [comment]
@akariv https://next.obudget.org/i/calls_for_bids/call_for_bids/209179902/None:
the new link leads user to json not to the content page.

**Comment by akariv** [comment]
Fixed, deploying in a few minutes

**Comment by noamoss** [comment]
@akariv no way to simulate clicking on the relevant item button? (not worth over 0.5h of work)

**Comment by noamoss** [comment]
checked and approved on next.obudget
