### ISSUE TITLE
support criteria item: add source url

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#335]
similar to the tender/contract style (notice to open in a new tab):

![image](https://user-images.githubusercontent.com/3581741/54930711-685d3f00-4f20-11e9-8137-08a63cadd9e3.png)

location:

![image](https://user-images.githubusercontent.com/3581741/54930935-d4d83e00-4f20-11e9-8e0d-88d89159e031.png)

**Comment by akariv** [comment]
Fixed

**Comment by noamoss** [comment]
@akariv the new link leads to a json, not to the content source url, see the following example:

https://next.obudget.org/i/support_criteria/support_criteria/203985587/None

**Comment by akariv** [comment]
Fixed, deploying in a few minutes

**Comment by noamoss** [comment]
checked and approved on live.

**Comment by noamoss** [comment]
@akariv same question here: we are linking to the jobiz search page, if we can simulate the relevant button click without spending over 0.5h, we should. Otherwise, can close this issue.

**Comment by akariv** [comment]
There's no such option - see what happens when you try to share an item
directly from jobiz and what url they give.
