### ISSUE TITLE
add tooltip for 'מבחן תמיכה'

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#336]
@akariv could you remind me where is the relevant spreadsheet and whether you need to do anything to apply the tooltip over the label?

![image](https://user-images.githubusercontent.com/3581741/54932855-3d74ea00-4f24-11e9-8a40-61ee8d17c774.png)

---

* tooltip text:

"
מבחני תמיכה הם הוראות עקרוניות הקובעות קריטריונים אשר על פיהם ניתן להעניק תמיכה מתקציב המדינה למוסדות ציבור. על פי הוראות אלו, לכל סוג של מוסדות ציבור, או תחום פעילות מובחן, נקבעת תקנה תקציבית ובה סכום התמיכה הכולל לאותו סוג של מוסדות. החוק מורה על כך שסכום תמיכה הכולל יחולק על פי מבחני תמיכה שוויוניים, אותם קובע השר הממונה על סעיף התקציב, בהתייעצות עם היועץ המשפטי לממשלה ובאישורו.
"

* source: אתר משרד הבריאות
* link: https://www.health.gov.il/Subjects/Finance/Mtmicha/Pages/default.aspx

**Comment by akariv** [comment]
Please update this spreadsheet and reassign to me when done

https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit#gid=0

**Comment by noamoss** [comment]
@akariv added the text, not sure how to handle the url and the source part.

**Comment by akariv** [comment]
As tooltips are not clickable in general and should be kept short, so I
wouldn't bother adding the source.

**Comment by noamoss** [comment]
@akariv agreed. I just added the sort (as plain text) to the tooltip. Feel free to close if nothing else to be done to deploy this minor textual change.

**Comment by noamoss** [comment]
checked and approved on live.
