### ISSUE TITLE
support criteria: unclear item

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#337]
https://next.obudget.org/i/support_criteria/support_criteria/152095178/None:

![image](https://user-images.githubusercontent.com/3581741/54933254-f6d3bf80-4f24-11e9-95d6-42e61759ad75.png)

@akariv do you have any clue what causes this display? Understanding the reason for the 'מבחן היסטורי' label and the missing tag + description might help me coming back with a better definition of how to handle it (if needed)

BTW: it is a health ministry item (not welfare) - how come we have it in the DB?

**Comment by akariv** [comment]
This is the source:

![Screen Shot 2019-03-26 at 13 31 31](https://user-images.githubusercontent.com/265333/54993858-8764db00-4fcb-11e9-8add-345ca7fecb74.png)

**Comment by noamoss** [comment]
so this is an example of #338. I would just add here the fact we know the source it אתר התמיכות, משרד המשפטים with a  link to the following URL (in a new tab, of course): https://www.google.com/search?hl=en&q=%D7%90%D7%AA%D7%A8%20%D7%94%D7%AA%D7%9E%D7%99%D7%9B%D7%95%D7%AA%20%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%9E%D7%A9%D7%A4%D7%98%D7%99%D7%9D

**Comment by noamoss** [comment]
checked on live and approved
