### ISSUE TITLE
support criteria item page when no description

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#338]
https://next.obudget.org/i/support_criteria/support_criteria/120328310/None:

![image](https://user-images.githubusercontent.com/3581741/54933600-a01ab580-4f25-11e9-8cd7-c6d57f5d7d2e.png)

1. label should be unified with other item: 'מבחן תמיכה' (instead of 'מבחני תמיכה')
2. no reason to show labels, as long as we don't have this data.
3. If we have no data, just a document, we sould replace the description with a common textual placeholder:
""
פרסום זה כולל במקור המידע את הקבצים המצורפים, ללא מידע נוסף.
""

4. (already mentioned in #335 , adding the source url)

**Comment by akariv** [comment]
Fixed (will be deployed soon)

**Comment by noamoss** [comment]
checked on live, looks good.
