### ISSUE TITLE
call for bids + support criterias: ignore space inside url/email address

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#339]
https://next.obudget.org/i/calls_for_bids/call_for_bids/241327296/None:

![image](https://user-images.githubusercontent.com/3581741/54934042-7d3cd100-4f26-11e9-9c7a-89089baf9145.png)

unfortunately, the raw data (links, email addresses) might include illegal values, which will lead us to publish links to nowhere. We should transform any URL/email address to ignore / throw away space characters.

for example:
`https://www.gov.il/he/departments/publications/Call_for_bids/ rfi-02-2019`
----> 
`https://www.gov.il/he/departments/publications/Call_for_bids/rfi-02-2019`

**Comment by noamoss** [comment]
@akariv got you. You're right. Let's leave as is for urls, and fix for emails only.

**Comment by akariv** [comment]
Can you please link to an example item that has this problem for emails?

**Comment by noamoss** [comment]
@akariv sorry, could find it. I will close the issue and will reopen if/when I find this error again.
