### ISSUE TITLE
Add temporary animated new feature strip to social map homepage

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#340]
Based on Takzivizm referral strip:
![image](https://user-images.githubusercontent.com/3581741/54958773-99a92f80-4f5f-11e9-9550-f98eed15472c.png)

Add a similar strip to the social map homepage, with the following customizations:

* Background color: ```rgb(113, 222, 207)```
* Text color: black/white (not sure, we will have to see and check)
* Label text: 
חדש! עמותה או חל"צ? חפשו ומצאו במרוכז מכרזים, מבחני תמיכה וקולות קוראים ממשלתיים הרלוונטיים לכם (בהרצה)
* Location: top center

**Comment by akariv** [comment]
Where should it link to?

**Comment by noamoss** [comment]
to a search results page filtered by הזדמנויות with no search query

**Comment by noamoss** [comment]
@akariv 

Looks good, but something is wrong with the fade-in effect: the strip appears when I load the page (expected bevahiour: it should move in after the page was loaded, just like it happens in next.obudget).

**Comment by akariv** [comment]
You're right, fixed.

**Comment by noamoss** [comment]
checked on live.

**Comment by noamoss** [comment]
@akariv I am reopening, as the strip does not fit on mobile/narrow screens:

![image](https://user-images.githubusercontent.com/3581741/56697739-334b3480-66f8-11e9-918f-39f5fbeea90c.png)


(feel free to break line or to lower the font size, whatever you feel is right)

**Comment by akariv** [comment]
Fixed.

**Comment by noamoss** [comment]
checked and approved.
