### ISSUE TITLE
improve tooltip text flow/ border shape

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#342]
https://next.obudget.org/i/support_criteria/support_criteria/120328310/None:

![image](https://user-images.githubusercontent.com/3581741/55028559-b3ef1600-5010-11e9-99cb-70b3be520697.png)

**Comment by akariv** [comment]
I would say that the text for this tooltip should be more concise.
Don't forget that tooltips need to look good in mobile view as well.

**Comment by noamoss** [comment]
@akariv agreed. I minimized the tooltip text. Please reassign to me when I can check.
