### ISSUE TITLE
scraper: education ministry support criteria page 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#343]
http://cms.education.gov.il/EducationCMS/Units/Hashavut/Tmichot/HodaotLtsibur

**Comment by noamoss** [comment]
@akariv could you take a look in this page? 
I am not sure if there is a point (or a way) to scrape it in an efficient way.

**Comment by akariv** [comment]
Looks like it's referring to a publication # in ילקוט פרסומים - perhaps
that's the location where we should be looking for these documents?

**Comment by noamoss** [comment]
@akariv sorry, not sure I understand

**Comment by akariv** [comment]
See the column with that title? ילקוט הפרסומים?

**Comment by noamoss** [comment]
@akariv I do, how/where should we look for it?

**Comment by akariv** [comment]
https://hackdash.org/projects/5c8e53a6256b2a1313910663 :)

**Comment by noamoss** [comment]
@akariv thanks. You are right, this is the relevant source.

I got the same result for 3 out of 3 queries:

![image](https://user-images.githubusercontent.com/3581741/55066550-b4c28f00-5086-11e9-8eb5-11bfcf1c0812.png)

but assuming ילקוט הפרסומים is going to be scrapped the task here should be extracting data from the Education Ministry office, and saving it after joining relevant data from ילקוט הפרסומים, assuming we don't have it on our DB already.

**Comment by akariv** [comment]
It's also possible that this is an exact duplicate of support criteria
documents as they're published in the ministry of justice website (iirc
something in the text suggested that).
If so, then we already got all that info.

**Comment by noamoss** [comment]
... so is this just an extra criteria you are offering?

**Comment by noamoss** [comment]
?

**Comment by noamoss** [comment]
@akariv can you clarify/answer my question
