### ISSUE TITLE
scrape health ministry tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#344]
https://www.health.gov.il/Services/Tenders/Pages/default.aspx#blank

fit the data to the existing `tenders` records on the DB.

![image](https://user-images.githubusercontent.com/3581741/55034248-b60ba180-501d-11e9-91c1-81047feefc7a.png)

**Comment by akariv** [comment]
Is there anything there that doesn't already exist in our data?

**Comment by noamoss** [comment]
@akariv see my answer at https://github.com/OpenBudget/BudgetKey/issues/310#issuecomment-476851907

**Comment by akariv** [comment]
The discussion in #310 was inconclusive (and not sure it included tenders at all)...

Anyhow, looking at this year's tenders is very difficult - 
this page is still loading 1 attempt in 20 (which makes its scraping extremely difficult):
<img width="955" alt="Screen Shot 2019-11-10 at 14 40 25" src="https://user-images.githubusercontent.com/265333/68544123-7df87980-03c8-11ea-9161-5bbaab778abe.png">

Looking in mr.gov.il and filtering by 'משרד הבריאות' we get 52 tenders just for 2019 - more than the 50 results in this page (for all years!).

I think we should not waste more time on this source @noamoss .

**Comment by noamoss** [comment]
@akariv agreed. I will add a comment to the sources table to clarify it.
