### ISSUE TITLE
scrape health ministry challange tenders (מכרז אתגר)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#345]
A. search the main page for new items:
https://www.health.gov.il/Services/Tenders/prob_tenders/Pages/activTenders.aspx:

B. for new items scrape and save in the relevant data points of `tender` on the current db:

![image](https://user-images.githubusercontent.com/3581741/55031849-37603580-5018-11e9-876c-5a1bc47c3105.png)
![image](https://user-images.githubusercontent.com/3581741/55032039-b5bcd780-5018-11e9-98d8-ffab5c2a8659.png)
![image](https://user-images.githubusercontent.com/3581741/55032068-c4a38a00-5018-11e9-857d-def951f83126.png)

1. title
2. status.
3. description
4. connected files
* source page

** notice: the page does not include publication date, and therefore we should add the date in which we first caught new items. The next time we scan the page we should verify if the item is still open, and if not, change it's status to 'closed'.

(remember the publisher is always משרד הבריאות)

**Comment by akariv** [comment]
Isn't all the information already in here:
https://next.obudget.org/i/tenders/office/618595/85-2018?li=2
?

Also, why does it say 'פתוח להגשה' when the last date for submitting was in
19/8/2018?

**Comment by noamoss** [comment]
@akariv 

>Isn't all the information already in here

The only currently open challenge tender, indeed, was retrieved from מנהל הרכש. It does not mean we know for sure all of them are shown and published there. I have no way to verify it. I assume you would prefer to put it on hold, but I think we can just not prioritize it and leave open as non-urgent (and as a starter task for a new developer). Up to you - but please add your thoughts so I can document and update it also elsewhere.

>Also, why does it say 'פתוח להגשה' when the last date for submitting was in 19/8/2018?

I believe the lower section of the page includes past related tenders. In this case, the single result is a closed tender. Anyhow, this is why I did not relate to this part of the page in the description.

**Comment by akariv** [comment]
From peeking at the attachments it looks like it's the same one from 2018
that was closed last August (and might have mistakenly left open here)

**Comment by akariv** [comment]
There isn't any open tender + it seems that we're getting the data from the main tender scraping (minhal harechesh).
I propose we close this one as done.

**Comment by noamoss** [comment]
@akariv makes sense.

**Comment by noamoss** [comment]
(approve checking and finding past/closed etgar tenders in the budget key search)
