### ISSUE TITLE
verify/scrape active and old support criterias and call for bids from the health ministry site

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#348]
https://www.health.gov.il/Subjects/Finance/Mtmicha/Pages/default.aspx

First priority are the support criteria for NGOS:

![image](https://user-images.githubusercontent.com/3581741/55035288-33d0ac80-5020-11e9-9068-3624831a93cd.png)

Other sections of the page would be a nice bonus.

**Comment by akariv** [comment]
Since it's a links only source (no actual info or dates), we said we'd scrape this and have the mechanism described in #408 to support it.
Makes sense to you @noamoss ?

**Comment by noamoss** [comment]
@akariv yes, sounds like it is the best we can offer here.

**Comment by akariv** [comment]
Example

https://next.obudget.org/i/support_criteria/support_criteria/516032133/0?li=11

**Comment by noamoss** [comment]
@akariv  I am reopening this issue for two reasons:

1. The source page is under construction, and therefore I can not perform QA.
2. You pointed to #408 and implemented the first option described there. I think we need to add an indication (constant place holder) explaining the situation to the user: "לא הצלחנו לאתר במקור המידע הממשלתי את התאריך בו נסגרת ההרשמה".

assuming the status will be changed automaticaly one month (~30 days) after the publication, this constant text is still relevant. Please approve this auto-status-change mechanism was implemented, so I can follow up and check it.

**Comment by akariv** [comment]
I didn't start working on #408 yet.

I'm reassigning this to you to QA once page is back online and #408 is ready.

**Comment by noamoss** [comment]
checked and approved. perfect.
