### ISSUE TITLE
fix search results design long texts

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#349]
(General for all search results cards, not only Hakol Kore):

When the descriptive text is longer than 2 lines, add '...':

![image](https://user-images.githubusercontent.com/3581741/55353373-cc0cdc80-54cb-11e9-88e7-7a2a563363d8.png)

**Comment by noamoss** [comment]
@akariv did not add '...' when the text is longer than 2 lines:

![image](https://user-images.githubusercontent.com/3581741/55907533-b7bd9380-5bdf-11e9-82b1-65acd487b444.png)

**Comment by akariv** [comment]
Yeah, that's not really possible

**Comment by noamoss** [comment]
@akariv ah? why not? any other way you can think of to show the sentence continues?

**Comment by noamoss** [comment]
@akariv still wondering why (i.e. what's the technical obstacle) for adding three dots, instead of the current blur effect.
