### ISSUE TITLE
hakol kore - static (hidden) landing page

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#350]
Create a static and robots-hidden landing page for הקול הקורה, based on the following design (taken from [here](https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c5f0339c6fba37e32235054))

![image](https://user-images.githubusercontent.com/3581741/55414561-05992280-5574-11e9-92d8-da9cd63e1f94.png)

1. header and text:
 הקול קורה: כל המידע על קולות קוראים לתמיכות ומכרזים ממשלתיים

עמותה או חל"צ? חפשו ומצאו במרוכז את ההזדמנויות הממשלתיות הרלוונטיות לכם - קולות קוראים לתמיכות, מבחני תמיכות ומכרזים פתוחים וקבלו עדכונים בזמן אמת על הזדמנויות חדשות.

2. omit the search filter - set search to only work on הזדמנויות
3. placeholder:

"הקלידו מילות חיפוש כמו תחום פעילות, נושא או מונח רלוונטי" 

4. link to the social map homepage (same tab)

5-7. logos + links:

A. מנהיגות אזרחית, [logo](https://user-images.githubusercontent.com/3581741/55681758-c03d7200-5932-11e9-8abe-2c0f7eac49a0.png), [link](http://migzar3.org.il/)
B. Public Knowledge Workshop.

C. an extra line of text to be added to thank the Joint for their support:
 בתמיכת "[מיזם ממשלה-חברה אזרחית](http://www.theinstitute.org.il/index.php?dir=site&page=programs&op=view&cs=131&langpage=heb)" – שותפות של ממשלת ישראל והמכון למנהיגות וממשל בג'וינט ישראל

Please notice to open the link in a new tab

**Comment by noamoss** [comment]
waiting for materials from Dana/Lior (מנהיגות אזרחית)

**Comment by noamoss** [comment]
added the missing text, ready to go.

**Comment by akariv** [comment]
Page is now live at 
https://socialmap.org.il/hakol-kore

**Comment by noamoss** [comment]
@akariv looks good, few things:

![image](https://user-images.githubusercontent.com/3581741/56697061-642a6a00-66f6-11e9-996d-5e5cd05caabf.png)


1. missing favicon + title should be: המפה החברתית - הקול קורה
(please apply for socialmap.org.il as well, as this has a SEO impact)

2. no point keeping the drop-down for one option, please hide/remove it.

3.please fix the text:
למידע נוסף על ארגוני החברה האזרחית ב"מפה החברתית" --> 
למידע נוסף על ארגוני החברה האזרחית בקרו ב"מפה החברתית".

4. The placeholder text changes: originally it appears in a longer version ('הזינו מילות חיפוש כמו תחום פעילות, נושא או מונח רלוונטי') as expected, but than it changes into 'בואו נחפש' (see screenshot). 

5. hasadna link is not working properly, I am getting `A connection was reset (corresponding to a TCP RST).
https://hasadna.org.il/`

6. please link the soical map logo to the social map homepage (socialmap.org.il), same tab.

Also, please see #361 for the mobile friendly question

**Comment by akariv** [comment]
1. There never was a socialmap favicon - restored it to the budgetkey
favicon for now.
2. I won't redesign a new searchbar component just for this page.
3. Fixed
4. This placeholder is a global override in mobile mode, to avoid the long
placeholders to overflow the length of the search bar.
    I'm guessing you tried to load the page in mobile?
5. Fixed
6. Fixed

**Comment by akariv** [comment]
Re (2) - I managed to find a hack to remove it without too much tinkering, deployed now.

**Comment by noamoss** [comment]
@akariv you did not relate to point 7 above. The rest looks great.


----

> 1. There never was a socialmap favicon - restored it to the budgetkey favicon for now. 

checked and approved.

> 2. I won't redesign a new searchbar component just for this page. 

I saw you found a great solution. thanks.

> 3. Fixed 

checked and approved.

> 4. This placeholder is a global override in mobile mode, to avoid the long placeholders to overflow the length of the search bar. I'm guessing you tried to load the page in mobile? 

propbably correct, as I played with the tab size. checked now and approved.

> 5. Fixed 

checked and approved.

> 6. Fixed

checked and approved.

**Comment by akariv** [comment]
Fixed #7

**Comment by noamoss** [comment]
looks good. We're done here.
