### ISSUE TITLE
add 'טיוטה' label to טיוטת מבחני תמיכה

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#359]
[Example Item](https://next.obudget.org/i/support_criteria/support_criteria/271355134/None?li=0&theme=socialmap). Currently it looks like open מבחן תמיכה - we should change פתוח status to 'טיוטה' or 'טיוטה להערות הציבור'.

![image](https://user-images.githubusercontent.com/3581741/56509969-1d3f4780-6531-11e9-8a83-f5bb28e5251d.png)

**Comment by akariv** [comment]
There's no indication in the item's metadata that this is indeed a draft.

Other than running some complex and inaccurate nlp algorithms on the text, do you have any suggestion as to how to detect this sort of items?

![Screen Shot 2019-04-24 at 14 47 14](https://user-images.githubusercontent.com/265333/56657213-20a51100-66a0-11e9-88e2-2f01fcf34aa6.png)

An example item which is detected as draft: https://next.obudget.org/i/support_criteria/support_criteria/479565327/None?li=0

**Comment by noamoss** [comment]
@akariv 

1. currently the page is broken:

![image](https://user-images.githubusercontent.com/3581741/56674049-0b40de80-66c2-11e9-9fe7-98a6b271f735.png)

Please let me know when ready for a recheck. 


2.
>There's no indication in the item's metadata that this is indeed a draft.

you're right. I don't see a point in building complex logic mechanisms for this source for now, and suggest to  leave as is for now. What do you think?

But please keep this comment/issue in mind when dealing with the [general law ministry source](https://www.justice.gov.il/Units/Tmihot/Pages/Pirsum.aspx) for טיוטת מבחני תמיכה.

**Comment by akariv** [comment]
Fixed now.

Also to note, that 'draft' is not a stage for documents but rather a different kind of document (stages are 'open', 'in effect' and 'outdated'). They are like RFis in the procurement world, which may result in a tender to be published in a later date but do not guarantee it.

**Comment by noamoss** [comment]
>Also to note, that 'draft' is not a stage for documents but rather a different kind of document (stages are 'open', 'in effect' and 'outdated').

I thought we discussed it and decided otherwise. I can correct my mistake in the email I sent to the content partners.
