### ISSUE TITLE
הצעה: להציג מטבע רק אם הרכש לא בשקלים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#36]
ב-'כלל ההתקשרויות עם הארגון' יש עמודת 'מטבע'. מאחר והרוב המוחלט בשקלים, זה סתם מעמיס

**Comment by akariv** [comment]
נראה לי שנשאיר, ולו רק בשביל להבחין בין המקרים שלא מצוין מטבע לבין אלו שמצוין שזה ב₪
