### ISSUE TITLE
Idea: different sorting on הזדמנויות search results page + category

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#360]
While using the הזדמנויות filtered search results page, I thought it would make sense to apply a different sorting logic for these results (comparing the overall results sorting mechanism, we are discussing in #356) - making the item(s) with a closer deadline appear before the laters.

If it to be applied, it should have the same logic both in the filtered result tab and in the 'all' tab.

**Comment by noamoss** [comment]
@akariv before checking our content partners opinion, I would be glad to hear what do you think of this idea, and how much time (more or less) it would take to apply.

**Comment by akariv** [comment]
These are already sorted by publication date (when showing 'all') and by relevance when searching for a specific term.

**Comment by noamoss** [comment]
@akariv right, and my idea is to omit the relevance factor and sort only by days left to the deadline. My assumption is that when looking for opportunities (and opportunities only) it is the most important factor for users.

A. what do you think of the idea?
B. how complicated (== hours) would it be to implement?

**Comment by akariv** [comment]
I disagree - why would anyone prefer an irrelevant result over a relevant one just because it has less days till its deadline?

**Comment by noamoss** [comment]
@akariv well, I think there is a different/unique 'job to be done' (to quote Mushon) behind this content type, comparing to the other kinds of search. It comes from a strange feeling I had when I looked at the results list of this category: we highlighted the days left for applications for a reason.

I might be wrong, of course, and therefore would like to check this thought with the partners, as long as it is doable (and not too expensive).

**Comment by noamoss** [comment]
... I think this issue is most relevant when you click the new promo strip in the homepage and move into a filtered search result page for הזדמנויות - since the user did not type in any term, I see no real point using the publishing date for sorting - it is good to know when it was published, but the key factor is how much time left for me to work/explore/decide for each item.

**Comment by noamoss** [comment]
^^^^

**Comment by noamoss** [comment]
closing in favor of https://github.com/OpenBudget/BudgetKey/issues/356#issuecomment-576445302
