### ISSUE TITLE
hakol-kore landing page to mobile

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#361]
the new (hidden) landing page is not working properly on mobile devices, as we had no pre-made design and since we are not sure if this is a priority at all. Before discussing it with our partners and to be able to consider it, I would like to know how much time it should take. Just to clarify, we are not talking about fancy behaviors, just to imitate the social map general homepage breakdown on narrow screens (see below):

![image](https://user-images.githubusercontent.com/3581741/56697484-64773500-66f7-11e9-9ab0-1c81f0eaac6f.png)

![image](https://user-images.githubusercontent.com/3581741/56697587-bc15a080-66f7-11e9-91fd-0ed16760c666.png)

**Comment by noamoss** [comment]
@akariv could you try and estimate the task, and reassign to me?

**Comment by akariv** [comment]
~ 0.5hours to implement.

**Comment by noamoss** [comment]
@akariv so, let's implement please - no reason to wait for their input.

**Comment by akariv** [comment]
done

**Comment by noamoss** [comment]
thanks! 
checked and approved.
