### ISSUE TITLE
מילת חיפוש לא ממורקרת בתוצאות

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#364]
https://next.obudget.org/s/?q=%D7%A0%D7%95%D7%A2%D7%A8&dd=supports&range=all&lang=he&kind=calls_for_bids

![image](https://user-images.githubusercontent.com/8996235/57198692-60aca380-6f7e-11e9-8024-6d21f2f009a1.png)

**Comment by maryLoi** [comment]
למה שאר התוצאות עלו בתוצאות החיפוש?

**Comment by akariv** [comment]
נראה שעכשיו זה בסדר, לא?

קישור מעודכן:

https://next.obudget.org/s/?q=%D7%A0%D7%95%D7%A2%D7%A8&dd=procurement&range=all&lang=he&tender_type=calls_for_bids&status=all
