### ISSUE TITLE
קישורים בתחתית מפתח התקציב לא לחיצים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#368]
אי אפשר להקליק על הקישורים

![image](https://user-images.githubusercontent.com/8996235/57791162-df56cd00-7744-11e9-8e8a-ea3b9808c4aa.png)

**Comment by akariv** [comment]
תצטרכי להראות לי, לא מצליח לשחזר.

**Comment by maryLoi** [comment]
resolved
