### ISSUE TITLE
סריקת כל המועמדים לכנסת בבחירות 2019

### ISSUE THREAD

**Issue by akariv** [OpenBudget/BudgetKey#369]
מכאן

https://bechirot21.bechirot.gov.il/election/Candidates/Pages/default.aspx

**Comment by BitanTomer** [comment]
I will work on this

**Comment by BarVolunteering** [comment]
זה קשור ל:
hasadna/knesset-data-pipelines
או ל
OpenBudget/budgetkey-data-pipelines
?

**Comment by akariv** [comment]
השני

**Comment by BarVolunteering** [comment]
התחלתי לעבוד על זה

**Comment by BarVolunteering** [comment]
הושלם ב
https://github.com/OpenBudget/budgetkey-data-pipelines/pull/195
https://github.com/OpenBudget/budgetkey-data-pipelines/pull/193

@akariv בבקשה תסגור
