### ISSUE TITLE
Social Map: stats

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#370]
מספר ישובים לא הגיוני
(הדף הראשי)

![image](https://user-images.githubusercontent.com/8996235/58385392-67b45800-7ff8-11e9-9acd-d5b2a5aaa9ae.png)

**Comment by akariv** [comment]
מה לא הגיוני?

**Comment by maryLoi** [comment]
טעות שלי, חשבתי שיש רק 255 ישובים, אבל זה עיריות

**Comment by akariv** [comment]
*רשויות מקומיות
