### ISSUE TITLE
לא מופיע "מקבל כספי ממשלה

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#373]
בדף של עמותת אנוש לא מופיע הטאב "מקבל כספי ממשלה
https://next.obudget.org/i/org/association/580019800?li=0

![image](https://user-images.githubusercontent.com/8996235/58901070-16e3e400-8709-11e9-8566-51ff5ebf8200.png)

**Comment by akariv** [comment]
כי הם לא מקבלים

**Comment by akariv** [comment]
או שבעצם כן... טוב, אבדוק

**Comment by akariv** [comment]
עכשיו מופיע
