### ISSUE TITLE
clickable drop-down

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#38]
יש ציפיה אינטואיטיבית שגם הכותרת תהיה לחיצה, לא רק החץ 
למשל אם התפריט פתוח, שאוכל לסגור אותו לא רק על ידי לחיצה על חץ, אלא גם על השורה הראשית

![image](https://user-images.githubusercontent.com/8996235/37711439-6a0b355c-2d19-11e8-99aa-12b77a473fe2.png)

**Comment by akariv** [comment]
fixed
