### ISSUE TITLE
tenders: mobile display

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#383]
- closed tender: https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c2a02dba72ae0af70ed4ed3

- closed tender collapsed: https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c2a02da08e761af2e28402a

- open tender with action item alert: https://app.zeplin.io/project/5c14cc360e0e0cb02de5ed2a/screen/5c165f505366b7aee17d9785

**Comment by akariv** [comment]
Example with tips: https://next.obudget.org/i/tenders/exemptions/629120/none?li=12
Example with awardees: https://next.obudget.org/i/tenders/central/553417/1-2014?li=0
Examples of a long description: 
- https://next.obudget.org/i/calls_for_bids/call_for_bids/642538903/0}
- https://next.obudget.org/i/support_criteria/support_criteria/272659091/0
Example for an interesting contract spending:
- https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%9E%D7%A9%D7%A4%D7%98%D7%99%D7%9D/4501131858/0008510313

**Comment by noamoss** [comment]
@akariv checked with two devices, looks great.

three glitches found:

1. long link is going out of the container ([link](https://next.obudget.org/i/support_criteria/support_criteria/272659091/0): 
![תמונה](https://user-images.githubusercontent.com/3581741/69180997-f96bd080-0b16-11ea-9272-5a22ebbc4067.png)

2. the timetable labels are shortened, and can not be understood (תש, צר):

![תמונה](https://user-images.githubusercontent.com/3581741/69181115-320baa00-0b17-11ea-8cfa-df22ebc73bb7.png)

3. tooltips are running out of screen:
![תמונה](https://user-images.githubusercontent.com/3581741/69181183-52d3ff80-0b17-11ea-97d1-9cbb56a75a9d.png)

4. 
2.

**Comment by noamoss** [comment]
@akariv 

1. fixed
2. looks better, but now we see the '%' without the real data (see screenshot below). I think we could give up on this piece of info (due to the fact we have the pie graph). The other solution is to push the number in a separate line.
3. the visual solution works, but to tooltip remains when I scroll down/up. Expected behavior: first click to hide it.
4. fixed
5. fixed

---

![image](https://user-images.githubusercontent.com/3581741/69238233-2adcae80-0ba0-11ea-8f20-4315cc78f334.png)

**Comment by akariv** [comment]
2. fixed
3. added message to tooltip

**Comment by noamoss** [comment]
checked and approved
