### ISSUE TITLE
scrape gov.il publications (tenders, call for bids, support criterias)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#385]
A. Use the type ("סוג") field to mark relevant publications, and keep the main/secondary topic fields for tagging:

https://www.gov.il/he/Departments/publications/
![image](https://user-images.githubusercontent.com/3581741/62830417-7550a580-bc17-11e9-8ad7-9af200928c93.png)

A1. for tenders ("מכרזים") use the new status field (פעיל) as Hakol-Kore opportunities filter. 

![image](https://user-images.githubusercontent.com/3581741/62830447-13447000-bc18-11e9-868e-36afc61480b8.png)

B. use "תמיכות ומענקים" &  for support criterias:
![image](https://user-images.githubusercontent.com/3581741/62830481-8a7a0400-bc18-11e9-933d-93396218b07a.png)

C. use "קול קורא" & "קולות קוראים" for call for bids:
![image](https://user-images.githubusercontent.com/3581741/62830522-e2186f80-bc18-11e9-9aad-2c008b34e788.png)

for "קולות קוראים" use the status field value ("פעיל") as an Hakol-Kore opportunities filter:
![image](https://user-images.githubusercontent.com/3581741/62830530-23108400-bc19-11e9-9654-0c0d230fd4fc.png)

*Notes:*
1. If 'מכרזים' is selected and the item heading starts with 'קול קורא' it should be handled as a call for bid:
![image](https://user-images.githubusercontent.com/3581741/62830397-02dfc580-bc17-11e9-8499-3cc393ee17cf.png)

**Comment by noamoss** [comment]
@akariv 

did not find the following item on a manual check:

* https://www.gov.il/he/departments/publications/Call_for_bids/jewishidentity

The others are there.

**Comment by akariv** [comment]
This is the one:

https://next.obudget.org/i/support_criteria/support_criteria/61706/63a8b6a0-82ae-4f79-a5e6-36d5df243ad3?li=0

**Comment by noamoss** [comment]
:+1:
