### ISSUE TITLE
scrape education ministry call for bids

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#386]
https://pob.education.gov.il/KolotKorim/Pages/KolKore.aspx

On the default list view, we can scrape the following data points:
![image](https://user-images.githubusercontent.com/3581741/62830653-d463e980-bc1a-11e9-9a32-2ce87172fe9b.png)

1. item description/title
2. publisher (department of the education ministry) 
3. due date
4. link for publication download + tag ("תבחינים")

Expanding the item display enables us to scrape the following data points:

![image](https://user-images.githubusercontent.com/3581741/62830702-93200980-bc1b-11e9-8843-77408f64c79b.png)

5. Takana No.
6. Contacts (notice: the number of the contacts is flexible, changes from item to item).
7. publication date
8. Merkava No.
10. Description/content

(in the description section we can see also relevant files to be extracted (9) - so with the 'link' label above)

* Note: While creating this issue, I tried to find duplicates on the gov.il data source. It seems like the education ministry publications do not appear there. We should, however, add a condition to prevent future duplication of the same publication appearing in both sources (just like with any other data source). Please describe the logic behind this check.

**Comment by noamoss** [comment]
A new item appears twice in the search results:

![image](https://user-images.githubusercontent.com/3581741/67570057-2c4dbf00-f739-11e9-9816-6dd2f26c5808.png)

**Comment by akariv** [comment]
fixed the duplication

**Comment by noamoss** [comment]
@akariv it works.

Could you explain what/how did you fix it?

**Comment by akariv** [comment]
Deleted some old data

**Comment by noamoss** [comment]
@akariv so it was just an old data issue? did you implement a double-entity check for this source?

**Comment by akariv** [comment]
yes and no

**Comment by noamoss** [comment]
so we should keep this issue open until we have a validation, to ensure it works

**Comment by akariv** [comment]
What is the other source of data that might cause duplication errors?

**Comment by noamoss** [comment]
minhal harekesh? 

![תמונה](https://user-images.githubusercontent.com/3581741/67639616-a8433500-f8fa-11e9-9957-d49c3ceea48a.png)


gov.il? 
![תמונה](https://user-images.githubusercontent.com/3581741/67639641-e3ddff00-f8fa-11e9-801c-dd58b7516d5b.png)

**Comment by akariv** [comment]
Yes, this issue is not about tenders but calls for bids... there's no calls
for bids from the education ministry in either gov.il or MR...

**Comment by akariv** [comment]
@noamoss can this be closed?
