### ISSUE TITLE
scrape: Ministry of Development of the Negev and Galilee publications

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#387]
http://negev-galil.gov.il/MediaCenter/Tenders/Pages/play_ground030719.aspx:

From the general list view we can extract:

1. publication status.
2A. publication type (title includes the type:
* קול קורא ל...
* מכרז פומבי מס...
*  פניה מוקדמת לקבל מידע
* נוהל סיוע

2B. Item title/description (rest of the text)

3. publish date
![image](https://user-images.githubusercontent.com/3581741/62830875-a1bbf000-bc1e-11e9-864d-90b364405fc3.png)

From the detailed item page ([example link](http://negev-galil.gov.il/MediaCenter/Tenders/Pages/play_ground030719.aspx)) we can add the folloowings:
4. due date
5. content
6. attached files
![image](https://user-images.githubusercontent.com/3581741/62830965-50146500-bc20-11e9-8bdc-b80e8154cd11.png)

Notice: I could not find a a way to extract the contacts from the general text, so we might have to ignore it for this data source.You might have an alternative idea.

**Comment by noamoss** [comment]
@akariv reminding we spoke about a need to prevent duplication back then (left as an open question) - this source is a good example for the need:

I just searched manually on the 'hakol-kore' for all of the currenty open publications.

Out of 11 publications 4 were not currently scraped, and consist valuable information for our users:

1. http://negev-galil.gov.il/MediaCenter/Tenders/Pages/park230919.aspx
2. http://negev-galil.gov.il/MediaCenter/Tenders/Pages/social220919.aspx
3. http://negev-galil.gov.il/MediaCenter/Tenders/Pages/budget2019.aspx
4. http://negev-galil.gov.il/MediaCenter/Tenders/Pages/tender250819.aspx

**Comment by akariv** [comment]
Yes, I remember that.

But there are two big questions here -
1. How do we detect and remove the duplications? The wording can be quite
different between the different data sources.
and perhaps more importantly,
2. Why some office tenders are not published in the central portal and is
it possible that we're missing a lot more office tenders?

**Comment by noamoss** [comment]
>1. How do we detect and remove the duplications? The wording can be quite
different between the different data sources.

Let's experiment, hopefully, we won't need to deal with corpora and lemmas. How does the following direction - any match of:
1. same publish date
2. same publisher
3. at least 3 identical words (if the title built of 5 words or longer) or 2 identical words (in case of a shorter title).

>why some office tenders are not published in the central portal and is 

Probably because something or someone does not work well in the governmental process. I think we or our content partners (מנהיגות אזרחית) contact the can contact the offices and ask, but it won't prevent the need of adding this resource, as we can tell for sure it has relevant information and we can not count on it to be fully updated on the main tender site. 

>Is it possible that we're missing a lot more office tenders?

No way to tell for sure, right? I believe we do, and therefore prefer to add these kinds of sources.

**Comment by akariv** [comment]
Sent mail to drors@pmo:

שני אדם ואני עובד בפרויקט ״רכש פתוח״ של הסדנא לידע ציבורי וחוקר את במסגרת הפרויקט את עולם המכרזים הממשלתיים.

אודה לך מאוד אם תוכל לעזור לי בנקודה קטנה שאני מנסה להבין.

אני מסתכל על אתר המשרד ורואה שם מספר מכרזים משרדיים (למשל 16/2019 או 23/2019).
אולם, כאשר אני משווה למידע המופיע באתר מנהל הרכש הממשלתי, רק חלק מן המכרזים הללו מופיעים.
ספציפית, המכרזים 9,12,13,14,15/2019 לא מופיעים שם ומופיעים רק באתר המשרד.

תוכל להסביר לי בבקשה מה מקור הפער? למה חלק מן המכרזים מופיע וחלק לא?

בתודה מראש,
אדם

**Comment by noamoss** [comment]
@akariv I guess you did not hear back, right?

can we move forward by adding the source for the items we don't have from MR?

**Comment by noamoss** [comment]
this issue will remain open to verify later wether we should complete missing (closed) items from that were not entered to the data.gov portal.

**Comment by noamoss** [comment]
@akariv this is the time, I would recommend adding the missing pieces. What do you think?

**Comment by akariv** [comment]
I think it's probably not worth the time to manually add to the database 4 closed tenders.
There are probably more pressing issues to handle first...

**Comment by noamoss** [comment]
@akariv following @maryLoi 's feedback, we should reopen this issue - we can ignore titles that include 'מכרז' if you are afraid of duplications, but should include 'קולות קוראים':

![תמונה](https://user-images.githubusercontent.com/3581741/70657021-c6bf7e80-1c63-11ea-907b-01678ec8d254.png)

**Comment by noamoss** [comment]
checked on live and approved.
