### ISSUE TITLE
Scrape Social Security: Requests for assistance and calls for proposals

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#388]
https://www.btl.gov.il/Funds/kolotkorim/Pages/default.aspx:

1. for Hakol-Kore opportunities filter by status: 'פתוח להגשה' & 'יפורסם בהמשך'

Extract the following data points:
2. The item title/description 
3. The publication file link
4. The fund name, use as a publisher (in addition to 'הביטוח הלאומי')
5. Target population (not sure if we should use it as part of the main content or as a tag/label, @akariv what do you think?)
6. field: use as tag
7. Q&A due date: to be used as part of the item content
8. status
9. due date
10. Optional element: if it appears add text "לשאלות ותשובות" + link for q&a
11. add label+link : "לטופס הגשת הבקשה"

![image](https://user-images.githubusercontent.com/3581741/62831058-e432fc00-bc21-11e9-91f6-43ba57377b09.png)

**Comment by akariv** [comment]
https://next.obudget.org/i/calls_for_bids/call_for_bids/703997173/0?li=0

**Comment by noamoss** [comment]
I approve checking and finding the two relevant items on social map.

@akariv I guess we will have to tackle it elsewhere, but both items appeared really(!) down in the results list, even when I typed in the entire title.
