### ISSUE TITLE
Scrape The Estate Commission (ועדת העזבונות) call for bids

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#389]
* This source is being updated 1-2 times a year (unknown dates). 

Basically, this issue is to ensure it was covered by the gov.il issue (#385 )

**Comment by akariv** [comment]
It's covered:

https://next.obudget.org/get/calls_for_bids/calls_for_bids/126947/3ab7feb7-709d-4e1c-8321-687aae93e364?li=0

**Comment by noamoss** [comment]
@akariv nice, but is it also included in the current הזדמנויות definition?

**Comment by akariv** [comment]
All calls for bids, tenders and support criteria are included.
