### ISSUE TITLE
scrape Ministry of culture past supports

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#390]
This issue aims to verify if we can extract past office supports for NGOs.

In the following link you will find xls files for past years, documenting the NGO number + name and the reported amount:
https://www.gov.il/he/Departments/General/ministry_support

![image](https://user-images.githubusercontent.com/3581741/62831526-9621f680-bc29-11e9-9afc-4f8a0c4b32db.png)

**Comment by akariv** [comment]
Seems that all of these are already in the system.

Verification - 
Opened the link: https://www.gov.il/he/departments/general/ministry_support

Chose an old file:
<img width="533" alt="Screen Shot 2019-11-04 at 12 40 07" src="https://user-images.githubusercontent.com/265333/68115256-a67fff80-ff00-11e9-9035-f2ceb3b9bc42.png">

Chose the first row in the file:
<img width="788" alt="Screen Shot 2019-11-04 at 12 40 36" src="https://user-images.githubusercontent.com/265333/68115278-b3045800-ff00-11e9-8a54-ca67410d18ca.png">

Opened the relevant page in BudgetKey - https://next.obudget.org/i/org/municipality/500221015?li=0

Scrolled down to the supports list:
<img width="1022" alt="Screen Shot 2019-11-04 at 12 41 31" src="https://user-images.githubusercontent.com/265333/68115311-cca59f80-ff00-11e9-8dde-f19d65734820.png">

**Comment by noamoss** [comment]
I can approve checking a couple of and finding them all in the obudget (checked later years). What is the current source you are using? Did you alread upload it manually before?

**Comment by akariv** [comment]
This is the supports database, it's being uploaded (manually at this point)
every few months.

@Noamoss <noamoss@gmail.com>

**Comment by akariv** [comment]
An update on this issue - although we closed it, I think that manual scraping (with such a low frequency) is not very sustainable.
So I added an automatic scraper for the supports source to run daily.
