### ISSUE TITLE
scraper: prime minister office support criteria

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#392]
http://www.pmo.gov.il/Pages/GovernmentSupport.aspx

This page includes a separate section per publication

![image](https://user-images.githubusercontent.com/3581741/62831676-dbdfbe80-bc2b-11e9-8a01-13be9b799b49.png)

- title 'תמיכות במוסדות ציבור המנציחים זכרם ופועלם של נשיאי ישראל, ראש ממשלותיה ודמויות נוספות לשנת [year]'
- textual content/description: "בהתאם להוראות סעיף 3א לחוק יסודות התקציב, התשמ"ה-1985, גיבש משרד ראש הממשלה, בהתייעצות עם היועץ המשפטי לממשלה ובהתייעצות עם המועצות הציבוריות הרלוונטיות, מבחנים לחלוקת כספי התמיכות של משרד ראש הממשלה לתמיכה במוסדות ציבור המנציחים את זכרם ופועלם של נשיאי ישראל וראשי ממשלותיה, זכרו ופועלו של זאב ז'בוטינסקי, זכרו ופועלו של בנימין זאב הרצל וזכרו ופועלו של רחבעם זאבי."
- tags: :"הנצחה"
- publisher: משרד ראש הממשלה
- publish date: the month/year in which we find out of the udpate
- attach all the files in the section with their labels

- I would add 'לא ידוע' as due date and make sure to mark it as closed when the budget year ends. (@akariv any other idea here?)

**Comment by akariv** [comment]
The link seems to be already dead - https://www.gov.il/he/Departments/General/government_support is the new one I think.

Also, it seems all support criteria documents there are already in our system, e.g.:

https://next.obudget.org/i/support_criteria/support_criteria/220282023/0?li=0

**Comment by noamoss** [comment]
@akariv 

>Also, it seems all support criteria documents there are already in our system, e.g.:

could not find "פרסום מבחנים לתמיכה במוסדות ציבור בתחום ההכנה לגיור" 

BTW, could not find also  "תמיכות לזכרו ופועלו של השר רחבעם זאבי ז"ל (גנדי)"

both are available on  https://www.gov.il/he/Departments/General/government_support

**Comment by akariv** [comment]
https://next.obudget.org/s/?q=%D7%A8%D7%97%D7%91%D7%A2%D7%9D%20%D7%96%D7%90%D7%91%D7%99&dd=supports&range=all&lang=he&kind=support_criteria

https://next.obudget.org/i/support_criteria/support_criteria/149922802/0?li=4
