### ISSUE TITLE
scrape Justice Ministry tenders

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#393]
https://www.justice.gov.il/Pubilcations/Tenders/Pages/SearchTender.aspx:

fromt the main list view extract the following details:

1. publication no.
2. publication type: 
2A מכרז פומבי --> מכרז משרדי
2B בקשה לקבלת מידע RFI
3. title/description
4. detailed page url
5. due date

![image](https://user-images.githubusercontent.com/3581741/62831834-991ee600-bc2d-11e9-9f9d-423e850a95d9.png)

From the detailed page we can extract the followings:

6. publicatoin status (use 'חדש' as Hakol-Kore opportunities filter)
7. publish date
8. due time (to combine with the due date value)
9. contact person
10. publisher unit
11. contact email
12. comments
13. attached files

![image](https://user-images.githubusercontent.com/3581741/62831871-23ffe080-bc2e-11e9-8692-274aafdce765.png)

----
*notice:* for this source we know for sure that some items appear in מנהל הרכש tenders engine ([example](https://www.justice.gov.il/Pubilcations/Tenders/Pages/45-2019.aspx)) and some do not ([example](https://www.justice.gov.il/Pubilcations/Tenders/Pages/27-2019.aspx)). 

Therefore, we can use it as a case study to check two sources and prevent items duplications (I think we should always prefer the מנהל הרכש in terms of duplication - but should consider showing a warning to the user: "מצאנו יותר ממקור ממשלתי אחד בנוגע לפרסום זה. המידע המובא כאן לקוח מאתר מנהל הרכש הממשלתי').

**Comment by akariv** [comment]
From what I checked, all items I sampled in the Justice website also appeared in the MR one -

your example, for example, also appears there:

https://www.mr.gov.il/officestenders/Pages/officetender.aspx?pID=634564

**Comment by noamoss** [comment]
👍 
I will keep it open to recheck. Right now all 3 opportunities jump in the social map as well.

**Comment by noamoss** [comment]
I rechecked and can approve finding all items in our search results. closing issue.
