### ISSUE TITLE
scrape Justice ministry class action lawsuit (קרן תובענות יצוגיות)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#394]
https://www.justice.gov.il/Units/ApotroposKlali/Departments/ApotroposKlali/giloi/Pages/ClassActionLaw.aspx

All the items are published in this single page, in the lower section table. My suggestion for the items are:

1. item no.
2. link for attached file (label should be: "פרסום רשמי")
3. item title: קרן התובענות היצוגיות + [topic]
4. due date
5. updates (notice, seems like it is being used mainly for due date extenstion)
6. static item content - from the page upper part

![image](https://user-images.githubusercontent.com/3581741/62831926-3890a880-bc2f-11e9-8351-e9565a54e0f0.png)

**Comment by akariv** [comment]
Once again -
- The link is dead (long live the new link https://www.gov.il/he/Departments/publications/reports/class_action_law)
- here is already information in the ezvonot database that is somewhat overlapping with the data here For example, see:
  
  <img width="596" alt="Screen Shot 2019-11-04 at 13 05 38" src="https://user-images.githubusercontent.com/265333/68116583-dda3e000-ff03-11e9-85e5-561d48446fde.png">

  and 
  https://app.redash.io/hasadna/queries/279776/source

It seems that there's going to be very difficult to connect the two data sources automatically (perhaps we could do it manually?).

**Comment by noamoss** [comment]
@akariv 
> ...to connect the two data sources

which two? please be explicit

>(perhaps we could do it manually?)

do you suggest that because of the structure of the source or because of a potential duplication? 

I can see why scraping such a thin source might feel like a waste of time, but on the other hand- this page seems to be stable and keeps updating once in a while during the last 1.5 years. I am not sure making it a manually updating is maintainable.

**Comment by noamoss** [comment]
Following our quick talk: we decided to split the two sources, for now. Once done, we can open a new (future) issue to explore ways to combine.

**Comment by noamoss** [comment]
agreed.

**Comment by akariv** [comment]
Sample item:

https://next.obudget.org/i/calls_for_bids/call_for_bids/873700058/07/2019?li=9

**Comment by noamoss** [comment]
@akariv looks good, and works fine. 

One small visual fix is needed: the attached file is displayed without name (which makes it not really clear as a downloadable resource). I think we should use the convention in the source and display a 'קול קורא' label:
![image](https://user-images.githubusercontent.com/3581741/68489900-b4ab8400-0250-11ea-9921-495586c85d51.png)


![image](https://user-images.githubusercontent.com/3581741/68489850-92b20180-0250-11ea-87c8-3d3df1a39123.png)

**Comment by akariv** [comment]
Done:

https://next.obudget.org/i/calls_for_bids/call_for_bids/869230893/07/2019?li=0

**Comment by noamoss** [comment]
checked and approved on live.
