### ISSUE TITLE
scrape justice ministry general guardian (האפוטרופוס הכללי) 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#395]
updated source link:  https://data.gov.il/dataset/ezvonot2018

------
This source was originally intended for כספי הקדשות. I wrote this issue in a bit more general way, hope it makes sense. 

https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/default.aspx

from the general list view extract the following data points: 
1. item title
2. URL to the detailed page
3. publish date
4. body content first line(s)

![image](https://user-images.githubusercontent.com/3581741/62832173-2ca6e580-bc33-11e9-98cc-d8a7827d0e11.png)

https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/Rivlin.aspx:
5. additional body content
6. attached files

![image](https://user-images.githubusercontent.com/3581741/62832151-f6696600-bc32-11e9-80a2-33b73c23edcf.png)

----

*notes*: 
1. We have a unique challenge with this source: it includes not only relevant publishes, but also ongoing updates which we don't want to include in our DB. My initial thought was to exclude items that include words from a pre-defined blacklist (i.e. [תקלה](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/MelfunctionAlert.aspx), [דו"ח](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/31072019.aspx), [דרוש/ה or דרוש or דרושים](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/2904219_2.aspx).)  - But it still leaves us with irrelevant items entering our database. Therefore the preferred solution would be choosing whitelist words list:
- [תמיכה](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/New_Report.aspx)
- [מכרז](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/tender_5_2_19.aspx) 
- [פרס](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/Rivlin.aspx)
- [מלגות or מלגה](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/Scholarship8112018.aspx)

The downside of this alternative is missing out some relevant publishments, [like this](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/ExitDebtCycle.aspx).

2. We also have a unified data source: ["רשימת הנעדרים"](https://www.justice.gov.il/Units/ApotroposKlali/Departments/ApotroposKlali/giloi/Pages/rashimatNeedarim.aspx). Every time it is being updated, a general announcement item is being published ([example](https://www.justice.gov.il/Units/ApotroposKlali/PressRoom/News/Pages/16052019.aspx)), but it might be easier to build a specific checker and scraper for the list page and update the attached file every time it is changing. 

In both cases, we should not include the "עודכנה רשימת הנעדרים ​" as a standard item.

**Comment by akariv** [comment]
A lot of the links broke as this unit moved to publish stuff using the standard gov publications method.

Still I'm not sure a prize for a poet/writer or a scholarship for students should be considered a 'kol kore' at all. Same goes for the list of missing persons - how's that relevant?

This unit has a list of support 'areas' which are defined on a yearly basis (we should locate their source - I only found a textual description of them in a pdf: https://www.gov.il/he/departments/news/new_19319
Also interesting (but we need the data) - the dedicated inheritances which you can apply for: https://www.gov.il/he/departments/news/new_190319

**Comment by noamoss** [comment]
@akariv 

>Still I'm not sure a prize for a poet/writer or a scholarship for students should be considered a 'kol kore' at all...how's that relevant?

If you are one of [these organizations](https://next.obudget.org/s/?q=%D7%A1%D7%A4%D7%A8%D7%95%D7%AA&dd=associations&range=all&lang=he&theme=socialmap&org_kind=all&region=all&creds=all&public_funds=all), it might be relevant.

> Same goes for the list of missing persons - how's that relevant?
Now, this is a good question, but we should ask ourselves if we have a way (based on the current publications) to put aside these irrelevant publications (like a list of missing people) and keep the relevant ones. Looking at the examples above I believe there is no real harm adding this non-budget information to the system, as long as it serves the main goal: updating the NGOs about possibly relevant publication.  

>This unit has a list of support 'areas' which are defined on a yearly basis (we should locate their source - I only found a textual description of them in a pdf.....Also interesting (but we need the data) - the dedicated inheritances which you can apply for: 

so - what would you suggest to do? use it as a filtering mechanism for this source? I think it is overkill, but tell me if I am missing something or misunderstood you.

**Comment by akariv** [comment]
How a poetry prize is an opportunity for a literary research organization?

The task here was to try and find these more focused datasets (support
criteria and dedicated estates) as data and pull them in the system, and
not the list of press releases that's currently required.

Iirc that data is in data.gov.il, but I'm not sure about the update
schedule or the resolution of the data.

**Comment by noamoss** [comment]
>How a poetry prize is an opportunity for a literary research organization?

It might promote this piece of information among its active members. It might realize that it is possible to ask for public money for awards. I agree It is an edge case scenario (appropriate to the edge case example publication I chose at the demo :) ).

>Iirc that data is in data.gov.il, but I'm not sure about the update schedule or the resolution of the data

And we can not say for sure if everything moves from the announcements to the data.gov.il

> The task here was to try and find these more focused datasets (support
criteria and dedicated estates) as data and pull them in the system, and
not the list of press releases that's currently required.


you're right, sorry. Let's start with the obvious: we will define a set of obvious words/terms/variations in the publication title that would hint us (as potential users) it is a potential opportunity, for example:
- קול קורה
- תמיכה
- לתמיכה
- לתמיכת
- תמיכת
- תמיכות
-מכרז
- מכרזים
- במכרז
- במכרזים
- למכרז
- למכרזים

**Comment by akariv** [comment]
I don't think you're understanding what I'm trying to say.
There are two datasets here that are actually important:
- ths list of support 'areas' which are defined on a yearly basis (we should locate their source - I only found a textual description of them in a pdf: https://www.gov.il/he/departments/news/new_19319
- the dedicated inheritances which you can apply for: https://www.gov.il/he/departments/news/new_190319

Each row from each one of those should be added to the database as a separate single item - the press release about the fact that the data exists is of no interest. 

Other than these two high-interest data-sets everything else on this press-release list is of low interest and quality.

**Comment by akariv** [comment]
I think I found the second one - 
https://data.gov.il/dataset/ezvonot2018

**Comment by noamoss** [comment]
this is the part I am not sure I understand/agree with:

>the press release about the fact that the data exists is of no interest

espcially if we don't have a sustainable source for the support criteria 'areas'

---

> I think I found the second one 

:clap: :clap: :clap:

**Comment by akariv** [comment]
the press release about the fact that the data exists is of no interest to us because it's neither a call for bids or a support criteria document. 
If we could parse its contents (or find them somewhere else), we could take the different support areas and convert each one to a proper item in our db.

**Comment by noamoss** [comment]
>the press release about the fact that the data exists is of no interest to us because it's neither a call for bids or a support criteria document.

but it might be an indication of potential opportunity. Don't you think? I mean, isn't it a way to MISS an important update/budget for NGOs?

**Comment by akariv** [comment]
In our system we scrape and store actual, concrete opportunities - with
proper dates, and relevant information on each one.
A press release indicating the possible existence of some opportunity -
which without opening and browsing through a pdf document I won't be able
to know if it's relevant to me or not - is not very useful.
To most people it would be a waste of time and anyway users wouldn't even
see it as it wouldn't even appear in the results for any targeted search.

**Comment by noamoss** [comment]
convinsed. what's now?

**Comment by akariv** [comment]
bad news - the files in data.gov.il are regularly updated (last update was
last week) but all files are empty.
Send a request in the contact form, if this doesn't work I'll try my
data.gov.il connections....

**Comment by noamoss** [comment]
done. Also, update issue's description.

**Comment by akariv** [comment]
@noamoss to add a new spec for handling the data.gov.il files (preferably in a new issue and closing this one).

**Comment by noamoss** [comment]
@akariv sent you some questions on slack, will close this issue for a new one when we decide how to continue.

**Comment by noamoss** [comment]
sent the following request: 

![image](https://user-images.githubusercontent.com/3581741/69869574-e050e580-12b5-11ea-9fc1-34a5d8e673e6.png)

**Comment by noamoss** [comment]
![image](https://user-images.githubusercontent.com/3581741/70737280-dbab1900-1d1a-11ea-96fa-e6292a3bc329.png)

**Comment by akariv** [comment]
@noamoss what's the next step here?

**Comment by noamoss** [comment]
@akariv figuring out what/if can be done, meanwhile please leave it assigned to me. You said you were about to meet Rivki this week, did you remember to ask her about potential connections?

**Comment by noamoss** [comment]
closing in favor of #491.
