### ISSUE TITLE
alert/notification email, responsive/adapt for mobile

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#398]

**Comment by noamoss** [comment]
@akariv you said we don't need a design for this issue since it is more of a developmental challenge. Please let me know if something is needed here.

**Comment by noamoss** [comment]
@akariv  reopening issue with a bug report:

first sections look fine on mobile, but starting the "בקשות חדשות לפטור ממכרז" all search titles are broken:

![Screenshot_2019-11-29-14-20-32-675_com google android gm](https://user-images.githubusercontent.com/3581741/69868985-2a38cc00-12b4-11ea-9e33-44b8b49ffb0b.jpg)

**Comment by akariv** [comment]
Any information on the device maker / UI language / email client?

**Comment by noamoss** [comment]
gmail app on android, redmi 7

**Comment by noamoss** [comment]
also, see the following errors on my laptop ([whatismybrowser details)](whatismybrowser.com/w/4JMCNJR):

![image](https://user-images.githubusercontent.com/3581741/70381031-7935cf80-194c-11ea-9af5-212a50e63074.png)

**Comment by noamoss** [comment]
If I am not mistaken, only the top section of the email behaves and looks ok both on mobile and wider screens.

**Comment by akariv** [comment]
תוקן

**Comment by noamoss** [comment]
@akariv can you send me a test mail for check?

**Comment by noamoss** [comment]
@akariv 
checked and approved the recent fix.

one problem remains (the screenshot was taken with a redmi 7): the longest title+subitles are being cut. Maybe that it can be fixed by pulling (all titles+subtitles) to the right (centralized following the subitems borders, instead of the entire page):
 
![image](https://user-images.githubusercontent.com/3581741/71549249-2d160200-29c3-11ea-86f6-7d1d7834b59b.png)


![image](https://user-images.githubusercontent.com/3581741/71549287-fa203e00-29c3-11ea-97e7-f56d30307864.png)

**Comment by akariv** [comment]
Fixes style hopefully

**Comment by noamoss** [comment]
yep! checked and approved.
