### ISSUE TITLE
תוצאת חיפוש כפולה

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#40]
https://next.obudget.org/s/?q=27.12.01.01&dd=all

שתי התוצאות בחיפוש זהות

![image](https://user-images.githubusercontent.com/8996235/37775155-da6fb850-2dea-11e8-872b-d0d979ba0a45.png)

**Comment by akariv** [comment]
זאת בעיה שהיתה מתרחשת רק עם סעיפי תקציב ריקים (כלומר ללא תקציב או ביצוע)

הסעיפים הללו כבר לא מופיעים בתוצאות.
