### ISSUE TITLE
מספר תקנה לחיץ בדף רכש

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#400]
במספר התקנה להוריד שני אפסים מובילים ולהפוך אותו ללחיץ
דוגמה
![image](https://user-images.githubusercontent.com/8996235/64557175-b12b7780-d349-11e9-85d1-83fdd751fb30.png)

https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%97%D7%99%D7%A0%D7%95%D7%9A/4501095356/0020460125?li=0

**Comment by DanilDelegator** [comment]
Hi, I'd like to work on this issue. Can you specify what you think it should redirect to? @maryLoi
