### ISSUE TITLE
קול קורא: סטטוס וקישור לא נכון

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#401]
https://next.obudget.org/i/calls_for_bids/call_for_bids/259976757/None?li=4

הסטטוס פתוח - לא מעודכן
קישור לפרסום המקורי מוביל לדף הבית של ג'וביז - לא רלוונטי

**Comment by noamoss** [comment]
@maryLoi 

> קישור לפרסום המקורי מוביל לדף הבית של ג'וביז - לא רלוונטי
בגלל מגבלות ג'וביז, בפרסומים משם אין לנו אלטרנטיבה אמיתית- אין קישור ישיר למקור המדוייק.

>הסטטוס פתוח - לא מעודכן

קשור ל- #408 

@akariv you can use this example to verify after you fix it.

**Comment by akariv** [comment]
הקישור המקורי כבר לא עובד (כבר אמרנו שתמיד טוב לשים צילום מסך?)

בכל מקרה, היתה בעיה בסטטוסים של פריטים מג׳וביז והיא תוקנה.

לגבי הלינק למקור - זה הכי טוב שאפשר לעשות עם האתר הזה.

**Comment by noamoss** [comment]
@maryLoi  checked for a similar concrete problem on Jobiz, but could not find. For example, this item on Jobiz:
![image](https://user-images.githubusercontent.com/3581741/71450405-e7123180-2769-11ea-8dc1-d1743d167a5a.png)


and found the relevant item on obudget: https://next.obudget.org/i/support_criteria/support_criteria/281016662/0?li=2&theme=socialmap:
![image](https://user-images.githubusercontent.com/3581741/71450409-fbeec500-2769-11ea-948e-b27defdad8af.png)

looks good to me. Please reopen this issue if you find relevant examples.
