### ISSUE TITLE
renew welfare ministry scrapers

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#405]

**Comment by noamoss** [comment]
@akariv I can not check this is working, as there are no open calls on the webpage (https://www.molsa.gov.il/Publications/Pages/PubAppealSearch.aspx). Will recheck soon and update here.

**Comment by noamoss** [comment]
on the other hand, I see a duplication of item from this source with gov.il:

https://next.obudget.org/s/?q=%D7%A9%D7%99%D7%A4%D7%95%D7%A6%D7%99%D7%9D%20%D7%95%D7%94%D7%A6%D7%98%D7%99%D7%99%D7%93%D7%95%D7%AA%20%D7%91%D7%9E%D7%A2%D7%95%D7%A0%D7%95%D7%AA%20%D7%97%D7%A1%D7%95%D7%AA%20%D7%94%D7%A0%D7%95%D7%A2%D7%A8%20&dd=opportunities&range=all&lang=he&theme=socialmap&kind=all&focused=no

**Comment by akariv** [comment]
The link you provided is outdated - it doesn't show anything that's not a year old - we're currently getting MOLSA calls for bids and support criteria from gov.il publications only.

Not sure what duplication you're referring to...

<img width="1251" alt="Screen Shot 2019-10-25 at 23 03 38" src="https://user-images.githubusercontent.com/265333/67600877-b6b71280-f77b-11e9-9adf-96ef0151019a.png">

**Comment by noamoss** [comment]
>Not sure what duplication you're referring to...

**Comment by noamoss** [comment]
>Not sure what duplication you're referring to...

may bad, I got confused. sorry.

Going back to my original reposnse:


 I can not check this is working, as there are no open calls on the webpage (https://www.molsa.gov.il/Publications/Pages/PubAppealSearch.aspx). Will recheck soon and update here.

**Comment by akariv** [comment]
Again, this page didn't update with anything new for a year now so don't
hold your breath.

**Comment by noamoss** [comment]
don't blame me for my hobbies :)

**Comment by akariv** [comment]
What I'm trying to say is they're now publishing using gov.il standard
publications mechanism

**Comment by akariv** [comment]
See here:

https://www.gov.il/he/departments/publications/?limit=10&publicationType=7159e036-77d5-44f9-a1bf-4500e6125bf1&rfpStatusType=c8ed2e3c-e5a9-4101-93f5-bae798c4ac1d&OfficeId=4fa63b79-3d73-4a66-b3f5-ff385dd31cc7

**Comment by noamoss** [comment]
@akariv I saw that, I am just not sure they entirely/officialy stopped using their website, based on the fact (or my understanding) they are still publishing tenders the like before (https://www.molsa.gov.il/Tenders/Pages/ServicesTendersSearch.aspx).

**Comment by akariv** [comment]
Who knows... Either way, for tenders as well the data in minhal harechesh
seems to be more complete and based on their disclaimer, more up.to date.

**Comment by noamoss** [comment]
@akariv 

> for tenders as well the data in minhal harechesh
seems to be more complete and based on their disclaimer, more up.to date.

I guess you are right, but as your wrote, who knows...

Just to make sure - do you still scrape this source and added a double-enetity check for this source?

**Comment by akariv** [comment]
no, we only use gov.il and MR sources for this office.

**Comment by noamoss** [comment]
ok, I tried to challenge your assumption, but did not find a relevant item that is missing on our search. Closing this issue.
