### ISSUE TITLE
open/close opprtunities for items with no due date

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#408]
following a use report:
![image](https://user-images.githubusercontent.com/3581741/67632140-5bcf0980-f8a8-11e9-8100-860219452b6e.png)

I guess the challenge here is that we don't have a 'due date' value to populate. Both provided examples are 'מבחן תמיכה', but I assume we might find similar scenarios with other content types.

My idea: 
1. Decide that these should be defined 'unknown' and keep it open for 4 weeks - I see a problem with this solution in term of showing a misleading information to our users. 
2. Try to find the following structure in the item description 'עד ל.... [all possible date structures regex]'
and populate the missing value with the scraped value. When we can not find the structure, I would still recommend applying option 1 as a fallback. 

----
should update the user when done at yardenk86@gmail.com

**Comment by noamoss** [comment]
see https://github.com/OpenBudget/BudgetKey/issues/407#issuecomment-549028173 - might be relevant here as well.

**Comment by akariv** [comment]
To be more elaborate on the spec (@noamoss please review) -

- If the item has a 'claim date' (מועד הגשה):
  - if current date is before the claim date:
    - set the status to פתוח
  - else
    - if the item already has a status (from scraping)
      - leave the status as is
    - else:
      - set the status to 'סגור'
- else
  - if publication date is known (from scraping) use it, else use the discovery date (=the first time we saw the item) as publication date for the next if
  - if not 4w passed from the publication date
    - set the status to 'חדש'
  - else:
    - set the status to 'לא ידוע'

**Comment by noamoss** [comment]
@akariv 

first part looks ok, for the second part see my comments below:

>if not 4w passed from the publication date

>    set the status to 'חדש'

status should be 'פתוח'. 
חדש, from the user perspective, is not a status, but an extra indication/piece of information about an open (חדש) status. It is also relevant for items with unknown claim date for the first X (...sorry, don't remember our current definition) days/weeks after it appears on our site, just like for the other (with a know claim date) items.

> else:

>    set the status to 'לא ידוע'

I am not sure we should make things more complicated with a 3rd "unkown"/לא ידוע status.  I  thought just to switch from פתוח to סגור, which seems enough -  as long as we also disaply the following text in the page body"לא הצלחנו לאתר במקור המידע הממשלתי את התאריך בו נסגרת ההרשמה".

**Comment by akariv** [comment]
Ah, this is just a summary of what we talked about.
The logic in our conversation is that if we can't ensure 100% that an item is actually open, then we shouldn't advertise it as such (and thus avoid confusing users), and use a weaker promise - not 'open' but rather 'recently published' (which might mean it's still open but not necessary).
Having a 'closed' status after 4 weeks is also wrong - it might have been cancelled, or it's still open or anything really. In fact, we don't really know what the status is at this point - thus 'unknown' is the most apt status. 
One thing to note is that the 'unknown' status will never appear in the emails (as we're filtering by status) nor in the opportunities section, so the chance of it confusing users is quite low.

ps - there are a few other statuses besides 'פתוח' and 'סגור':
פעיל, ממתין לתוצאות are two examples

**Comment by noamoss** [comment]
@akariv 

### discussion:

>The logic in our conversation is that if we can't ensure 100% that an item is actually open, then we shouldn't advertise it as such

you are right. it has been too long, I forgot this part.

>One thing to note is that the 'unknown' status will never appear in the emails (as we're filtering by status) nor in the opportunities section, so the chance of it confusing users is quite low....ps - there are a few other statuses besides 'פתוח' and 'סגור':
פעיל, ממתין לתוצאות are two examples

1. You are right, I forgot it all since the last time I worked on it. Still, correct me if I am wrong: חדש and פתוח are not at the same label hierarchy. right? 

2. The truth is I was mainly concerned about the emails, but this discussion brings up, maybe, a better way we could handle it: the raw status(es)  an are piece of data to show the user, teaching them of the current step of the item's relevant process -  while the open (actable) / closed (archived) items are conclusions/guesses we make/calculate for the user, as an interpretation. In other words, I believe it would be better sometime to split the status into two separate fields.

-----
### QA
worked with https://next.obudget.org/i/support_criteria/support_criteria/516032133/0?li=11, as a qa case study. results:


1. the "חדש" label is not following other item pages style
2. we should explicitly explain we do not know the due date: "תאריך אחרון לפניות: לא ידוע"
3. I would add a tip for action for these "unknown" scenarios: "לא הצלחנו לאתר במקור המידע הממשלתי את התאריך בו נסגרת ההרשמה. לבירור, מומלץ לבדוק בפרסום המקורי או ליצור קשר עם האחרא/ית.". It should be a red strip tip (at the top of the item's page).
4. searched for "מבחנים לחלוקת כספי תמיכות" but it did not appear on the hakol-kore results

**Comment by noamoss** [comment]
@akariv reopening, as you did not relate to my qa findings, see above.

**Comment by akariv** [comment]
> You are right, I forgot it all since the last time I worked on it. Still, correct me if I am wrong: חדש and פתוח are not at the same label hierarchy. right?

Yes and no. We're talking about the status here, so the only thing we know about the status is that if it was recently published, it's probably open (although we can't be sure). 
We could use a more accurate 'כנראה פתוח' or 'פורסם לאחרונה' instead (but let's keep it simple).

> I believe it would be better sometime to split the status into two separate fields.

We've been calculating and simplifying the status for a long time, all the way back from open-procure. Not sure what is different now... and in any case, we calculate the status when there is no status in the source, so what would we show?

QA:
> the "חדש" label is not following other item pages style

This label is the computed status (i.e. if < 4 weeks since publication).
The regular new label (highlighted in yellow) is for items with <1 week since publication.
This means that both label will appear if item is really new, creating a confusing experience and perhaps amplifying the need for a more accurate status label which is not 'חדש'.

> we should explicitly explain we do not know the due date: "תאריך אחרון לפניות: לא ידוע

Agreed, done

> I would add a tip for action for these "unknown" scenarios

Added an action tip in the same style as the rest of them

> ... did not appear on the hakol-kore results

Not sure exactly what result you were hoping to find, but just in case - 
the opportunities are filtered also by status - currently there's a list of two valid statuses which cause the result to appear, see here:
https://github.com/OpenBudget/budgetkey-themes/blob/master/theme.socialmap.he.json#L240

Once we decide on the correct word for the 'probably open' status, we'll add it to the list.

**Comment by noamoss** [comment]
>We could use a more accurate 'כנראה פתוח' or 'פורסם לאחרונה' instead (but let's keep it simple)....Once we decide on the correct word for the 'probably open' status, we'll add it to the list.

agree, we should keep it simple. I would stay with פתוח using the same logic we defined: 4 weeks open fo unknown open/closing date. My new idea is to change "פרסום ראשון:" to "פורסם באתר:" and to add another label to the body: "מועד פרסום: לא ידוע" (just like you did for the due date.

I believe that a tool on both ("מועד פרסום: לא ידוע" and "מועד סגירה: לא ידוע") with the explanation I offered is good enough to ensure the user understands what's going on.

>Not sure what is different now..

Let's talk when we meet, I will explain (maybe I am wrong here).

>we should explicitly explain we do not know the due date: "תאריך אחרון לפניות: לא ידוע

checked and approved.

>Added an action tip in the same style as the rest of them

couldn't see it [here](https://next.obudget.org/i/support_criteria/support_criteria/516032133/0?li=11)

**Comment by akariv** [comment]
> agree, we should keep it simple. I would stay with פתוח using the same logic we defined: 4 weeks open fo unknown open/closing date. My new idea is to change "פרסום ראשון:" to "פורסם באתר:" and to add another label to the body: "מועד פרסום: לא ידוע" (just like you did for the due date.

Implemented.

> couldn't see it here

That's what you get for running QA before the issue had been closed.
You should be able to see it now.

**Comment by noamoss** [comment]
checked and approved on live.

@akariv I set a reminder to revisit this check on Dec 2, to verify the status change.

**Comment by noamoss** [comment]
@akariv 4 weeks later, status did not change, this is a problem

**Comment by noamoss** [comment]
my bad: need to check in a week...

**Comment by noamoss** [comment]
@akariv status did not change

**Comment by akariv** [comment]
There was a bug in the update mechanism, seems to be working now.

https://next.obudget.org/i/support_criteria/support_criteria/191019351/0

**Comment by noamoss** [comment]
@akariv not sure, see:

https://next.obudget.org/i/calls_for_bids/call_for_bids/214488145/0?li=12&theme=socialmap

![image](https://user-images.githubusercontent.com/3581741/71450597-65bc9e00-276d-11ea-83dc-757c7ff986ac.png)
 (Taken on Dec. 25 19)

**Comment by akariv** [comment]
Seems like some old data as the original item no longer exists in the source.
I'll make sure to fix all the old jobiz items as well.

**Comment by noamoss** [comment]
@akariv thanx, let me know when ready for a recheck.

**Comment by akariv** [comment]
Seems like it's solved.

**Comment by akariv** [comment]
@noamoss can we close?

**Comment by noamoss** [comment]
@akariv not yet.  I am following [this item](https://next.obudget.org/i/support_criteria/support_criteria/500006501/0?li=3&theme=socialmap). Will recheck and update/close this issue on January 24.

**Comment by akariv** [comment]
@noamoss can we close?

**Comment by noamoss** [comment]
@akariv nope, please take a look here: https://next.obudget.org/i/support_criteria/support_criteria/500006501/0?li=3&theme=socialmap

the item is still open.

**Comment by akariv** [comment]
Did you find this item in search?
Couldn't find it there.
@noamoss

**Comment by noamoss** [comment]
@akariv 
no, the status still should be closed in the item page. 

Think of a scenario in which I received a notification email, but opened it two weeks later - it gets me to this item page.

**Comment by akariv** [comment]
This is probably an old item prior to the bugfix.
The item ids changed quite a bit before they settled, and there are still
some of the old ones lurking around - but they shouldn't be findable
through the search (un-searchable items also get deleted from the index
eventually)
Please try to find an existing example of an item which appears in search
and isn't according to spec.

**Comment by noamoss** [comment]
@akariv 

>there are still some of the old ones lurking around 

can't you easily locate and fix them on DB by crossing `publish date` + `no due_date` + `status == open` and set their status to `closed`?

>Please try to find an existing example of an item which appears in the search

will do

**Comment by akariv** [comment]
No point, as next week they will be deleted anyway...

**Comment by noamoss** [comment]
Deleted? Please explain

**Comment by akariv** [comment]
> This is probably an old item prior to the bugfix.
> The item ids changed quite a bit before they settled, and there are still
some of the old ones lurking around - but they shouldn't be findable
through the search (un-searchable items also get deleted from the index
eventually)

**Comment by noamoss** [comment]
could not find further relevant examples. closing issue.
