### ISSUE TITLE
עץ התקציב לא מוצג

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#41]
לא מוצג עץ התקציב, הסכומים והגרף

http://next.obudget.org/i/budget/0027120101/2017?li=0

![image](https://user-images.githubusercontent.com/8996235/37775298-49f44a74-2deb-11e8-9779-fe9c35eae381.png)

**Comment by akariv** [comment]
התקנה כבר לא מופיעה בחיפוש

https://next.obudget.org/s/?q=%D7%94%D7%A9%D7%9C%D7%9E%D7%AA%20%D7%94%D7%9B%D7%A0%D7%A1%D7%94%20%D7%9C%D7%9E%D7%A7%D7%91%D7%9C%D7%99%20%D7%A7%D7%A6%D7%91%D7%90%D7%95%D7%AA%20%D7%95%D7%A9%D7%90%D7%99%D7%A8%D7%99%D7%9D&dd=budget&range=all&lang=he&kind=regulations&fiscal-year=all

**Comment by akariv** [comment]
אלו שכן מופיעות נראות סבבה
