### ISSUE TITLE
hakol-kore: refresh action tips

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#414]
I updated the following files with new content, please implement, and let me know when ready for check:

* Tenders: https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit#gid=1250185114

* Tooltips: https://docs.google.com/spreadsheets/d/1ztsoslfvEiQS1jSTrivU6chvyAySIIV9tad0L1ZKGj8/edit?usp=sharing

We have been also asked to add action tips to support criteria and to supports - but I am not sure we are capable to do so without extra development, am I right?

**Comment by noamoss** [comment]
@akariv 
could not find the expected updated action tip on two open tenders (central + office):

* https://next.obudget.org/i/tenders/central/641227/15-2019?li=0&theme=socialmap

* https://next.obudget.org/i/tenders/office/642023/5/2019?li=8&theme=socialmap

am I missing something?

(this is the expected tip, I added to the file: "

למידע נוסף על השתתפות במכרזים ממשלתיים ראו באתר האוגדן 

http://haogdan.migzar3.org.il/%D7%9E%D7%9B%D7%A8%D7%96%D7%99%D7%9D_%D7%9C%D7%A8%D7%9B%D7%99%D7%A9%D7%AA_%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D_%D7%91%D7%A8%D7%A9%D7%95%D7%AA_%D7%9E%D7%A7%D7%95%D7%9E%D7%99%D7%AA_%D7%90%D7%95_%D7%9E%D7%A9%D7%A8%D7%93_%D7%9E%D7%9E%D7%A9%D7%9C%D7%AA%D7%99)
"

**Comment by akariv** [comment]
Action tips get updated every day or so.

**Comment by noamoss** [comment]
checked and approved.
