### ISSUE TITLE
fix socialmap about-us mobile display

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#419]
on https://next.obudget.org/about/?theme=socialmap (mobile display):

![image](https://user-images.githubusercontent.com/3581741/69485893-f3932980-0e4d-11ea-93a3-9bc0cfe54e5f.png)

1. fix logging avatar
2. search icon leads to the next.obudget search, instead of the social map customized search.

**Comment by akariv** [comment]
Fixed

**Comment by noamoss** [comment]
checked and approved.
