### ISSUE TITLE
תוכן קול קורא לא מעודכן

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#428]
פרסום במפתח 

https://next.obudget.org/i/calls_for_bids/call_for_bids/271726178/0?li=9&theme=socialmap

א. הקישור לפרסום המקורי לא רלוונטי כי מוביל לאתר בית של ג'וביז
ב. הקישור שבגוף הטקסט מוביל לפרסום בגוב עם טקסט אחר, שכולל גם מועד הגשה ומסומן בסטטוס סגור, אף כבפתח הוא מסומן כפתוח

https://www.gov.il/he/Departments/publications/Call_for_bids/promoting-employment-bedouin-women

**Comment by noamoss** [comment]
@maryLoi 

>א. הקישור לפרסום המקורי לא רלוונטי כי מוביל לאתר בית של ג'וביז

אין לנו מה לעשות עם זה - לפרסומים בג'וביז אין קישור ישיר וזו הדרך שלנו לספר למשתמשים מאין הבאנו את המידע

@akariv this is a bug indeed:

> ב. הקישור שבגוף הטקסט מוביל לפרסום בגוב עם טקסט אחר, שכולל גם מועד הגשה ומסומן בסטטוס סגור, אף כבפתח הוא מסומן כפתוח

also notice the source includes a publication date, and our item say 'unknown'

**Comment by noamoss** [comment]
@maryLoi  on a 2nd thought, it is not a bug - the original publication (jobiz) referneced to a secondary publication (gov.il) - we can not combine/update the data we show. closing issue.
