### ISSUE TITLE
תאריך פרסום ותאריך הגשה לא נכון של קול קורא

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#429]
https://next.obudget.org/i/calls_for_bids/call_for_bids/92535/53e4419f-5df5-4816-be9b-042f7ab7bbcf?li=21&theme=socialmap

ק.ק. מ-2018 שבו כתוב

מועד פרסום:  31/12/2019 11:30
מועד סגירה:  31/12/2019 11:30

**Comment by akariv** [comment]
שדה מועד הפרסום הציג בטעות את המועד הסגירה.
תוקן.
