### ISSUE TITLE
מבחן תמיכה ריק

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#430]
בחיפוש כללי של כל מבחני תמיכה יש כמה רשומות ריקות,

https://next.obudget.org/i/support_criteria/support_criteria/138651074/0?li=49&theme=socialmap
![image](https://user-images.githubusercontent.com/8996235/70396470-f0816700-1a11-11ea-951b-111a21cea200.png)

**Comment by akariv** [comment]
יסתדר ברגע שנעבור לקחת את המידע הזה מגיידסטאר

**Comment by akariv** [comment]
הסתדר, הפריט כבר לא מופיע בחיפוש
