### ISSUE TITLE
missing gov.il publicaiton

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#431]
missing publication (kol kore) from gov.il:

קול קורא להצעת התערבויות טיפוליות עבור גברים פוגעים ונפגעים במערכות יחסים זוגיות

https://www.gov.il/he//departments/publications/Call_for_bids/molsa-voice-of-call-30-11-2019

**Comment by noamoss** [comment]
(reported by @maryLoi )

**Comment by maryLoi** [comment]
עוד קול קורא חסר

בקשות לתמיכה מתקציב משרד התרבות והספורט לשנת 2020 – מינהל הספורט
https://www.gov.il/he/departments/publications/Call_for_bids/sport_support_2020

תוצאות החיפוש בגוב
https://www.gov.il/he/departments/publications/?limit=10&OfficeId=7d5d01a1-c043-4c87-b8ef-5061999e797c&rfpStatusType=c8ed2e3c-e5a9-4101-93f5-bae798c4ac1d&publicationType=7159e036-77d5-44f9-a1bf-4500e6125bf1

**Comment by akariv** [comment]
Here it is:
https://next.obudget.org/i/calls_for_bids/call_for_bids/145397/0282a462-a352-476f-9570-10b524b653de?li=4

https://next.obudget.org/i/calls_for_bids/call_for_bids/149158/a232751a-b101-4588-a2dc-cf52bcd53a8a?li=0

**Comment by akariv** [comment]
<img width="1057" alt="Screen Shot 2019-12-25 at 17 07 00" src="https://user-images.githubusercontent.com/265333/71447595-fdec6000-2738-11ea-8a2e-b9a89d74a33e.png">
<img width="933" alt="Screen Shot 2019-12-25 at 17 06 32" src="https://user-images.githubusercontent.com/265333/71447596-fdec6000-2738-11ea-8cee-e88c13244aec.png">
