### ISSUE TITLE
missing publications from pob.education

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#433]
רוב הק"ק מאתר משרד החינוך נסרקים. כמה חסרים:
https://pob.education.gov.il/KolotKorim/Pages/KolKore.aspx

תקצוב רשויות עבור תוכנית מרחבי למידה ירוקים (מל"י) לשנת התקציב 2020 ואילך
תקצוב בתי ספר משלבים עבור הדרכה פדגוגית לשנת הלימודים תש"ף
תקצוב עבור הצטיידות מעבדות למקצוע הכימיה למגמות חדשות ולמגמות וותיקות – תש"ף

**Comment by maryLoi** [comment]
תיקון: מהדוגמאות הנ"ל רק זה לא נמצא
תקצוב בתי ספר משלבים עבור הדרכה פדגוגית לשנת הלימודים תש"ף

**Comment by akariv** [comment]
https://next.obudget.org/i/calls_for_bids/call_for_bids/654246041/0?li=0
