### ISSUE TITLE
סטטוס קול קורא לא נכון

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#434]
במועד סגירה מצויין תאריך של אתמול 10/12/2019  אבל הסטטוס שלו פתוח
https://next.obudget.org/i/calls_for_bids/call_for_bids/605248618/0?li=10&theme=socialmap

![image](https://user-images.githubusercontent.com/8996235/70654372-ddafa200-1c5e-11ea-81ba-c4648e012cf9.png)

**Comment by akariv** [comment]
Fixed.
