### ISSUE TITLE
redesign logos and hakol-kore landing page

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#435]
1. Rearrange the logos in the hakol-kore landing page following the demo:

![תמונה](https://user-images.githubusercontent.com/3581741/71035796-f91a2180-2124-11ea-80c6-4ab7f863f4a1.png)

(notice, the combined text in the lower part should be: 

פיתוח הכלי נעשה בתמיכת ["מיזם ממשלה-חברה אזרחית"](http://www.theinstitute.org.il/index.php?dir=site&page=programs&op=view&cs=131&langpage=heb) - שותפות של ממשלת ישראל והמכון למנהיגות וממשל בג'וינט ישראל, ובשיתוף פעולה בתוכנית חברתית עם מגדל חברה לביטוח.

2. Replace the Hasadna's logo [on this page](https://socialmap.org.il/hakol-kore) into 3 languages logo: 
https://drive.google.com/file/d/1urrpYyXVHbh7h3euZVsR5ftJRmXVkhFn/view?usp=sharing

3. Replace Joint logo with the attached file

![אלכא-מיזם ממשלה - חברה אזרחית](https://user-images.githubusercontent.com/3581741/71122807-11a03f80-21ea-11ea-9901-bd67c34aa0ee.png)
![אלכא-מיזם ממשלה - חברה אזרחית](https://user-images.githubusercontent.com/3581741/71122808-14029980-21ea-11ea-9a2b-de164a8af0e9.jpg)

4. add (בהרצה) to the intro paragraph:

![תמונה](https://user-images.githubusercontent.com/3581741/71123083-88d5d380-21ea-11ea-9981-9f162063aae5.png)

**Comment by maryLoi** [comment]
https://drive.google.com/open?id=1RjTHCC8GPJct8-L4i9sFReqq4x_8IqWV

**Comment by noamoss** [comment]
@akariv updated the issue, following Dorit's recent email. ready to go

**Comment by noamoss** [comment]
@akariv updated the issue, following Dorit's recent email. It's on hold for now, waiting for her approval.

**Comment by noamoss** [comment]
@akariv finally, ready to go.

**Comment by noamoss** [comment]
@akariv please notice (following Dorit's request) that on mobile display the general shape (2 + 1) should remain, so both Hasadna and Manhigut Ezrachit logo will appear at the same height.

**Comment by noamoss** [comment]
checked and approved, sent an update to Dorit.
