### ISSUE TITLE
לאפשר מספר תקנה עם נקודות בחיפוש

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#437]
פעם היה אפשר להקליד מספר תקנה מפוסק בנקודות וזה היה עובד, והיום לא.
בעייתי במיוחד כי בטבלאות של נתוני הוצאות הלינקים למספרי תקנה לא עובדים ואנשים עושים קופי פייסט משם כמו שזה

למשל 20.43.03

**Comment by akariv** [comment]
it works
