### ISSUE TITLE
don't show `null` on budget transfer search results for unknown status

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#440]
![image](https://user-images.githubusercontent.com/3581741/71549464-86336500-29c6-11ea-8fe1-c0ea149367e8.png)

**Comment by akariv** [comment]
Reproduction:

https://next.obudget.org/s/?q=%D7%94%D7%A9%D7%AA%D7%AA%D7%A4%D7%95%D7%AA%20%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%92%D7%9E%D7%9C%D7%90%D7%99%D7%9D%20%D7%91%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F&dd=national-budget-changes&range=all&lang=he
