### ISSUE TITLE
obubdget tenders last activity filter is not filtering

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#441]
https://next.obudget.org/s/?q=%D7%A9%D7%99%D7%A7%D7%95%D7%9D&dd=procurement&range=last_month&lang=he&tender_type=all

![image](https://user-images.githubusercontent.com/3581741/71549530-9dbf1d80-29c7-11ea-90a2-04f6ec76c834.png)

(taken on Dec. 28 2019)

**Comment by akariv** [comment]
The activity period was not a 'last activity filter' at all, but literally an 'activity period' filter.

For example, the exemption in your screenshot (https://next.obudget.org/i/tenders/exemptions/587153/none?li=1) is active till 2021, so was definitely active during the last 30 days.

Either way, this confusion and the lack of usefulness of this filter plus the fact that we will add a proper sorting control soon lead me to the decision to remove it altogether from the UI.
