### ISSUE TITLE
redesign email header and improve intro text

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#444]
![תמונה](https://user-images.githubusercontent.com/3581741/72001795-ce684800-324e-11ea-81f4-71531e81ca4f.png)

* Assets: [link](https://www.figma.com/file/xc2kl2bphumgYDd2XurJhW/Emails?node-id=5%3A63)

1. link to: https://obudget.org/
2. link to: https://socialmap.org.il/
3. link to: https://next.obudget.org/govbuy/
4. link to: https://socialmap.org.il/hakol-kore
5. add the following intro header and paragraph:

זוכר/ת שביקשת שנעדכן אותך אם קורה משהו בנושאים השמורים שלך? אז המשכנו לחפש בכל מקורות המידע שזמינים לנו ומצאנו עוד כמה דברים שקרו מאז העדכון הקודם. 

את/ה תמיד יכול/ה גם [לשנות או להוסיף התראות חדשות](https://next.obudget.org/p/) או להוסיף מידע ממשפחת אתרי "מפתח התקציב".

**Comment by noamoss** [comment]
@akariv what do you think of the spec?

**Comment by akariv** [comment]
This is just the new header... I thought we were going to improve the intro
text as well @Noamoss <noamoss@gmail.com>

**Comment by akariv** [comment]
Done

**Comment by noamoss** [comment]
@akariv looks great (both on mobile and desktop).

1. one small textual fix is needed, please delete the following unnecessary words:

![image](https://user-images.githubusercontent.com/3581741/72175429-cc37f200-33e4-11ea-8224-c227d21817f2.png)

2. please see a follow-up (#447)

**Comment by noamoss** [comment]
@akariv reopening, until I can check and approve this issue.

**Comment by akariv** [comment]
@noamoss you should have received an email last week - can you confirm?

**Comment by noamoss** [comment]
yes, checked and approved.
