### ISSUE TITLE
fit personal page for returning anonymous users

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#447]
when clicking the 'saved alerts' link on the weekly mail, before logging in to our site, user sees the following screen:

![image](https://user-images.githubusercontent.com/3581741/72174537-a7427f80-33e2-11ea-9a23-d0ec81db5668.png)
following #444 

This is of course no true, because they just got here thanks to the alert mail.

I suggest to chane the explaination text on https://next.obudget.org/p/:

![image](https://user-images.githubusercontent.com/3581741/72175194-39975300-33e4-11ea-8f07-1e3e62bf9393.png)

1. הגעת לכאן, אבל עוד לא התחברת למערכת

2. [add the google login/register box]להתחברות עם חשבון הגוגל שלכם: 

3. חדשים כאן? אל חשש, בדף תוצאות החיפוש לחיצה קטנה על הכוכב בשורת החיפוש תרשום 
אותך לקבלת התראות בדוא"ל, שניתן יהיה לערוך בעמוד זה.

**Comment by akariv** [comment]
I didn't replace the text in the screen but instead a differentiated the cases for:
- not authenticated
- authenticated, no items
- authenticated, has items

**Comment by noamoss** [comment]
great, checked and approved.
