### ISSUE TITLE
לא מוצגות כל תוצאות החיפוש

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#448]
למשל נחפש "מבחנים לחלוקת כספי תמיכות של משרד הבריאות"

אין דרך לראות את כל התוצאות

![image](https://user-images.githubusercontent.com/8996235/72180292-83396b00-33ef-11ea-88b1-62de8dbbc9e1.png)

יש בפועל לא מעט מבחנים כאלה:
https://next.obudget.org/s/?q=%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%91%D7%A8%D7%99%D7%90%D7%95%D7%AA&dd=supports&range=last_year&lang=he&kind=support_criteria

**Comment by akariv** [comment]
I think this was already solved
