### ISSUE TITLE
חיפוש

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#450]
חיפשתי [כבאות](https://next.obudget.org/s/?q=%D7%9B%D7%91%D7%90%D7%95%D7%AA&dd=budget&range=all&lang=he&kind=all&fiscal-year=all)
לא ברור למה הסעיף השני הישן יותר של נציבות הכבאות לא מופיעה ברצף האחרי הראשון

![image](https://user-images.githubusercontent.com/8996235/72209491-62d4e380-34b7-11ea-897f-72c4b02d2bdd.png)

**Comment by akariv** [comment]
הוא קטן פי מאה מהשני ויושב תחת שלטון מקומי ולא בטחון פנים, אני לא בטוח שיש
קשר ביניהם
