### ISSUE TITLE
תמיכות ומענקים" הם בפועל קולות קוראים"

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#453]
חלק מהתמיכות ומענקים הם קולות קוראים לכל דבר. כרגע במפתח הם מסווגים כמבחני תמיכה וזה מאוד מטעה

https://www.gov.il/he/departments/publications/Call_for_bids/molsa-support-care-for-people-with-disabilities-and-their-rehabilitation-2020

כל הפרסומים של המשרדים הנ"ל הם קולות קוראים:
המשרד להגנת הסביבה
משרד הרווחה
משרד העליה

**Comment by akariv** [comment]
done
