### ISSUE TITLE
משרד הבריאות מפרסם קולות קוראים תחת השם מבחני תמיכה

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#454]
באתר משרד הבריאות כל מה שנקרא "מבחני תמיכה" הוא בקובץ אחד שרשור של קול קורא עם מבחן התמיכה. עדיף לשנות את הסיווג שלו ל"קול קורא"

https://www.health.gov.il/Subjects/Finance/Mtmicha/Pages/default.aspx

**Comment by akariv** [comment]
done
