### ISSUE TITLE
משרד הבריאות: קבצים לא רלוונטיים נסרקים 

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#455]
קבצים שמפורסמים כתת סעיף ומהווים טפסים או דוחות, נסרקים על ידינו כמבחני תמיכה

למשל [דוח ביצוע](https://next.obudget.org/i/support_criteria/support_criteria/528457603/0?li=50&theme=socialmap
)

https://www.health.gov.il/Subjects/Finance/Mtmicha/Pages/default.aspx

![image](https://user-images.githubusercontent.com/8996235/72270432-d0a31b80-362d-11ea-9cd1-ca9468f4adcd.png)

**Comment by akariv** [comment]
These are now being scanned as קולות קוראים
