### ISSUE TITLE
inconsistent results while quering for knwon Joint items

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#457]
1. searching [this item from the joint site](http://www2.jdc.org.il/he/jobs/2439) by full title in the budget key, doesn't show the expected item ([search result link](https://next.obudget.org/s/?q=%D7%9E%D7%9B%D7%A8%D7%96%20%D7%9C%D7%A8%D7%9B%D7%99%D7%A9%D7%AA%20%D7%95%D7%90%D7%A1%D7%A4%D7%A7%D7%AA%20%D7%A8%D7%99%D7%94%D7%95%D7%98%20%D7%9C%D7%9E%D7%A8%D7%9B%D7%96%D7%99%20%D7%94%D7%9B%D7%95%D7%95%D7%9F%20%D7%90%D7%A4%20+60&dd=all&range=all&lang=he)):
![image](https://user-images.githubusercontent.com/3581741/72383834-ee9f7780-3724-11ea-8b37-8f39c8aa7020.png)

2. deleting the last characters, gradually, one by one, from the end of the query does not show the expected results, until...

3. deleting the entire number and the plus sign works [search results link](https://next.obudget.org/s/?q=%D7%9E%D7%9B%D7%A8%D7%96%20%D7%9C%D7%A8%D7%9B%D7%99%D7%A9%D7%AA%20%D7%95%D7%90%D7%A1%D7%A4%D7%A7%D7%AA%20%D7%A8%D7%99%D7%94%D7%95%D7%98%20%D7%9C%D7%9E%D7%A8%D7%9B%D7%96%D7%99%20%D7%94%D7%9B%D7%95%D7%95%D7%9F&dd=all&range=all&lang=he):
![image](https://user-images.githubusercontent.com/3581741/72383949-30c8b900-3725-11ea-9017-7c09e6d885c6.png)

**Comment by akariv** [comment]
https://next.obudget.org/s/?q=%D7%92%27%D7%95%D7%99%D7%A0%D7%98%20%D7%99%D7%A9%D7%A8%D7%90%D7%9C:%20%D7%9E%D7%9B%D7%A8%D7%96%20%D7%9C%D7%A8%D7%9B%D7%99%D7%A9%D7%AA%20%D7%95%D7%90%D7%A1%D7%A4%D7%A7%D7%AA%20%D7%A8%D7%99%D7%94%D7%95%D7%98%20%D7%9C%D7%9E%D7%A8%D7%9B%D7%96%D7%99%20%D7%94%D7%9B%D7%95%D7%95%D7%9F%20%D7%90%D7%A4%20+60&dd=all&range=all&lang=he

**Comment by noamoss** [comment]
@akariv did you fix anything here? can you explain the essence of this usse?

**Comment by akariv** [comment]
Yes, there was a bug in the theme definition that prevented certain results from showing.

This is the fixing commit:

https://github.com/OpenBudget/budgetkey-themes/commit/d866b1786713114bf8d96536939215330f32cc48
