### ISSUE TITLE
no hint for clicking menu

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#46]
![image](https://user-images.githubusercontent.com/8996235/38043309-708e39b4-32bf-11e8-8608-e43058130ef6.png)

כשעומדים עם העכבר על החץ לא מופיע סמן בצורת יד המרמז על אזור לחיץ. העכבר נשאר בצורת חץ

**Comment by simonbor** [comment]
css fix

**Comment by simonbor** [comment]
please close

**Comment by YoniA** [comment]
is this issue still open?

**Comment by akariv** [comment]
nope, closing
