### ISSUE TITLE
update  `נסגר להגשות, ממתין לפרסום תוצאות` behaviour

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#463]
Following this item:
https://next.obudget.org/i/tenders/central/645818/technology-cloud_tender
![image](https://user-images.githubusercontent.com/3581741/74021914-2d7fc080-49a5-11ea-9e29-6c37dbabee3e.png)

![image](https://user-images.githubusercontent.com/3581741/74022235-c44c7d00-49a5-11ea-8d8b-a383033f80b0.png)

We should:
1.  change the ambiguous `פורסם וממתין לתוצאות` label (in source) to appear the same in obudget (currently it is translated to `נסגר להגשות, ממתין לפרסום תוצאות`)
2. prevent `פורסם וממתין לתוצאות` from setting the item's status:  it should not set the item status to `סגור` - even though it might mean that in some scenarios. Instead, when this label appears in the חשכ"ל items,  the due date should define the item's status.

**Comment by akariv** [comment]
The fix here is to merely change the translations in the tenders
spreadsheet to the correct ones.
The email does not really care about the textual status, but looks at the
publication/due dates.

@Noamoss <noamoss@gmail.com>

**Comment by noamoss** [comment]
@akariv 

>The fix here is to merely change the translations in the tenders
spreadsheet to the correct ones.

[done](https://docs.google.com/spreadsheets/d/1JkZooBwoxKPlrXWWwUtNHLMdxc-iG0n5tdGZ23I8fYY/edit?usp=sharing) lines, 14-17.

>The email does not really care about the textual status but looks at the publication/due dates.

but the status filter on site does. What/how should it be defined in the `simple decision` field then (left it empty for now)?

**Comment by akariv** [comment]
I think this is פתוח

**Comment by noamoss** [comment]
@akariv not always. This is how I changed it:

![image](https://user-images.githubusercontent.com/3581741/74032935-cb7f8500-49bd-11ea-904f-14e6cc86634b.png)


I guess it will prevent errors like this issue but will keep closing tenders with documented transfers.
If it seems ok, please update here when you pushed the update to the site.

**Comment by noamoss** [comment]
checked and approved on live
