### ISSUE TITLE
supports criteria due date is scraped but not displayed

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#469]
while checking https://github.com/OpenBudget/BudgetKey/issues/408, found this problem.
See for example this item:
https://next.obudget.org/i/support_criteria/support_criteria/153722/ac3b7663-6cc1-41df-9292-dd0011aff968?li=1&theme=socialmap

![image](https://user-images.githubusercontent.com/3581741/74281177-a32db880-4d26-11ea-94d0-a22b2f407f76.png)

![image](https://user-images.githubusercontent.com/3581741/74281048-65309480-4d26-11ea-8327-2827a7858c22.png)

This item was updated with a new due date, we know it (see the red message) but do not display it in the item body.

**Comment by noamoss** [comment]
another quick example: https://www.gov.il/he/departments/publications/Call_for_bids/jerusalemgrantbio290817

**Comment by noamoss** [comment]
another quick example: https://next.obudget.org/i/support_criteria/support_criteria/17293/2dcdda50-4a29-437e-90e0-c2195c497997?li=4&theme=socialmap

**Comment by akariv** [comment]
we decided to change the type of these to 'call for bids', and keep only
the pure support criteria documents (from guidestar) in the support
criteria category.
as such, they do not have a claim date.

**Comment by akariv** [comment]
@noamoss 
This was applied, you should not be able to find any items with claim dates in the support criteria category

**Comment by noamoss** [comment]
@akariv 
I think the original problem remains after applying this solution. See [the example item above](https://next.obudget.org/i/support_criteria/support_criteria/153722/ac3b7663-6cc1-41df-9292-dd0011aff968?li=1&theme=socialmap): we know that a request to be submitted will not be checked:

![image](https://user-images.githubusercontent.com/3581741/75089403-10302200-5561-11ea-8be8-3037c5d5b1d6.png)

we can scrape this data and show it - and therefore let the user know about the due date?
What do I miss here?

// cc @maryLoi

**Comment by akariv** [comment]
This is the actual item - the one you linked above is not accessible via
search any more.

https://next.obudget.org/i/calls_for_bids/call_for_bids/153722/ac3b7663-6cc1-41df-9292-dd0011aff968?li=0
