### ISSUE TITLE
תפריט לא נסגר כשלוחצים מחוצה לו

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#47]
![image](https://user-images.githubusercontent.com/8996235/38043414-bad39c3a-32bf-11e8-8fa2-d689c615f4a0.png)

אחרי שנפתח התפירט, יש ציפייה שאם מקליקים באיזור כלשהו מחוץ לתפריט, הוא ייסגר

**Comment by GuyAdiv** [comment]
העלתי תיקון לזה
https://github.com/GuyAdiv/budgetkey-ng2-components
