### ISSUE TITLE
מנוע חיפוש לא מוצא

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#473]
אם מחפשים "העמותה להעצמה כלכלית לנשים" לא מקבלים שמות גופים כלל.

בפועל העמותה קיימת במאגר
https://next.obudget.org/i/org/association/580350460?li=0

**Comment by noamoss** [comment]
@maryLoi 
דווקא מצאתי. אם זה לא עובד אצלך, תכללי בבקשה צילום מסך וקישור למסך התוצאה:

![image](https://user-images.githubusercontent.com/3581741/75090057-ae26eb00-5567-11ea-9c6e-9c1ec4fa668d.png)

**Comment by noamoss** [comment]
@maryLoi אם עובד, סגרי בבקשה את הנושא

**Comment by akariv** [comment]
הארגון נקרא ״עמותה להעצמה כלכלית לנשים״ ולא ״העמותה להעצמה כלכלית לנשים״

תיקנתי את החיפוש כך שימצא גם עם שגיאות מסוג זה.
