### ISSUE TITLE
תצוגה דיפולטית של הטבלה לא תואמת נתונים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#476]
כל הכספים שהגוף הזה מקבל הם בהתקשרויות, והתצוגה הדיפולטית של הטבלה היא תמיכות. מבלבל
לא הוספת בכל מקום את האופציה של טבלה משולבת של רכש ותמיכות?

https://next.obudget.org/i/org/company/515707909?li=1
![image](https://user-images.githubusercontent.com/8996235/75274428-835cc100-580b-11ea-8dfe-7e6acaf6d2ca.png)

**Comment by maryLoi** [comment]
במקרה הזה יש רק תמיכות שאושרו, אין מידע על העברות בפועל. בתצוגה הדיפולטית נראה כאילו אין נתונים כלל
(צילום מסך של הנתונים שכן קיימים)
https://next.obudget.org/i/budget/0020460268/2019

![image](https://user-images.githubusercontent.com/8996235/75283509-b0b16b00-581b-11ea-95b9-b4050b6591c7.png)

**Comment by akariv** [comment]
I added the total expenses query to the org page now.

In the second case, there were no actual payments (only approvals) so the default list is empty.
