### ISSUE TITLE
התקשרות ללא פרטים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#480]
בדף הההתקשרות אין שום פרטים למרות שיש 42% ביצוע

https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%97%D7%99%D7%A0%D7%95%D7%9A/4501665051/0020670174?li=9

![image](https://user-images.githubusercontent.com/8996235/76887925-abc86000-688b-11ea-97df-eac84bbebde2.png)

**Comment by akariv** [comment]
נראה שזה העמוד הנכון של ההתקשרות, שעברה מתקנה לתקנה:

https://next.obudget.org/i/contract-spending/%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%97%D7%99%D7%A0%D7%95%D7%9A/4501665051/0020460454?li=0

הדף שאת הגעת אליו נראה ישן וכנראה צריך להימחק... אבדוק מדוע זה לא קרה
