### ISSUE TITLE
בעיה בהורדת הוצאות מתקנה

### ISSUE THREAD

**Issue by rkportal** [OpenBudget/BudgetKey#511]
הי

ניסיתי להוריד היום את ההוצאות מתקנה "19.42.02.50 ספריות פעולות" והגעתי לדף עם ההודעה הבאה:

הי
אני מנסה לגשת לטבלאת הנתונים על ההוצאות מתקנת הספריות במפתח התקציב, ואני מקבל שגיאת "Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
הדף ממנו ניסיתי לגשת לנתונים:
https://next.obudget.org/i/budget/0019420250/2024?li=0&theme=budgetkey
כתובת השגיאה:
https://next.obudget.org/api/download?query=with%20a%20as%20(%20select%20year_paid%20as%20%22%D7%A9%D7%A0%D7%94%22%2C%20entity_name%20as%20%22%D7%9E%D7%A7%D7%91%D7%9C%20%D7%94%D7%9B%D7%A1%D7%A4%D7%99%D7%9D%22%2C%20amount_paid%20as%20%22%D7%A1%D7%9A%20%D7%9B%D7%95%D7%9C%D7%9C%22%2C%20support_title%20as%20%22%D7%AA%D7%99%D7%90%D7%95%D7%A8%22%2C%20%27%D7%AA%D7%9E%D7%99%D7%9B%D7%94%27%20as%20%22%D7%A1%D7%95%D7%92%20%D7%94%D7%94%D7%95%D7%A6%D7%90%D7%94%22%20from%20supports_by_payment_year%20where%20budget_code%20%3D%20%270019400114%27%20and%20amount_paid%3E0%20and%20year_paid%20%3E0%20union%20select%20min_year%20as%20%22%D7%A9%D7%A0%D7%94%22%2C%20entity_name%20as%20%22%D7%9E%D7%A7%D7%91%D7%9C%20%D7%94%D7%9B%D7%A1%D7%A4%D7%99%D7%9D%22%2C%20executed%20as%20%22%D7%A1%D7%9A%20%D7%9B%D7%95%D7%9C%D7%9C%22%2C%20purpose%20as%20%22%D7%AA%D7%99%D7%90%D7%95%D7%A8%22%2C%20%27%D7%A8%D7%9B%D7%A9%27%20as%20%22%D7%A1%D7%95%D7%92%20%D7%94%D7%94%D7%95%D7%A6%D7%90%D7%94%22%20from%20contract_spending%20where%20budget_code%20%3D%20%270019400114%27%20and%20executed%20%3E%200%20and%20min_year%20%3E0)%20select%20*%20from%20a%20order%20by%20%22%D7%A9%D7%A0%D7%94%22%20desc%2C%20%22%D7%A1%D7%9A%20%D7%9B%D7%95%D7%9C%D7%9C%22%20desc&format=xlsx&filename=%D7%94%D7%A9%D7%AA%D7%AA%D7%A4%D7%95%D7%AA%20%D7%91%D7%AA%D7%9B%D7%A0%D7%99%D7%AA%20%D7%94%D7%9E%D7%95%22%D7%A4%20%D7%94%D7%90%D7%99%D7%A8%D7%95%D7%A4%D7%99%D7%AA__%D7%A4%D7%99%D7%A8%D7%95%D7%98%20%D7%9B%D7%9C%20%D7%94%D7%94%D7%95%D7%A6%D7%90%D7%95%D7%AA%20%D7%9E%D7%AA%D7%A7%D7%A0%D7%94%20%D7%96%D7%95%20%D7%A9%D7%A9%D7%95%D7%9C%D7%9E%D7%95%20%D7%91%20%D7%9B%D7%9C%20%D7%94%D7%A9%D7%A0%D7%99%D7%9D&headers=%D7%A9%D7%A0%D7%94%3B%D7%9E%D7%A7%D7%91%D7%9C%20%D7%94%D7%9B%D7%A1%D7%A4%D7%99%D7%9D%3B%D7%A1%D7%9A%20%D7%9B%D7%95%D7%9C%D7%9C%3Anumber%3B%D7%AA%D7%99%D7%90%D7%95%D7%A8%3B%D7%A1%D7%95%D7%92%20%D7%94%D7%94%D7%95%D7%A6%D7%90%D7%94

בבדיקה מהירה, הבעיה חוזרת גם בתקנות אחרות, ראו למשל כאן:
https://next.obudget.org/i/budget/0019400114/2024

ההוצאות עצמן מוצגות באתר באופן ברור, אבל בניסיון הורדה (גם של אקסל וגם של csv) האתר קורס

רועי

**Comment by akariv** [comment]
@rkportal 

תודה על הדיווח!

התקלה תוקנה.
