### ISSUE TITLE
.חבילה מחול שלחתי הצהרה למכס  כפי שבקשו מציטה.במכס טוענים שלא נמסר תצהיר שלכם  AE029986251

### ISSUE THREAD

**Issue by erzamoney** [OpenBudget/BudgetKey#514]

**Comment by erzamoney** [comment]
אצלכם באתר רשום שהטיפול הושלם ואין צורך בטיפול.
מה צריך לעשות כדי שהחבילה תגיע אלי.

**Comment by akariv** [comment]
לא יודע למה ההערה הזו קשורה אבל בטח לא אלינו. אתר מפתח התקציב מציג מידע שקשור לתקציב המדינה. נשמע שאתה צריך ליצור קשר עם חברה ספציפית ולא איתנו.
