### ISSUE TITLE
Plotly menu

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#52]
הכרחי שהתפריט יופיע? אין בו פונקציות שימושיות והוא רק מעמיס

![image](https://user-images.githubusercontent.com/8996235/38044620-0b79c88c-32c3-11e8-9e48-6e3a50660fe5.png)

**Comment by akariv** [comment]
התפריט מאפשר להוריד את הגרף כתמונה, זה די נחמד, לא?

**Comment by akariv** [comment]
בכל מקרה אני לא חושב שנתעסק עם זה עד שנחליף את הגרף הזה במשהו אחר (כשיהיה עיצוב)
