### ISSUE TITLE
ייצוג למספרים גדולים בגרף

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#57]
גם האותיות באנגלית מבלבלות:
M = מיליון או מיליארד ?

גם 3 או 4 ספרות אחרי נקודה מבלבל

![image](https://user-images.githubusercontent.com/8996235/38092179-354ec236-3370-11e8-9a94-5ac2e10ffed9.png)

**Comment by akariv** [comment]
Same comment as in https://github.com/OpenBudget/BudgetKey/issues/52
