### ISSUE TITLE
תוצאות חיפוש  - תקנה עם שני אפסים מובילים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#61]
תסריט 1 - מחפשים תקנה 23011104
בתוצאות תופיע שורה אחת עם התוצאה המדוייקת
![image](https://user-images.githubusercontent.com/8996235/38093551-fec39d32-3373-11e8-96db-3d6ffc021f21.png)

תסריט 2 - מתוך פירוט התמיכות בדף ארגון לוחצים על תקנה 0023011104
מקבלים הרבה תוצאות חיפוש
http://next.obudget.org/s/?q=0023011104&dd=budget

**Comment by akariv** [comment]
מקבלים 2, לא הרבה...

duplicate of #189
