### ISSUE TITLE
Add EU logo to about page

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#85]
add EU logo + disclaimer:
download logo [here](https://europa.eu/european-union/about-eu/symbols/flag_en)

- font size should be proportionate to the size of the flag.
- colour of the font : **reflex blue** (same blue as the EU flag), **black** or **white** depending on the background
- typeface allowed: Arial, Calibri, Garamond, Trebuchet, Tahoma, Verdana.
- not in italics
- flag must be positioned well apart from the implementing organization's logo

**example:**
![image](https://user-images.githubusercontent.com/8996235/39201787-b84c4fea-47f8-11e8-9f37-170140eb7d7d.png)

**text to go under the flag:**
This Project is funded by the European Union
פרויקט זה מתבצע במימון האיחוד האירופי 
هذا المشروع ممول من قبل الاتحاد الأوروبي 
___________________________________________

**disclaimer text:**
This website was created and maintained with the financial support of the European Union. Its contents are the sole responsibility of the Public Knowledge Workshop and do not necessarily reflect the views of the European Union.

**Comment by maryLoi** [comment]
add disclaimer in 3 languages:


This website was created and maintained with the financial support of the European Union. 
Its contents are the sole responsibility of the Public Knowledge Workshop and do not necessarily reflect the views of the European Union.

אתר זה מפותח ומתוחזק בסיוע האיחוד האירופי. האחריות הבלעדית על תכניו נתונה בידי הסדנא לידע ציבורי ואינם בהכרח משקפים את עמדות האיחוד האירופי. 
 
-تم إعداد هذا الموقع وصيانته بمساعدة مالية من الاتحاد الأوروبي. محتويات الفيديو من مسؤولية  الورشة للمعرفة الجماهيرية و لا تعكس بأي حال من الأحوال وجهات نظر او آراء الاتحاد الاوروبي.

**Comment by noamoss** [comment]
let's follow up on #210.
