### ISSUE TITLE
צבע מבצבץ

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#87]
שאריות צבע מבצבצות מתחת לטקסט

![image](https://user-images.githubusercontent.com/8996235/39405904-ea82464c-4bb6-11e8-9563-d8888bb451de.png)

**Comment by maryLoi** [comment]
![image](https://user-images.githubusercontent.com/8996235/39405916-1f505d3c-4bb7-11e8-8383-3b8419724c6b.png)

**Comment by maryLoi** [comment]
![image](https://user-images.githubusercontent.com/8996235/39405960-bee61bf2-4bb7-11e8-854f-d81ea3f9641f.png)

**Comment by akariv** [comment]
Duplicate of https://github.com/OpenBudget/mushonkey/issues/4
