### ISSUE TITLE
Recent supports data missing on next.obudget.org

### ISSUE THREAD

**Issue by shevyk** [OpenBudget/BudgetKey#9]
Supports data from recent years appears to be missing on next.obudget.org
e.g.

http://next.obudget.org/i/budget/0020460119/2018
lists supports data up to 2015

http://www.obudget.org/#budget/20460119/2018/main?tab=supports
lists supports data up to 2016

2017 and 2018 data are missing from both.

**Comment by akariv** [comment]
@shevyk the data is not missing, but we're showing only 100 first rows of the data.
Please take a look now and see if the was it's displayed is more understandable now.

**Comment by shevyk** [comment]
Thanks. it's clearer now. 
Please see issue #10 on data download.
