### ISSUE TITLE
מינוס לפני הסכום

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#91]
חיפוש: [חיסונים](https://next.obudget.org/s/?q=%D7%97%D7%99%D7%A1%D7%95%D7%A0%D7%99%D7%9D&range=last_decade&dd=budget)

![image](https://user-images.githubusercontent.com/8996235/39406630-23da783c-4bc2-11e8-89ea-5885b841abb0.png)

**Comment by akariv** [comment]
מדובר בסעיף הכנסה -איך היית מציעה להציג את זה?

**Comment by maryLoi** [comment]
אפשר לכתוב מתחת למספר את המילה הכנסה

![image](https://user-images.githubusercontent.com/8996235/39444547-daab28c8-4cc0-11e8-9c94-d814b13e671e.png)

**Comment by akariv** [comment]
Delegated to #209
