### ISSUE TITLE
Fix markup to fit long associations names 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#92]
![image](https://user-images.githubusercontent.com/3581741/39427361-214fea82-4c8c-11e8-9356-cb3404294cec.png)

when association name is longer than one line, we should expand the green background stripe

**Comment by akariv** [comment]
screenshot is no longer relevant but recent example is this

https://next.obudget.org/i/org/association/580012110?li=9

**Comment by GuyAdiv** [comment]
suggested new style:
![page.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2a50889afcb40013bb8218/125516c66e82c728ace21e0d46f8959d26c0cfeb9ffbb049a15ee4d67304722b7f5dfb7d22dde17ee7102e035e574eac400e5d4cf4ac9b37b4f46d2ede0356b49b381d66cc2f10abb2831aba01bf2188488cb4bd884ad2a5.jpg)
old style:
![page_before.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2a50889afcb40013bb8218/125516c66e82c728ace21e0d46f8959d26bd81ac89e6ad46e611b2843b492d762a10e17132d0bb7ee61a2d53570d48a4435d0d45f4f9892af0b43478df4e17ff933c0120996048e6edc00db513bb27814e80b3bc8f4dc3e03b23e58e8c5d73.jpg)

**Comment by noamoss** [comment]
hi @GuyAdiv welcome aboard, and thanks for the suggestion.

There is one thing to consider here: the annual budget is the most important data point of this content type (except for the the organization name, of course). Could think of a way to emphasize it, make it more?

// cc @mushon

**Comment by akariv** [comment]
Also still need to show how multiline would look :)

**Comment by noamoss** [comment]
checked on live and approved.
