### ISSUE TITLE
SocialMap Adamke: set height for 10 items

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#99]
Adamke block should be limited site-wide to 10 items (rows). Notice that in case of fewer than 10 items, the height should be increased to 10 lines as well.

Relevant for 

- Homepage (third tab)
- Areal page 
- Field of activity page (second tab, last tab)

**Comment by noamoss** [comment]
@akariv reopenning as the fix wasn't implemented on 

- areal page ([see example](http://next.obudget.org/i/reports/ngo-district-report/%D7%94%D7%A6%D7%A4%D7%95%D7%9F?li=0&theme=socialmap))

**Comment by noamoss** [comment]
@akariv reopening for the 2nd time: it is not implemented in the areal pages yet

**Comment by akariv** [comment]
@noamoss this is not an Adamke chart...

**Comment by noamoss** [comment]
you're right, my bad.

checked and approved on live.
